import { Injectable } from '@angular/core';
import { TreasureGenerator } from './treasure-generator';
import { GeneratedTreasure, tabelaTesouroItens, TreasureContext } from '../model/treasure';

@Injectable({ providedIn: 'root' })
export class EquipmentTreasureGenerator implements TreasureGenerator {
  constructor() {}

  public generate(ctx: TreasureContext): GeneratedTreasure {
    let nivel = String(ctx.level).trim();
    const tabelaItemNivel = tabelaTesouroItens.filter((item: any) => item.nd === Number(nivel));
    const linhaItemNivel: any = tabelaItemNivel.find((item: any) => ctx.random! >= item.min && ctx.random! <= item.max);

    let tesouro: any[] = [];
    let gt: { items: any; return: string; notes: string; report: string };

    let randomEquipamento = Math.floor(Math.random() * 6) + 1;
    let linhaEquipamento = this.tipoEquipamento.find((item: any) => randomEquipamento === item.id);

    if (linhaEquipamento!.nome === 'Arma') {
      tesouro.push(this.gerarEquipamento(linhaItemNivel, this.equipamentoArmas, this.melhoriasSuperioresArmas, 66, 74));
    } else if (linhaEquipamento!.nome === 'Armadura') {
      tesouro.push(
        this.gerarEquipamento(linhaItemNivel, this.equipamentoArmaduras, this.melhoriasSuperioresArmaduras, 50, 59)
      );
    } else {
      tesouro.push(
        this.gerarEquipamento(linhaItemNivel, this.equipamentoEsoterico, this.melhoriasSuperioresEsotericos, 62, 70)
      );
    }

    gt = {
      items: linhaItemNivel,
      return: linhaItemNivel.nome,
      notes: linhaItemNivel.unidade,
      report: this.gerarRelatorio(ctx.random!, linhaItemNivel, tesouro),
    };

    return gt;
  }

  private gerarEquipamento(
    linhaItemNivel: any,
    tabelaEquipamento: any,
    tabelaMelhoria: any,
    inicio: number,
    fim: number
  ) {
    let randomEquipamento = Math.floor(Math.random() * 100) + 1;
    let equipamento = tabelaEquipamento.find((item: any) => randomEquipamento === item.id);
    equipamento.melhorias = [];

    if (linhaItemNivel.valor.includes('Superior')) {
      const numero = Number(linhaItemNivel.modificador.match(/\d+/)?.[0] || 0);
      let materialEspecial = false;
      for (let i = 1; i <= numero; i++) {
        let randomMelhoriaSuperior = Math.floor(Math.random() * 100) + 1;
        let melhoria = tabelaMelhoria.find((item: any) => randomMelhoriaSuperior === item.id);

        if (melhoria.nome === 'Material especial' && !materialEspecial) {
          materialEspecial = true;
          let randomMaterialEspecial = Math.floor(Math.random() * 6) + 1;
          melhoria = tabelaMelhoria.find((item: any) => randomMaterialEspecial === item.id);
        } else {
          randomMelhoriaSuperior = this.randomIntervaloBanido(inicio, fim);
          melhoria = tabelaMelhoria.find((item: any) => randomMelhoriaSuperior === item.id);
        }

        equipamento.melhorias.push(melhoria);
      }
    }

    return equipamento;
  }

  randomIntervaloBanido(inicio: number, fim: number) {
    let numero;

    do {
      numero = Math.floor(Math.random() * 100) + 1; // 1 a 100
    } while (numero >= 66 && numero <= 75); // intervalo proibido

    return numero;
  }

  private gerarRelatorio(random: number, linha: any, equipamentos: any): string {
    const linhasHtml = equipamentos
      .map((item: any) => `<li>${item.id} - ${item.nome} ${this.relatorioMelhorias(item)}</li>`)
      .join('');

    let labelEquipamento = linha.valor.includes('2D') ? linha.valor + '(escolha um)' : linha.valor;

    return `
      <b>ITEM</b><br />
      <label><b>RESULTADO D100:</b> ${random}</label><br />
      <label><b>${labelEquipamento}:</b></label>
      <ul>
          ${linhasHtml}
      </ul>
      `;
  }

  private relatorioMelhorias(item: any) {
    let relatorioMelhoria = item.melhorias.map((p: any) => p.nome).join(', ');
    return `(${relatorioMelhoria})`;
  }

  tipoEquipamento = [
    { id: 1, nome: 'Arma' },
    { id: 2, nome: 'Arma' },
    { id: 3, nome: 'Arma' },
    { id: 4, nome: 'Armadura' },
    { id: 5, nome: 'Armadura' },
    { id: 6, nome: 'Esotérico' },
  ];

  equipamentoArmas = [
    { id: 1, nome: 'Açoite finntroll', livro: 'Ameaças de Arton', pagina: 392 },
    { id: 2, nome: 'Adaga', livro: 'Tormenta20', pagina: 146 },
    { id: 3, nome: 'Adaga oposta', livro: 'Heróis de Arton', pagina: 216 },
    { id: 4, nome: 'Agulha de Ahlen', livro: 'Heróis de Arton', pagina: 216 },
    { id: 5, nome: 'Alabarda', livro: 'Tormenta20', pagina: 146 },
    { id: 6, nome: 'Alfange', livro: 'Tormenta20', pagina: 146 },
    { id: 7, nome: 'Arcabuz', livro: 'Ameaças de Arton', pagina: 392 },
    { id: 8, nome: 'Arco curto', livro: 'Tormenta20', pagina: 146 },
    { id: 9, nome: 'Arco de guerra', livro: 'Heróis de Arton', pagina: 216 },
    { id: 10, nome: 'Arco longo', livro: 'Tormenta20', pagina: 146 },
    { id: 11, nome: 'Arco montado', livro: 'Heróis de Arton', pagina: 216 },
    { id: 12, nome: 'Arpão', livro: 'Ameaças de Arton', pagina: 392 },
    { id: 13, nome: 'Azagaia', livro: 'Tormenta20', pagina: 146 },
    { id: 14, nome: 'Bacamarte', livro: 'Ameaças de Arton', pagina: 392 },
    { id: 15, nome: 'Balas (20)', livro: 'Tormenta20', pagina: 151 },
    { id: 16, nome: 'Balestra', livro: 'Heróis de Arton', pagina: 216 },
    { id: 17, nome: 'Bastão lúdico', livro: 'Heróis de Arton', pagina: 216 },
    { id: 18, nome: 'Besta de mão', livro: 'Heróis de Arton', pagina: 216 },
    { id: 19, nome: 'Besta de repetição', livro: 'Heróis de Arton', pagina: 216 },
    { id: 20, nome: 'Besta dupla', livro: 'Heróis de Arton', pagina: 216 },
    { id: 21, nome: 'Besta leve', livro: 'Tormenta20', pagina: 146 },
    { id: 22, nome: 'Besta pesada', livro: 'Tormenta20', pagina: 146 },
    { id: 23, nome: 'Bico de corvo', livro: 'Heróis de Arton', pagina: 216 },
    { id: 24, nome: 'Boleadeira', livro: 'Heróis de Arton', pagina: 216 },
    { id: 25, nome: 'Bordão', livro: 'Tormenta20', pagina: 147 },
    { id: 26, nome: 'Canhão portátil', livro: 'Heróis de Arton', pagina: 217 },
    { id: 27, nome: 'Chakram', livro: 'Heróis de Arton', pagina: 217 },
    { id: 28, nome: 'Chicote', livro: 'Tormenta20', pagina: 147 },
    { id: 29, nome: 'Cimitarra', livro: 'Tormenta20', pagina: 147 },
    { id: 30, nome: 'Cinquedea', livro: 'Heróis de Arton', pagina: 217 },
    { id: 31, nome: 'Clava', livro: 'Tormenta20', pagina: 147 },
    { id: 32, nome: 'Clava-grão', livro: 'Heróis de Arton', pagina: 217 },
    { id: 33, nome: 'Corrente de espinhos', livro: 'Tormenta20', pagina: 147 },
    { id: 34, nome: 'Desmontador', livro: 'Heróis de Arton', pagina: 217 },
    { id: 35, nome: 'Dirk', livro: 'Heróis de Arton', pagina: 217 },
    { id: 36, nome: 'Espada bastarda', livro: 'Tormenta20', pagina: 147 },
    { id: 37, nome: 'Espada canora', livro: 'Heróis de Arton', pagina: 217 },
    { id: 38, nome: 'Espada curta', livro: 'Tormenta20', pagina: 148 },
    { id: 39, nome: 'Espada de execução', livro: 'Heróis de Arton', pagina: 217 },
    { id: 40, nome: 'Espada larga', livro: 'Heróis de Arton', pagina: 217 },
    { id: 41, nome: 'Espada longa', livro: 'Tormenta20', pagina: 148 },
    { id: 42, nome: 'Espada vespa', livro: 'Ameaças de Arton', pagina: 392 },
    { id: 43, nome: 'Espada-gadanho', livro: 'Heróis de Arton', pagina: 217 },
    { id: 44, nome: 'Espadim', livro: 'Heróis de Arton', pagina: 217 },
    { id: 45, nome: 'Flechas (20)', livro: 'Tormenta20', pagina: 151 },
    { id: 46, nome: 'Flechas de caça (20)', livro: 'Heróis de Arton', pagina: 223 },
    { id: 47, nome: 'Florete', livro: 'Tormenta20', pagina: 148 },
    { id: 48, nome: 'Foice', livro: 'Tormenta20', pagina: 148 },
    { id: 49, nome: 'Funda', livro: 'Tormenta20', pagina: 148 },
    { id: 50, nome: 'Gadanho', livro: 'Tormenta20', pagina: 148 },
    { id: 51, nome: 'Garrucha', livro: 'Heróis de Arton', pagina: 219 },
    { id: 52, nome: 'Gládio', livro: 'Ameaças de Arton', pagina: 392 },
    { id: 53, nome: 'Katana', livro: 'Tormenta20', pagina: 148 },
    { id: 54, nome: 'Khopesh', livro: 'Heróis de Arton', pagina: 219 },
    { id: 55, nome: 'Kimbata', livro: 'Heróis de Arton', pagina: 219 },
    { id: 56, nome: 'Lança', livro: 'Tormenta20', pagina: 148 },
    { id: 57, nome: 'Lança de falange', livro: 'Heróis de Arton', pagina: 220 },
    { id: 58, nome: 'Lança de fogo', livro: 'Ameaças de Arton', pagina: 392 },
    { id: 59, nome: 'Lança de justa', livro: 'Heróis de Arton', pagina: 220 },
    { id: 60, nome: 'Lança montada', livro: 'Tormenta20', pagina: 148 },
    { id: 61, nome: 'Maça', livro: 'Tormenta20', pagina: 149 },
    { id: 62, nome: 'Maça-estrela', livro: 'Heróis de Arton', pagina: 220 },
    { id: 63, nome: 'Machadinha', livro: 'Tormenta20', pagina: 149 },
    { id: 64, nome: 'Machado anão', livro: 'Tormenta20', pagina: 149 },
    { id: 65, nome: 'Machado de batalha', livro: 'Tormenta20', pagina: 149 },
    { id: 66, nome: 'Machado de guerra', livro: 'Tormenta20', pagina: 149 },
    { id: 67, nome: 'Machado de haste', livro: 'Heróis de Arton', pagina: 220 },
    { id: 68, nome: 'Machado táurico', livro: 'Tormenta20', pagina: 149 },
    { id: 69, nome: 'Malho', livro: 'Heróis de Arton', pagina: 220 },
    { id: 70, nome: 'Mangual', livro: 'Tormenta20', pagina: 149 },
    { id: 71, nome: 'Marrão', livro: 'Heróis de Arton', pagina: 221 },
    { id: 72, nome: 'Marreta', livro: 'Tormenta20', pagina: 149 },
    { id: 73, nome: 'Martelo de guerra', livro: 'Tormenta20', pagina: 149 },
    { id: 74, nome: 'Martelo leve', livro: 'Heróis de Arton', pagina: 221 },
    { id: 75, nome: 'Martelo longo', livro: 'Heróis de Arton', pagina: 221 },
    { id: 76, nome: 'Montante', livro: 'Tormenta20', pagina: 150 },
    { id: 77, nome: 'Montante cinético', livro: 'Heróis de Arton', pagina: 221 },
    { id: 78, nome: 'Mordida do diabo', livro: 'Ameaças de Arton', pagina: 393 },
    { id: 79, nome: 'Mosquete', livro: 'Tormenta20', pagina: 150 },
    { id: 80, nome: 'Neko-te', livro: 'Ameaças de Arton', pagina: 393 },
    { id: 81, nome: 'Pedras (20)', livro: 'Tormenta20', pagina: 151 },
    { id: 82, nome: 'Picareta', livro: 'Tormenta20', pagina: 150 },
    { id: 83, nome: 'Pique', livro: 'Tormenta20', pagina: 150 },
    { id: 84, nome: 'Pistola', livro: 'Tormenta20', pagina: 150 },
    { id: 85, nome: 'Pistola-punhal', livro: 'Ameaças de Arton', pagina: 393 },
    { id: 86, nome: 'Porrete', livro: 'Ameaças de Arton', pagina: 393 },
    { id: 87, nome: 'Presa de serpente', livro: 'Ameaças de Arton', pagina: 393 },
    { id: 88, nome: 'Rapieira', livro: 'Heróis de Arton', pagina: 221 },
    { id: 89, nome: 'Rede', livro: 'Tormenta20', pagina: 150 },
    { id: 90, nome: 'Serrilheira', livro: 'Heróis de Arton', pagina: 221 },
    { id: 91, nome: 'Shuriken', livro: 'Ameaças de Arton', pagina: 394 },
    { id: 92, nome: 'Sifão cáustico', livro: 'Heróis de Arton', pagina: 222 },
    { id: 93, nome: 'Tacape', livro: 'Tormenta20', pagina: 150 },
    { id: 94, nome: 'Tai-tai', livro: 'Heróis de Arton', pagina: 222 },
    { id: 95, nome: 'Tan-korak', livro: 'Heróis de Arton', pagina: 222 },
    { id: 96, nome: 'Tetsubo', livro: 'Ameaças de Arton', pagina: 394 },
    { id: 97, nome: 'Traque', livro: 'Ameaças de Arton', pagina: 394 },
    { id: 98, nome: 'Tridente', livro: 'Tormenta20', pagina: 150 },
    { id: 99, nome: 'Virotes (20)', livro: 'Tormenta20', pagina: 151 },
    { id: 100, nome: 'Zarabatana', livro: 'Ameaças de Arton', pagina: 394 },
  ];

  equipamentoArmaduras = [
    { id: 1, nome: 'Armadura de chumbo', livro: 'Heróis de Arton', pagina: 223 },
    { id: 2, nome: 'Armadura de chumbo', livro: 'Heróis de Arton', pagina: 223 },
    { id: 3, nome: 'Armadura de engenhoqueiro goblin', livro: 'Heróis de Arton', pagina: 223 },
    { id: 4, nome: 'Armadura de engenhoqueiro goblin', livro: 'Heróis de Arton', pagina: 223 },
    { id: 5, nome: 'Armadura de folhas', livro: 'Heróis de Arton', pagina: 223 },
    { id: 6, nome: 'Armadura de folhas', livro: 'Heróis de Arton', pagina: 223 },
    { id: 7, nome: 'Armadura de hussardo alado', livro: 'Heróis de Arton', pagina: 223 },
    { id: 8, nome: 'Armadura de hussardo alado', livro: 'Heróis de Arton', pagina: 223 },
    { id: 9, nome: 'Armadura de justa', livro: 'Heróis de Arton', pagina: 223 },
    { id: 10, nome: 'Armadura de justa', livro: 'Heróis de Arton', pagina: 223 },
    { id: 11, nome: 'Armadura de ossos', livro: 'Ameaças de Arton', pagina: 395 },
    { id: 12, nome: 'Armadura de pedra', livro: 'Heróis de Arton', pagina: 224 },
    { id: 13, nome: 'Armadura de pedra', livro: 'Heróis de Arton', pagina: 224 },
    { id: 14, nome: 'Armadura de quitina', livro: 'Ameaças de Arton', pagina: 395 },
    { id: 15, nome: 'Armadura sensual', livro: 'Heróis de Arton', pagina: 224 },
    { id: 16, nome: 'Armadura sensual', livro: 'Heróis de Arton', pagina: 224 },
    { id: 17, nome: 'Brigantina', livro: 'Heróis de Arton', pagina: 224 },
    { id: 18, nome: 'Brigantina', livro: 'Heróis de Arton', pagina: 224 },
    { id: 19, nome: 'Brigantina', livro: 'Heróis de Arton', pagina: 224 },
    { id: 20, nome: 'Brigantina', livro: 'Heróis de Arton', pagina: 224 },
    { id: 21, nome: 'Broquel', livro: 'Heróis de Arton', pagina: 224 },
    { id: 22, nome: 'Broquel', livro: 'Heróis de Arton', pagina: 224 },
    { id: 23, nome: 'Brunea', livro: 'Tormenta20', pagina: 154 },
    { id: 24, nome: 'Brunea', livro: 'Tormenta20', pagina: 154 },
    { id: 25, nome: 'Brunea', livro: 'Tormenta20', pagina: 154 },
    { id: 26, nome: 'Brunea', livro: 'Tormenta20', pagina: 154 },
    { id: 27, nome: 'Colete fora da lei', livro: 'Heróis de Arton', pagina: 226 },
    { id: 28, nome: 'Colete fora da lei', livro: 'Heróis de Arton', pagina: 226 },
    { id: 29, nome: 'Completa', livro: 'Tormenta20', pagina: 154 },
    { id: 30, nome: 'Completa', livro: 'Tormenta20', pagina: 154 },
    { id: 31, nome: 'Completa', livro: 'Tormenta20', pagina: 154 },
    { id: 32, nome: 'Completa', livro: 'Tormenta20', pagina: 154 },
    { id: 33, nome: 'Completa', livro: 'Tormenta20', pagina: 154 },
    { id: 34, nome: 'Completa', livro: 'Tormenta20', pagina: 154 },
    { id: 35, nome: 'Completa', livro: 'Tormenta20', pagina: 154 },
    { id: 36, nome: 'Completa', livro: 'Tormenta20', pagina: 154 },
    { id: 37, nome: 'Completa', livro: 'Tormenta20', pagina: 154 },
    { id: 38, nome: 'Completa', livro: 'Tormenta20', pagina: 154 },
    { id: 39, nome: 'Cota de malha', livro: 'Tormenta20', pagina: 154 },
    { id: 40, nome: 'Cota de malha', livro: 'Tormenta20', pagina: 154 },
    { id: 41, nome: 'Cota de malha', livro: 'Tormenta20', pagina: 154 },
    { id: 42, nome: 'Cota de malha', livro: 'Tormenta20', pagina: 154 },
    { id: 43, nome: 'Cota de moedas', livro: 'Heróis de Arton', pagina: 226 },
    { id: 44, nome: 'Cota de moedas', livro: 'Heróis de Arton', pagina: 226 },
    { id: 45, nome: 'Couraça', livro: 'Tormenta20', pagina: 154 },
    { id: 46, nome: 'Couraça', livro: 'Tormenta20', pagina: 154 },
    { id: 47, nome: 'Couraça', livro: 'Tormenta20', pagina: 154 },
    { id: 48, nome: 'Couraça', livro: 'Tormenta20', pagina: 154 },
    { id: 49, nome: 'Couraça', livro: 'Tormenta20', pagina: 154 },
    { id: 50, nome: 'Couraça', livro: 'Tormenta20', pagina: 154 },
    { id: 51, nome: 'Couraça', livro: 'Tormenta20', pagina: 154 },
    { id: 52, nome: 'Couraça', livro: 'Tormenta20', pagina: 154 },
    { id: 53, nome: 'Couraça', livro: 'Tormenta20', pagina: 154 },
    { id: 54, nome: 'Couraça', livro: 'Tormenta20', pagina: 154 },
    { id: 55, nome: 'Couro', livro: 'Tormenta20', pagina: 154 },
    { id: 56, nome: 'Couro', livro: 'Tormenta20', pagina: 154 },
    { id: 57, nome: 'Couro', livro: 'Tormenta20', pagina: 154 },
    { id: 58, nome: 'Couro', livro: 'Tormenta20', pagina: 154 },
    { id: 59, nome: 'Couro batido', livro: 'Tormenta20', pagina: 154 },
    { id: 60, nome: 'Couro batido', livro: 'Tormenta20', pagina: 154 },
    { id: 61, nome: 'Couro batido', livro: 'Tormenta20', pagina: 154 },
    { id: 62, nome: 'Couro batido', livro: 'Tormenta20', pagina: 154 },
    { id: 63, nome: 'Couro batido', livro: 'Tormenta20', pagina: 154 },
    { id: 64, nome: 'Couro batido', livro: 'Tormenta20', pagina: 154 },
    { id: 65, nome: 'Escudo de couro', livro: 'Ameaças de Arton', pagina: 395 },
    { id: 66, nome: 'Escudo de vime', livro: 'Heróis de Arton', pagina: 226 },
    { id: 67, nome: 'Escudo leve', livro: 'Tormenta20', pagina: 154 },
    { id: 68, nome: 'Escudo leve', livro: 'Tormenta20', pagina: 154 },
    { id: 69, nome: 'Escudo leve', livro: 'Tormenta20', pagina: 154 },
    { id: 70, nome: 'Escudo leve', livro: 'Tormenta20', pagina: 154 },
    { id: 71, nome: 'Escudo leve', livro: 'Tormenta20', pagina: 154 },
    { id: 72, nome: 'Escudo leve', livro: 'Tormenta20', pagina: 154 },
    { id: 73, nome: 'Escudo leve', livro: 'Tormenta20', pagina: 154 },
    { id: 74, nome: 'Escudo leve', livro: 'Tormenta20', pagina: 154 },
    { id: 75, nome: 'Escudo pesado', livro: 'Tormenta20', pagina: 154 },
    { id: 76, nome: 'Escudo pesado', livro: 'Tormenta20', pagina: 154 },
    { id: 77, nome: 'Escudo pesado', livro: 'Tormenta20', pagina: 154 },
    { id: 78, nome: 'Escudo pesado', livro: 'Tormenta20', pagina: 154 },
    { id: 79, nome: 'Escudo pesado', livro: 'Tormenta20', pagina: 154 },
    { id: 80, nome: 'Escudo pesado', livro: 'Tormenta20', pagina: 154 },
    { id: 81, nome: 'Escudo pesado', livro: 'Tormenta20', pagina: 154 },
    { id: 82, nome: 'Escudo pesado', livro: 'Tormenta20', pagina: 154 },
    { id: 83, nome: 'Escudo torre', livro: 'Heróis de Arton', pagina: 226 },
    { id: 84, nome: 'Escudo torre', livro: 'Heróis de Arton', pagina: 226 },
    { id: 85, nome: 'Gibão de peles', livro: 'Tormenta20', pagina: 154 },
    { id: 86, nome: 'Gibão de peles', livro: 'Tormenta20', pagina: 154 },
    { id: 87, nome: 'Gibão de peles', livro: 'Tormenta20', pagina: 154 },
    { id: 88, nome: 'Gibão de peles', livro: 'Tormenta20', pagina: 154 },
    { id: 89, nome: 'Loriga segmentada', livro: 'Tormenta20', pagina: 154 },
    { id: 90, nome: 'Loriga segmentada', livro: 'Tormenta20', pagina: 154 },
    { id: 91, nome: 'Loriga segmentada', livro: 'Tormenta20', pagina: 154 },
    { id: 92, nome: 'Loriga segmentada', livro: 'Tormenta20', pagina: 154 },
    { id: 93, nome: 'Meia armadura', livro: 'Tormenta20', pagina: 154 },
    { id: 94, nome: 'Meia armadura', livro: 'Tormenta20', pagina: 154 },
    { id: 95, nome: 'Meia armadura', livro: 'Tormenta20', pagina: 154 },
    { id: 96, nome: 'Meia armadura', livro: 'Tormenta20', pagina: 154 },
    { id: 97, nome: 'Meia armadura', livro: 'Tormenta20', pagina: 154 },
    { id: 98, nome: 'Meia armadura', livro: 'Tormenta20', pagina: 154 },
    { id: 99, nome: 'Sagna', livro: 'Heróis de Arton', pagina: 226 },
    { id: 100, nome: 'Veste de teia de aranha', livro: 'Ameaças de Arton', pagina: 395 },
  ];

  equipamentoEsoterico = [
    { id: 1, nome: 'Afiador solar', livro: 'Deuses de Arton', pagina: 51 },
    { id: 2, nome: 'Afiador solar', livro: 'Deuses de Arton', pagina: 51 },
    { id: 3, nome: 'Afiador solar', livro: 'Deuses de Arton', pagina: 51 },
    { id: 4, nome: 'Ankh solar', livro: 'Ameaças de Arton', pagina: 396 },
    { id: 5, nome: 'Ankh solar', livro: 'Ameaças de Arton', pagina: 396 },
    { id: 6, nome: 'Ankh solar', livro: 'Ameaças de Arton', pagina: 396 },
    { id: 7, nome: 'Báculo da retribuição', livro: 'Deuses de Arton', pagina: 51 },
    { id: 8, nome: 'Báculo da retribuição', livro: 'Deuses de Arton', pagina: 51 },
    { id: 9, nome: 'Báculo da retribuição', livro: 'Deuses de Arton', pagina: 51 },
    { id: 10, nome: 'Báculo da retribuição', livro: 'Deuses de Arton', pagina: 51 },
    { id: 11, nome: 'Bolsa de pó', livro: 'Tormenta20', pagina: 159 },
    { id: 12, nome: 'Bolsa de pó', livro: 'Tormenta20', pagina: 159 },
    { id: 13, nome: 'Bolsa de pó', livro: 'Tormenta20', pagina: 159 },
    { id: 14, nome: 'Bolsa de pó', livro: 'Tormenta20', pagina: 159 },
    { id: 15, nome: 'Cajado arcano', livro: 'Tormenta20', pagina: 160 },
    { id: 16, nome: 'Cajado arcano', livro: 'Tormenta20', pagina: 160 },
    { id: 17, nome: 'Cajado arcano', livro: 'Tormenta20', pagina: 160 },
    { id: 18, nome: 'Cajado arcano', livro: 'Tormenta20', pagina: 160 },
    { id: 19, nome: 'Cetro elemental', livro: 'Tormenta20', pagina: 160 },
    { id: 20, nome: 'Cetro elemental', livro: 'Tormenta20', pagina: 160 },
    { id: 21, nome: 'Cetro elemental', livro: 'Tormenta20', pagina: 160 },
    { id: 22, nome: 'Cetro elemental', livro: 'Tormenta20', pagina: 160 },
    { id: 23, nome: 'Compasso mistico', livro: 'Heróis de Arton', pagina: 234 },
    { id: 24, nome: 'Compasso mistico', livro: 'Heróis de Arton', pagina: 234 },
    { id: 25, nome: 'Compasso mistico', livro: 'Heróis de Arton', pagina: 234 },
    { id: 26, nome: 'Compasso mistico', livro: 'Heróis de Arton', pagina: 234 },
    { id: 27, nome: 'Contas de oração', livro: 'Deuses de Arton', pagina: 51 },
    { id: 28, nome: 'Contas de oração', livro: 'Deuses de Arton', pagina: 51 },
    { id: 29, nome: 'Contas de oração', livro: 'Deuses de Arton', pagina: 51 },
    { id: 30, nome: 'Contas de oração', livro: 'Deuses de Arton', pagina: 51 },
    { id: 31, nome: 'Costela de lich', livro: 'Tormenta20', pagina: 160 },
    { id: 32, nome: 'Costela de lich', livro: 'Tormenta20', pagina: 160 },
    { id: 33, nome: 'Costela de lich', livro: 'Tormenta20', pagina: 160 },
    { id: 34, nome: 'Costela de lich', livro: 'Tormenta20', pagina: 160 },
    { id: 35, nome: 'Dedo de ente', livro: 'Tormenta20', pagina: 160 },
    { id: 36, nome: 'Dedo de ente', livro: 'Tormenta20', pagina: 160 },
    { id: 37, nome: 'Dedo de ente', livro: 'Tormenta20', pagina: 160 },
    { id: 38, nome: 'Dedo de ente', livro: 'Tormenta20', pagina: 160 },
    { id: 39, nome: 'Estola', livro: 'Deuses de Arton', pagina: 51 },
    { id: 40, nome: 'Estola', livro: 'Deuses de Arton', pagina: 51 },
    { id: 41, nome: 'Estola', livro: 'Deuses de Arton', pagina: 51 },
    { id: 42, nome: 'Estola', livro: 'Deuses de Arton', pagina: 51 },
    { id: 43, nome: 'Flauta convocadora', livro: 'Heróis de Arton', pagina: 234 },
    { id: 44, nome: 'Flauta convocadora', livro: 'Heróis de Arton', pagina: 234 },
    { id: 45, nome: 'Flauta convocadora', livro: 'Heróis de Arton', pagina: 234 },
    { id: 46, nome: 'Flauta convocadora', livro: 'Heróis de Arton', pagina: 234 },
    { id: 47, nome: 'Frasco purificador', livro: 'Deuses de Arton', pagina: 51 },
    { id: 48, nome: 'Frasco purificador', livro: 'Deuses de Arton', pagina: 51 },
    { id: 49, nome: 'Frasco purificador', livro: 'Deuses de Arton', pagina: 51 },
    { id: 50, nome: 'Frasco purificador', livro: 'Deuses de Arton', pagina: 51 },
    { id: 51, nome: 'Luva de ferro', livro: 'Tormenta20', pagina: 160 },
    { id: 52, nome: 'Luva de ferro', livro: 'Tormenta20', pagina: 160 },
    { id: 53, nome: 'Luva de ferro', livro: 'Tormenta20', pagina: 160 },
    { id: 54, nome: 'Luva de ferro', livro: 'Tormenta20', pagina: 160 },
    { id: 55, nome: 'Mandala onírica', livro: 'Heróis de Arton', pagina: 234 },
    { id: 56, nome: 'Mandala onírica', livro: 'Heróis de Arton', pagina: 234 },
    { id: 57, nome: 'Mandala onírica', livro: 'Heróis de Arton', pagina: 234 },
    { id: 58, nome: 'Mandala onírica', livro: 'Heróis de Arton', pagina: 234 },
    { id: 59, nome: 'Medalhão afiado', livro: 'Deuses de Arton', pagina: 51 },
    { id: 60, nome: 'Medalhão afiado', livro: 'Deuses de Arton', pagina: 51 },
    { id: 61, nome: 'Medalhão afiado', livro: 'Deuses de Arton', pagina: 51 },
    { id: 62, nome: 'Medalhão afiado', livro: 'Deuses de Arton', pagina: 51 },
    { id: 63, nome: 'Medalhão de prata', livro: 'Tormenta20', pagina: 160 },
    { id: 64, nome: 'Medalhão de prata', livro: 'Tormenta20', pagina: 160 },
    { id: 65, nome: 'Medalhão de prata', livro: 'Tormenta20', pagina: 160 },
    { id: 66, nome: 'Medalhão de prata', livro: 'Tormenta20', pagina: 160 },
    { id: 67, nome: 'Orbe cristalino', livro: 'Tormenta20', pagina: 160 },
    { id: 68, nome: 'Orbe cristalino', livro: 'Tormenta20', pagina: 160 },
    { id: 69, nome: 'Orbe cristalino', livro: 'Tormenta20', pagina: 160 },
    { id: 70, nome: 'Orbe cristalino', livro: 'Tormenta20', pagina: 160 },
    { id: 71, nome: 'Ostensório santificado', livro: 'Deuses de Arton', pagina: 51 },
    { id: 72, nome: 'Ostensório santificado', livro: 'Deuses de Arton', pagina: 51 },
    { id: 73, nome: 'Ostensório santificado', livro: 'Deuses de Arton', pagina: 51 },
    { id: 74, nome: 'Ostensório santificado', livro: 'Deuses de Arton', pagina: 51 },
    { id: 75, nome: 'Rede de almas', livro: 'Deuses de Arton', pagina: 52 },
    { id: 76, nome: 'Rede de almas', livro: 'Deuses de Arton', pagina: 52 },
    { id: 77, nome: 'Rede de almas', livro: 'Deuses de Arton', pagina: 52 },
    { id: 78, nome: 'Rede de almas', livro: 'Deuses de Arton', pagina: 52 },
    { id: 79, nome: 'Tomo de guerra', livro: 'Ameaças de Arton', pagina: 396 },
    { id: 80, nome: 'Tomo de guerra', livro: 'Ameaças de Arton', pagina: 396 },
    { id: 81, nome: 'Tomo de guerra', livro: 'Ameaças de Arton', pagina: 396 },
    { id: 82, nome: 'Tomo do rancor', livro: 'Ameaças de Arton', pagina: 396 },
    { id: 83, nome: 'Tomo do rancor', livro: 'Ameaças de Arton', pagina: 396 },
    { id: 84, nome: 'Tomo do rancor', livro: 'Ameaças de Arton', pagina: 396 },
    { id: 85, nome: 'Tomo hermético', livro: 'Tormenta20', pagina: 160 },
    { id: 86, nome: 'Tomo hermético', livro: 'Tormenta20', pagina: 160 },
    { id: 87, nome: 'Tomo hermético', livro: 'Tormenta20', pagina: 160 },
    { id: 88, nome: 'Tomo hermético', livro: 'Tormenta20', pagina: 160 },
    { id: 89, nome: 'Turíbulo ungido', livro: 'Deuses de Arton', pagina: 52 },
    { id: 90, nome: 'Turíbulo ungido', livro: 'Deuses de Arton', pagina: 52 },
    { id: 91, nome: 'Turíbulo ungido', livro: 'Deuses de Arton', pagina: 52 },
    { id: 92, nome: 'Turíbulo ungido', livro: 'Deuses de Arton', pagina: 52 },
    { id: 93, nome: 'Varinha arcana', livro: 'Tormenta20', pagina: 160 },
    { id: 94, nome: 'Varinha arcana', livro: 'Tormenta20', pagina: 160 },
    { id: 95, nome: 'Varinha arcana', livro: 'Tormenta20', pagina: 160 },
    { id: 96, nome: 'Varinha arcana', livro: 'Tormenta20', pagina: 160 },
    { id: 97, nome: 'Varinha armamentista', livro: 'Heróis de Arton', pagina: 234 },
    { id: 98, nome: 'Varinha armamentista', livro: 'Heróis de Arton', pagina: 234 },
    { id: 99, nome: 'Varinha armamentista', livro: 'Heróis de Arton', pagina: 234 },
    { id: 100, nome: 'Varinha armamentista', livro: 'Heróis de Arton', pagina: 234 },
  ];

  melhoriasSuperioresArmas = [
    // [11] - MELHORIAS SUPERIORES ARMAS
    { id: 1, nome: 'Atroz*', livro: 'Tormenta20', pagina: 164 },
    { id: 2, nome: 'Atroz*', livro: 'Tormenta20', pagina: 164 },
    { id: 3, nome: 'Atroz*', livro: 'Tormenta20', pagina: 164 },
    { id: 4, nome: 'Atroz*', livro: 'Tormenta20', pagina: 164 },
    { id: 5, nome: 'Atroz*', livro: 'Tormenta20', pagina: 164 },
    { id: 6, nome: 'Atroz*', livro: 'Tormenta20', pagina: 164 },
    { id: 7, nome: 'Atroz*', livro: 'Tormenta20', pagina: 164 },
    { id: 8, nome: 'Atroz*', livro: 'Tormenta20', pagina: 164 },
    { id: 9, nome: 'Atroz*', livro: 'Tormenta20', pagina: 164 },
    { id: 10, nome: 'Atroz*', livro: 'Tormenta20', pagina: 164 },
    { id: 11, nome: 'Banhada a ouro', livro: 'Tormenta20', pagina: 164 },
    { id: 12, nome: 'Banhada a ouro', livro: 'Tormenta20', pagina: 164 },
    { id: 13, nome: 'Certeira', livro: 'Tormenta20', pagina: 164 },
    { id: 14, nome: 'Certeira', livro: 'Tormenta20', pagina: 164 },
    { id: 15, nome: 'Certeira', livro: 'Tormenta20', pagina: 164 },
    { id: 16, nome: 'Certeira', livro: 'Tormenta20', pagina: 164 },
    { id: 17, nome: 'Certeira', livro: 'Tormenta20', pagina: 164 },
    { id: 18, nome: 'Certeira', livro: 'Tormenta20', pagina: 164 },
    { id: 19, nome: 'Certeira', livro: 'Tormenta20', pagina: 164 },
    { id: 20, nome: 'Certeira', livro: 'Tormenta20', pagina: 164 },
    { id: 21, nome: 'Conduíte', livro: 'Deuses de Arton', pagina: 54 },
    { id: 22, nome: 'Cravejada de gemas', livro: 'Tormenta20', pagina: 164 },
    { id: 23, nome: 'Cravejada de gemas', livro: 'Tormenta20', pagina: 164 },
    { id: 24, nome: 'Cruel', livro: 'Tormenta20', pagina: 164 },
    { id: 25, nome: 'Cruel', livro: 'Tormenta20', pagina: 164 },
    { id: 26, nome: 'Cruel', livro: 'Tormenta20', pagina: 164 },
    { id: 27, nome: 'Cruel', livro: 'Tormenta20', pagina: 164 },
    { id: 28, nome: 'Cruel', livro: 'Tormenta20', pagina: 164 },
    { id: 29, nome: 'Cruel', livro: 'Tormenta20', pagina: 164 },
    { id: 30, nome: 'Cruel', livro: 'Tormenta20', pagina: 164 },
    { id: 31, nome: 'Cruel', livro: 'Tormenta20', pagina: 164 },
    { id: 32, nome: 'Discreta', livro: 'Tormenta20', pagina: 164 },
    { id: 33, nome: 'Discreta', livro: 'Tormenta20', pagina: 164 },
    { id: 34, nome: 'Equilibrada', livro: 'Tormenta20', pagina: 165 },
    { id: 35, nome: 'Equilibrada', livro: 'Tormenta20', pagina: 165 },
    { id: 36, nome: 'Equilibrada', livro: 'Tormenta20', pagina: 165 },
    { id: 37, nome: 'Equilibrada', livro: 'Tormenta20', pagina: 165 },
    { id: 38, nome: 'Equilibrada', livro: 'Tormenta20', pagina: 165 },
    { id: 39, nome: 'Farpada', livro: 'Heróis de Arton', pagina: 239 },
    { id: 40, nome: 'Farpada', livro: 'Heróis de Arton', pagina: 239 },
    { id: 41, nome: 'Farpada', livro: 'Heróis de Arton', pagina: 239 },
    { id: 42, nome: 'Farpada', livro: 'Heróis de Arton', pagina: 239 },
    { id: 43, nome: 'Guarda', livro: 'Heróis de Arton', pagina: 239 },
    { id: 44, nome: 'Guarda', livro: 'Heróis de Arton', pagina: 239 },
    { id: 45, nome: 'Harmonizada', livro: 'Tormenta20', pagina: 165 },
    { id: 46, nome: 'Harmonizada', livro: 'Tormenta20', pagina: 165 },
    { id: 47, nome: 'Harmonizada', livro: 'Tormenta20', pagina: 165 },
    { id: 48, nome: 'Harmonizada', livro: 'Tormenta20', pagina: 165 },
    { id: 49, nome: 'Incendiária', livro: 'Heróis de Arton', pagina: 239 },
    { id: 50, nome: 'Injeção alquímica', livro: 'Tormenta20', pagina: 165 },
    { id: 51, nome: 'Injeção alquímica', livro: 'Tormenta20', pagina: 165 },
    { id: 52, nome: 'Injeção alquímica', livro: 'Tormenta20', pagina: 165 },
    { id: 53, nome: 'Injeção alquímica', livro: 'Tormenta20', pagina: 165 },
    { id: 54, nome: 'Macabra', livro: 'Tormenta20', pagina: 165 },
    { id: 55, nome: 'Macabra', livro: 'Tormenta20', pagina: 165 },
    { id: 56, nome: 'Maciça', livro: 'Tormenta20', pagina: 165 },
    { id: 57, nome: 'Maciça', livro: 'Tormenta20', pagina: 165 },
    { id: 58, nome: 'Maciça', livro: 'Tormenta20', pagina: 165 },
    { id: 59, nome: 'Maciça', livro: 'Tormenta20', pagina: 165 },
    { id: 60, nome: 'Maciça', livro: 'Tormenta20', pagina: 165 },
    { id: 61, nome: 'Maciça', livro: 'Tormenta20', pagina: 165 },
    { id: 62, nome: 'Maciça', livro: 'Tormenta20', pagina: 165 },
    { id: 63, nome: 'Maciça', livro: 'Tormenta20', pagina: 165 },
    { id: 64, nome: 'Maciça', livro: 'Tormenta20', pagina: 165 },
    { id: 65, nome: 'Maciça', livro: 'Tormenta20', pagina: 165 },
    { id: 66, nome: 'Material especial', livro: 'Tormenta20', pagina: 165 },
    { id: 67, nome: 'Material especial', livro: 'Tormenta20', pagina: 165 },
    { id: 68, nome: 'Material especial', livro: 'Tormenta20', pagina: 165 },
    { id: 69, nome: 'Material especial', livro: 'Tormenta20', pagina: 165 },
    { id: 70, nome: 'Material especial', livro: 'Tormenta20', pagina: 165 },
    { id: 71, nome: 'Material especial', livro: 'Tormenta20', pagina: 165 },
    { id: 72, nome: 'Material especial', livro: 'Tormenta20', pagina: 165 },
    { id: 73, nome: 'Material especial', livro: 'Tormenta20', pagina: 165 },
    { id: 74, nome: 'Material especial', livro: 'Tormenta20', pagina: 165 },
    { id: 75, nome: 'Material especial', livro: 'Tormenta20', pagina: 165 },
    { id: 76, nome: 'Mira telescópica', livro: 'Tormenta20', pagina: 166 },
    { id: 77, nome: 'Mira telescópica', livro: 'Tormenta20', pagina: 166 },
    { id: 78, nome: 'Mira telescópica', livro: 'Tormenta20', pagina: 166 },
    { id: 79, nome: 'Mira telescópica', livro: 'Tormenta20', pagina: 166 },
    { id: 80, nome: 'Precisa', livro: 'Tormenta20', pagina: 166 },
    { id: 81, nome: 'Precisa', livro: 'Tormenta20', pagina: 166 },
    { id: 82, nome: 'Precisa', livro: 'Tormenta20', pagina: 166 },
    { id: 83, nome: 'Precisa', livro: 'Tormenta20', pagina: 166 },
    { id: 84, nome: 'Precisa', livro: 'Tormenta20', pagina: 166 },
    { id: 85, nome: 'Precisa', livro: 'Tormenta20', pagina: 166 },
    { id: 86, nome: 'Precisa', livro: 'Tormenta20', pagina: 166 },
    { id: 87, nome: 'Precisa', livro: 'Tormenta20', pagina: 166 },
    { id: 88, nome: 'Pressurizada', livro: 'Heróis de Arton', pagina: 240 },
    { id: 89, nome: 'Pressurizada', livro: 'Heróis de Arton', pagina: 240 },
    { id: 90, nome: 'Pungente*', livro: 'Tormenta20', pagina: 166 },
    { id: 91, nome: 'Pungente*', livro: 'Tormenta20', pagina: 166 },
    { id: 92, nome: 'Pungente*', livro: 'Tormenta20', pagina: 166 },
    { id: 93, nome: 'Pungente*', livro: 'Tormenta20', pagina: 166 },
    { id: 94, nome: 'Pungente*', livro: 'Tormenta20', pagina: 166 },
    { id: 95, nome: 'Pungente*', livro: 'Tormenta20', pagina: 166 },
    { id: 96, nome: 'Pungente*', livro: 'Tormenta20', pagina: 166 },
    { id: 97, nome: 'Pungente*', livro: 'Tormenta20', pagina: 166 },
    { id: 98, nome: 'Pungente*', livro: 'Tormenta20', pagina: 166 },
    { id: 99, nome: 'Pungente*', livro: 'Tormenta20', pagina: 166 },
    { id: 100, nome: 'Usada', livro: 'Heróis de Arton', pagina: 240 },
  ];
  melhoriasSuperioresArmaduras = [
    // [12] - MELHORIAS SUPERIORES ARMADURAS
    { id: 1, nome: 'Ajustada', livro: 'Tormenta20', pagina: 164 },
    { id: 2, nome: 'Ajustada', livro: 'Tormenta20', pagina: 164 },
    { id: 3, nome: 'Ajustada', livro: 'Tormenta20', pagina: 164 },
    { id: 4, nome: 'Ajustada', livro: 'Tormenta20', pagina: 164 },
    { id: 5, nome: 'Ajustada', livro: 'Tormenta20', pagina: 164 },
    { id: 6, nome: 'Ajustada', livro: 'Tormenta20', pagina: 164 },
    { id: 7, nome: 'Ajustada', livro: 'Tormenta20', pagina: 164 },
    { id: 8, nome: 'Ajustada', livro: 'Tormenta20', pagina: 164 },
    { id: 9, nome: 'Ajustada', livro: 'Tormenta20', pagina: 164 },
    { id: 10, nome: 'Ajustada', livro: 'Tormenta20', pagina: 164 },
    { id: 11, nome: 'Balístico', livro: 'Heróis de Arton', pagina: 239 },
    { id: 12, nome: 'Balístico', livro: 'Heróis de Arton', pagina: 239 },
    { id: 13, nome: 'Balístico', livro: 'Heróis de Arton', pagina: 239 },
    { id: 14, nome: 'Balístico', livro: 'Heróis de Arton', pagina: 239 },
    { id: 15, nome: 'Banhada a ouro', livro: 'Tormenta20', pagina: 164 },
    { id: 16, nome: 'Banhada a ouro', livro: 'Tormenta20', pagina: 164 },
    { id: 17, nome: 'Banhada a ouro', livro: 'Tormenta20', pagina: 164 },
    { id: 18, nome: 'Banhada a ouro', livro: 'Tormenta20', pagina: 164 },
    { id: 19, nome: 'Cravejada de gemas', livro: 'Tormenta20', pagina: 164 },
    { id: 20, nome: 'Cravejada de gemas', livro: 'Tormenta20', pagina: 164 },
    { id: 21, nome: 'Cravejada de gemas', livro: 'Tormenta20', pagina: 164 },
    { id: 22, nome: 'Cravejada de gemas', livro: 'Tormenta20', pagina: 164 },
    { id: 23, nome: 'Delicada', livro: 'Tormenta20', pagina: 164 },
    { id: 24, nome: 'Delicada', livro: 'Tormenta20', pagina: 164 },
    { id: 25, nome: 'Delicada', livro: 'Tormenta20', pagina: 164 },
    { id: 26, nome: 'Delicada', livro: 'Tormenta20', pagina: 164 },
    { id: 27, nome: 'Delicada', livro: 'Tormenta20', pagina: 164 },
    { id: 28, nome: 'Deslumbrante*', livro: 'Heróis de Arton', pagina: 239 },
    { id: 29, nome: 'Deslumbrante*', livro: 'Heróis de Arton', pagina: 239 },
    { id: 30, nome: 'Diligente', livro: 'Deuses de Arton', pagina: 54 },
    { id: 31, nome: 'Diligente', livro: 'Deuses de Arton', pagina: 54 },
    { id: 32, nome: 'Discreta', livro: 'Tormenta20', pagina: 164 },
    { id: 33, nome: 'Discreta', livro: 'Tormenta20', pagina: 164 },
    { id: 34, nome: 'Discreta', livro: 'Tormenta20', pagina: 164 },
    { id: 35, nome: 'Discreta', livro: 'Tormenta20', pagina: 164 },
    { id: 36, nome: 'Espinhos', livro: 'Tormenta20', pagina: 165 },
    { id: 37, nome: 'Espinhos', livro: 'Tormenta20', pagina: 165 },
    { id: 38, nome: 'Espinhos', livro: 'Tormenta20', pagina: 165 },
    { id: 39, nome: 'Espinhos', livro: 'Tormenta20', pagina: 165 },
    { id: 40, nome: 'Injetora', livro: 'Heróis de Arton', pagina: 240 },
    { id: 41, nome: 'Injetora', livro: 'Heróis de Arton', pagina: 240 },
    { id: 42, nome: 'Injetora', livro: 'Heróis de Arton', pagina: 240 },
    { id: 43, nome: 'Injetora', livro: 'Heróis de Arton', pagina: 240 },
    { id: 44, nome: 'Inscrito', livro: 'Deuses de Arton', pagina: 54 },
    { id: 45, nome: 'Inscrito', livro: 'Deuses de Arton', pagina: 54 },
    { id: 46, nome: 'Inscrito', livro: 'Deuses de Arton', pagina: 54 },
    { id: 47, nome: 'Inscrito', livro: 'Deuses de Arton', pagina: 54 },
    { id: 48, nome: 'Macabra', livro: 'Tormenta20', pagina: 165 },
    { id: 49, nome: 'Macabra', livro: 'Tormenta20', pagina: 165 },
    { id: 50, nome: 'Material especial', livro: 'Tormenta20', pagina: 165 },
    { id: 51, nome: 'Material especial', livro: 'Tormenta20', pagina: 165 },
    { id: 52, nome: 'Material especial', livro: 'Tormenta20', pagina: 165 },
    { id: 53, nome: 'Material especial', livro: 'Tormenta20', pagina: 165 },
    { id: 54, nome: 'Material especial', livro: 'Tormenta20', pagina: 165 },
    { id: 55, nome: 'Material especial', livro: 'Tormenta20', pagina: 165 },
    { id: 56, nome: 'Material especial', livro: 'Tormenta20', pagina: 165 },
    { id: 57, nome: 'Material especial', livro: 'Tormenta20', pagina: 165 },
    { id: 58, nome: 'Material especial', livro: 'Tormenta20', pagina: 165 },
    { id: 59, nome: 'Material especial', livro: 'Tormenta20', pagina: 165 },
    { id: 60, nome: 'Polida', livro: 'Tormenta20', pagina: 166 },
    { id: 61, nome: 'Polida', livro: 'Tormenta20', pagina: 166 },
    { id: 62, nome: 'Polida', livro: 'Tormenta20', pagina: 166 },
    { id: 63, nome: 'Polida', livro: 'Tormenta20', pagina: 166 },
    { id: 64, nome: 'Polida', livro: 'Tormenta20', pagina: 166 },
    { id: 65, nome: 'Reforçada', livro: 'Tormenta20', pagina: 166 },
    { id: 66, nome: 'Reforçada', livro: 'Tormenta20', pagina: 166 },
    { id: 67, nome: 'Reforçada', livro: 'Tormenta20', pagina: 166 },
    { id: 68, nome: 'Reforçada', livro: 'Tormenta20', pagina: 166 },
    { id: 69, nome: 'Reforçada', livro: 'Tormenta20', pagina: 166 },
    { id: 70, nome: 'Reforçada', livro: 'Tormenta20', pagina: 166 },
    { id: 71, nome: 'Reforçada', livro: 'Tormenta20', pagina: 166 },
    { id: 72, nome: 'Reforçada', livro: 'Tormenta20', pagina: 166 },
    { id: 73, nome: 'Reforçada', livro: 'Tormenta20', pagina: 166 },
    { id: 74, nome: 'Reforçada', livro: 'Tormenta20', pagina: 166 },
    { id: 75, nome: 'Reforçada', livro: 'Tormenta20', pagina: 166 },
    { id: 76, nome: 'Reforçada', livro: 'Tormenta20', pagina: 166 },
    { id: 77, nome: 'Reforçada', livro: 'Tormenta20', pagina: 166 },
    { id: 78, nome: 'Reforçada', livro: 'Tormenta20', pagina: 166 },
    { id: 79, nome: 'Reforçada', livro: 'Tormenta20', pagina: 166 },
    { id: 80, nome: 'Reforçada', livro: 'Tormenta20', pagina: 166 },
    { id: 81, nome: 'Reforçada', livro: 'Tormenta20', pagina: 166 },
    { id: 82, nome: 'Reforçada', livro: 'Tormenta20', pagina: 166 },
    { id: 83, nome: 'Reforçada', livro: 'Tormenta20', pagina: 166 },
    { id: 84, nome: 'Reforçada', livro: 'Tormenta20', pagina: 166 },
    { id: 85, nome: 'Selada', livro: 'Tormenta20', pagina: 166 },
    { id: 86, nome: 'Selada', livro: 'Tormenta20', pagina: 166 },
    { id: 87, nome: 'Selada', livro: 'Tormenta20', pagina: 166 },
    { id: 88, nome: 'Selada', livro: 'Tormenta20', pagina: 166 },
    { id: 89, nome: 'Selada', livro: 'Tormenta20', pagina: 166 },
    { id: 90, nome: 'Selada', livro: 'Tormenta20', pagina: 166 },
    { id: 91, nome: 'Selada', livro: 'Tormenta20', pagina: 166 },
    { id: 92, nome: 'Selada', livro: 'Tormenta20', pagina: 166 },
    { id: 93, nome: 'Selada', livro: 'Tormenta20', pagina: 166 },
    { id: 94, nome: 'Selada', livro: 'Tormenta20', pagina: 166 },
    { id: 95, nome: 'Selada', livro: 'Tormenta20', pagina: 166 },
    { id: 96, nome: 'Sob medida*', livro: 'Tormenta20', pagina: 166 },
    { id: 97, nome: 'Sob medida*', livro: 'Tormenta20', pagina: 166 },
    { id: 98, nome: 'Sob medida*', livro: 'Tormenta20', pagina: 166 },
    { id: 99, nome: 'Sob medida*', livro: 'Tormenta20', pagina: 166 },
    { id: 100, nome: 'Sob medida*', livro: 'Tormenta20', pagina: 166 },
  ];
  melhoriasSuperioresEsotericos = [
    // [13] - MELHORIAS SUPERIORES ESOTÉRICOS
    { id: 1, nome: 'Banhado a ouro', livro: 'Tormenta20', pagina: 164 },
    { id: 2, nome: 'Banhado a ouro', livro: 'Tormenta20', pagina: 164 },
    { id: 3, nome: 'Banhado a ouro', livro: 'Tormenta20', pagina: 164 },
    { id: 4, nome: 'Canalizador', livro: 'Tormenta20', pagina: 164 },
    { id: 5, nome: 'Canalizador', livro: 'Tormenta20', pagina: 164 },
    { id: 6, nome: 'Canalizador', livro: 'Tormenta20', pagina: 164 },
    { id: 7, nome: 'Canalizador', livro: 'Tormenta20', pagina: 164 },
    { id: 8, nome: 'Canalizador', livro: 'Tormenta20', pagina: 164 },
    { id: 9, nome: 'Canalizador', livro: 'Tormenta20', pagina: 164 },
    { id: 10, nome: 'Canalizador', livro: 'Tormenta20', pagina: 164 },
    { id: 11, nome: 'Canalizador', livro: 'Tormenta20', pagina: 164 },
    { id: 12, nome: 'Canalizador', livro: 'Tormenta20', pagina: 164 },
    { id: 13, nome: 'Canalizador', livro: 'Tormenta20', pagina: 164 },
    { id: 14, nome: 'Canalizador', livro: 'Tormenta20', pagina: 164 },
    { id: 15, nome: 'Canalizador', livro: 'Tormenta20', pagina: 164 },
    { id: 16, nome: 'Canalizador', livro: 'Tormenta20', pagina: 164 },
    { id: 17, nome: 'Canalizador', livro: 'Tormenta20', pagina: 164 },
    { id: 18, nome: 'Canalizador', livro: 'Tormenta20', pagina: 164 },
    { id: 19, nome: 'Canônico', livro: 'Deuses de Arton', pagina: 54 },
    { id: 20, nome: 'Canônico', livro: 'Deuses de Arton', pagina: 54 },
    { id: 21, nome: 'Canônico', livro: 'Deuses de Arton', pagina: 54 },
    { id: 22, nome: 'Cravejado de gemas', livro: 'Tormenta20', pagina: 164 },
    { id: 23, nome: 'Cravejado de gemas', livro: 'Tormenta20', pagina: 164 },
    { id: 24, nome: 'Cravejado de gemas', livro: 'Tormenta20', pagina: 164 },
    { id: 25, nome: 'Discreto', livro: 'Tormenta20', pagina: 164 },
    { id: 26, nome: 'Discreto', livro: 'Tormenta20', pagina: 164 },
    { id: 27, nome: 'Discreto', livro: 'Tormenta20', pagina: 164 },
    { id: 28, nome: 'Discreto', livro: 'Tormenta20', pagina: 164 },
    { id: 29, nome: 'Energético', livro: 'Tormenta20', pagina: 165 },
    { id: 30, nome: 'Energético', livro: 'Tormenta20', pagina: 165 },
    { id: 31, nome: 'Energético', livro: 'Tormenta20', pagina: 165 },
    { id: 32, nome: 'Energético', livro: 'Tormenta20', pagina: 165 },
    { id: 33, nome: 'Energético', livro: 'Tormenta20', pagina: 165 },
    { id: 34, nome: 'Energético', livro: 'Tormenta20', pagina: 165 },
    { id: 35, nome: 'Energético', livro: 'Tormenta20', pagina: 165 },
    { id: 36, nome: 'Energético', livro: 'Tormenta20', pagina: 165 },
    { id: 37, nome: 'Energético', livro: 'Tormenta20', pagina: 165 },
    { id: 38, nome: 'Energético', livro: 'Tormenta20', pagina: 165 },
    { id: 39, nome: 'Energético', livro: 'Tormenta20', pagina: 165 },
    { id: 40, nome: 'Energético', livro: 'Tormenta20', pagina: 165 },
    { id: 41, nome: 'Energético', livro: 'Tormenta20', pagina: 165 },
    { id: 42, nome: 'Energético', livro: 'Tormenta20', pagina: 165 },
    { id: 43, nome: 'Energético', livro: 'Tormenta20', pagina: 165 },
    { id: 44, nome: 'Harmonizado', livro: 'Tormenta20', pagina: 165 },
    { id: 45, nome: 'Harmonizado', livro: 'Tormenta20', pagina: 165 },
    { id: 46, nome: 'Harmonizado', livro: 'Tormenta20', pagina: 165 },
    { id: 47, nome: 'Harmonizado', livro: 'Tormenta20', pagina: 165 },
    { id: 48, nome: 'Harmonizado', livro: 'Tormenta20', pagina: 165 },
    { id: 49, nome: 'Harmonizado', livro: 'Tormenta20', pagina: 165 },
    { id: 50, nome: 'Harmonizado', livro: 'Tormenta20', pagina: 165 },
    { id: 51, nome: 'Harmonizado', livro: 'Tormenta20', pagina: 165 },
    { id: 52, nome: 'Harmonizado', livro: 'Tormenta20', pagina: 165 },
    { id: 53, nome: 'Harmonizado', livro: 'Tormenta20', pagina: 165 },
    { id: 54, nome: 'Harmonizado', livro: 'Tormenta20', pagina: 165 },
    { id: 55, nome: 'Harmonizado', livro: 'Tormenta20', pagina: 165 },
    { id: 56, nome: 'Harmonizado', livro: 'Tormenta20', pagina: 165 },
    { id: 57, nome: 'Harmonizado', livro: 'Tormenta20', pagina: 165 },
    { id: 58, nome: 'Harmonizado', livro: 'Tormenta20', pagina: 165 },
    { id: 59, nome: 'Macabro', livro: 'Tormenta20', pagina: 165 },
    { id: 60, nome: 'Macabro', livro: 'Tormenta20', pagina: 165 },
    { id: 61, nome: 'Macabro', livro: 'Tormenta20', pagina: 165 },
    { id: 62, nome: 'Material especial', livro: 'Tormenta20', pagina: 165 },
    { id: 63, nome: 'Material especial', livro: 'Tormenta20', pagina: 165 },
    { id: 64, nome: 'Material especial', livro: 'Tormenta20', pagina: 165 },
    { id: 65, nome: 'Material especial', livro: 'Tormenta20', pagina: 165 },
    { id: 66, nome: 'Material especial', livro: 'Tormenta20', pagina: 165 },
    { id: 67, nome: 'Material especial', livro: 'Tormenta20', pagina: 165 },
    { id: 68, nome: 'Material especial', livro: 'Tormenta20', pagina: 165 },
    { id: 69, nome: 'Material especial', livro: 'Tormenta20', pagina: 165 },
    { id: 70, nome: 'Material especial', livro: 'Tormenta20', pagina: 165 },
    { id: 71, nome: 'Poderoso', livro: 'Tormenta20', pagina: 166 },
    { id: 72, nome: 'Poderoso', livro: 'Tormenta20', pagina: 166 },
    { id: 73, nome: 'Poderoso', livro: 'Tormenta20', pagina: 166 },
    { id: 74, nome: 'Poderoso', livro: 'Tormenta20', pagina: 166 },
    { id: 75, nome: 'Poderoso', livro: 'Tormenta20', pagina: 166 },
    { id: 76, nome: 'Poderoso', livro: 'Tormenta20', pagina: 166 },
    { id: 77, nome: 'Poderoso', livro: 'Tormenta20', pagina: 166 },
    { id: 78, nome: 'Poderoso', livro: 'Tormenta20', pagina: 166 },
    { id: 79, nome: 'Poderoso', livro: 'Tormenta20', pagina: 166 },
    { id: 80, nome: 'Poderoso', livro: 'Tormenta20', pagina: 166 },
    { id: 81, nome: 'Potencializador*', livro: 'Heróis de Arton', pagina: 240 },
    { id: 82, nome: 'Potencializador*', livro: 'Heróis de Arton', pagina: 240 },
    { id: 83, nome: 'Potencializador*', livro: 'Heróis de Arton', pagina: 240 },
    { id: 84, nome: 'Potencializador*', livro: 'Heróis de Arton', pagina: 240 },
    { id: 85, nome: 'Potencializador*', livro: 'Heróis de Arton', pagina: 240 },
    { id: 86, nome: 'Potencializador*', livro: 'Heróis de Arton', pagina: 240 },
    { id: 87, nome: 'Potencializador*', livro: 'Heróis de Arton', pagina: 240 },
    { id: 88, nome: 'Potencializador*', livro: 'Heróis de Arton', pagina: 240 },
    { id: 89, nome: 'Potencializador*', livro: 'Heróis de Arton', pagina: 240 },
    { id: 90, nome: 'Potencializador*', livro: 'Heróis de Arton', pagina: 240 },
    { id: 91, nome: 'Vigilante', livro: 'Tormenta20', pagina: 166 },
    { id: 92, nome: 'Vigilante', livro: 'Tormenta20', pagina: 166 },
    { id: 93, nome: 'Vigilante', livro: 'Tormenta20', pagina: 166 },
    { id: 94, nome: 'Vigilante', livro: 'Tormenta20', pagina: 166 },
    { id: 95, nome: 'Vigilante', livro: 'Tormenta20', pagina: 166 },
    { id: 96, nome: 'Vigilante', livro: 'Tormenta20', pagina: 166 },
    { id: 97, nome: 'Vigilante', livro: 'Tormenta20', pagina: 166 },
    { id: 98, nome: 'Vigilante', livro: 'Tormenta20', pagina: 166 },
    { id: 99, nome: 'Vigilante', livro: 'Tormenta20', pagina: 166 },
    { id: 100, nome: 'Vigilante', livro: 'Tormenta20', pagina: 166 },
  ];
  melhoriasSuperioresMaterialEspecial = [
    // [14] - MELHORIAS SUPERIORES MATERIAL ESPECIAL
    { id: 1, nome: 'Aço Rubi', livro: 'Tormenta20', pagina: 166 },
    { id: 2, nome: 'Adamante', livro: 'Tormenta20', pagina: 166 },
    { id: 3, nome: 'Gelo Eterno', livro: 'Tormenta20', pagina: 166 },
    { id: 4, nome: 'Madeira de Tollon', livro: 'Tormenta20', pagina: 166 },
    { id: 5, nome: 'Matéria Vermelha', livro: 'Tormenta20', pagina: 166 },
    { id: 6, nome: 'Mitral', livro: 'Tormenta20', pagina: 166 },
  ];
}
