import { Injectable } from '@angular/core';
import { TreasureGenerator } from './treasure-generator';
import { GeneratedTreasure, tabelaTesouroItens, TreasureContext } from '../model/treasure';

@Injectable({ providedIn: 'root' })
export class MagicEquipmentTreasureGenerator implements TreasureGenerator {
  constructor() {}

  public generate(ctx: TreasureContext): GeneratedTreasure {
    let nivel = String(ctx.level).trim();
    const tabelaItemNivel = tabelaTesouroItens.filter((item: any) => item.nd === Number(nivel));
    const linhaItemNivel: any = tabelaItemNivel.find((item: any) => ctx.random! >= item.min && ctx.random! <= item.max);

    let tesouro: any[] = [];
    let gt: { items: any; return: string; notes: string; report: string };

    this.gerarArmaArmaduraEsotericoOuAcessorio(tesouro, linhaItemNivel);

    if (linhaItemNivel.valor.includes('2D')) {
      this.gerarArmaArmaduraEsotericoOuAcessorio(tesouro, linhaItemNivel);
    }

    gt = {
      items: linhaItemNivel,
      return: linhaItemNivel.nome,
      notes: linhaItemNivel.unidade,
      report: this.gerarRelatorio(ctx.random!, linhaItemNivel, tesouro),
    };

    return gt;
  }

  private gerarArmaArmaduraEsotericoOuAcessorio(tesouro: any[], linhaItemNivel: any) {
    let randomItemMagico = Math.floor(Math.random() * 6) + 1;
    let linhaItemMagico = this.equipamentoMagico.find((item: any) => randomItemMagico === item.id);

    if (linhaItemMagico!.nome === 'arma') {
      tesouro.push(this.gerarItemMagico(linhaItemNivel, this.armaMagica, this.encantoArma));
    } else if (linhaItemMagico!.nome === 'armadura') {
      tesouro.push(this.gerarItemMagico(linhaItemNivel, this.armaduraMagica, this.encantoArmadura));
    } else if (linhaItemMagico!.nome === 'esoterico') {
      tesouro.push(this.gerarItemMagico(linhaItemNivel, this.esotericoMagico, this.encantoEsoterico));
    } else {
      let randomAcessorioMagico = Math.floor(Math.random() * 100) + 1;
      if (linhaItemNivel.valor.includes('menor')) {
        tesouro.push(this.acessorioMenor.find((item: any) => randomAcessorioMagico === item.id));
      } else if (linhaItemNivel.valor.includes('médio')) {
        tesouro.push(this.acessorioMedio.find((item: any) => randomAcessorioMagico === item.id));
      } else if (linhaItemNivel.valor.includes('maior')) {
        tesouro.push(this.acessorioMaior.find((item: any) => randomAcessorioMagico === item.id));
      }
    }
  }

  private gerarItemMagico(linhaItemNivel: any, tabela: any, tabelaEspecifica: any) {
    let randomItemMagico = Math.floor(Math.random() * 100) + 1;
    let linhaItemMagico = tabela.find((item: any) => randomItemMagico === item.id);
    if (!linhaItemMagico.encantos) {
      linhaItemMagico.encantos = [];
    }

    const numero = linhaItemNivel.modificador.includes('menor')
      ? 1
      : linhaItemNivel.modificador.includes('maior')
        ? 3
        : 2;

    for (let i = 1; i <= numero; i++) {
      let randomEncanto = Math.floor(Math.random() * 100) + 1;
      let encanto = tabelaEspecifica.find((item: any) => randomEncanto === item.id);
      linhaItemMagico.encantos.push(encanto);
    }

    return linhaItemMagico;
  }

  private gerarRelatorio(random: number, linha: any, linhaItem: any): string {
    const linhasHtml = linhaItem
      .map((item: any) => `<li>${item.id} - ${item.nome} ${item.encantos ? this.relatorioEncantos(item) : ''}</li>`)
      .join('');

    let labelEquipamento = linha.valor.includes('2D') ? linha.valor + ' (escolha um)' : linha.valor;

    return `
    <label><b>FÓRMULA:</b> ${linha.valor}</label><br />
      <label><b>RESULTADO D100:</b> ${random}</label><br />
      <label><b>${labelEquipamento}:</b></label>
      <ul>
          ${linhasHtml}
      </ul>
      `;
  }

  private relatorioEncantos(item: any) {
    let relatorioEncantos = item.encantos.map((p: any) => p.nome).join(', ');
    return `(${relatorioEncantos})`;
  }

  equipamentoMagico = [
    { id: 1, nome: 'arma' },
    { id: 2, nome: 'arma' },
    { id: 3, nome: 'armadura' },
    { id: 4, nome: 'esoterico' },
    { id: 5, nome: 'acessorio' },
    { id: 6, nome: 'acessorio' },
  ];

  encantoArma = [
    { id: 1, nome: 'Alvorada', livro: 'Heróis de Arton', pagina: 256 },
    { id: 2, nome: 'Ameaçadora', livro: 'Tormenta20', pagina: 335 },
    { id: 3, nome: 'Ameaçadora', livro: 'Tormenta20', pagina: 335 },
    { id: 4, nome: 'Ameaçadora', livro: 'Tormenta20', pagina: 335 },
    { id: 5, nome: 'Ameaçadora', livro: 'Tormenta20', pagina: 335 },
    { id: 6, nome: 'Anátema', livro: 'Heróis de Arton', pagina: 256 },
    { id: 7, nome: 'Anticriatura', livro: 'Tormenta20', pagina: 335 },
    { id: 8, nome: 'Anticriatura', livro: 'Tormenta20', pagina: 335 },
    { id: 9, nome: 'Arremesso', livro: 'Tormenta20', pagina: 335 },
    { id: 10, nome: 'Assassina', livro: 'Tormenta20', pagina: 335 },
    { id: 11, nome: 'Brumosa', livro: 'Heróis de Arton', pagina: 256 },
    { id: 12, nome: 'Caçadora', livro: 'Tormenta20', pagina: 335 },
    { id: 13, nome: 'Cantante', livro: 'Heróis de Arton', pagina: 256 },
    { id: 14, nome: 'Ciclônica', livro: 'Heróis de Arton', pagina: 256 },
    { id: 15, nome: 'Congelante', livro: 'Tormenta20', pagina: 335 },
    { id: 16, nome: 'Congelante', livro: 'Tormenta20', pagina: 335 },
    { id: 17, nome: 'Congelante', livro: 'Tormenta20', pagina: 335 },
    { id: 18, nome: 'Congelante', livro: 'Tormenta20', pagina: 335 },
    { id: 19, nome: 'Conjuradora', livro: 'Tormenta20', pagina: 335 },
    { id: 20, nome: 'Corrosiva', livro: 'Tormenta20', pagina: 335 },
    { id: 21, nome: 'Corrosiva', livro: 'Tormenta20', pagina: 335 },
    { id: 22, nome: 'Corrosiva', livro: 'Tormenta20', pagina: 335 },
    { id: 23, nome: 'Corrosiva', livro: 'Tormenta20', pagina: 335 },
    { id: 24, nome: 'Crescente', livro: 'Heróis de Arton', pagina: 256 },
    { id: 25, nome: 'Crescente', livro: 'Heróis de Arton', pagina: 256 },
    { id: 26, nome: 'Cristalina', livro: 'Heróis de Arton', pagina: 256 },
    { id: 27, nome: 'Cronal*', livro: 'Heróis de Arton', pagina: 256 },
    { id: 28, nome: 'Cuidadora', livro: 'Heróis de Arton', pagina: 256 },
    { id: 29, nome: 'Dançarina', livro: 'Tormenta20', pagina: 335 },
    { id: 30, nome: 'Dançarina', livro: 'Tormenta20', pagina: 335 },
    { id: 31, nome: 'Defensora', livro: 'Tormenta20', pagina: 335 },
    { id: 32, nome: 'Defensora', livro: 'Tormenta20', pagina: 335 },
    { id: 33, nome: 'Destruidora', livro: 'Tormenta20', pagina: 335 },
    { id: 34, nome: 'Dilacerante', livro: 'Tormenta20', pagina: 335 },
    { id: 35, nome: 'Dilacerante', livro: 'Tormenta20', pagina: 335 },
    { id: 36, nome: 'Drenante', livro: 'Tormenta20', pagina: 335 },
    { id: 37, nome: 'Elétrica', livro: 'Tormenta20', pagina: 335 },
    { id: 38, nome: 'Elétrica', livro: 'Tormenta20', pagina: 335 },
    { id: 39, nome: 'Elétrica', livro: 'Tormenta20', pagina: 335 },
    { id: 40, nome: 'Elétrica', livro: 'Tormenta20', pagina: 335 },
    { id: 41, nome: 'Energética*', livro: 'Tormenta20', pagina: 335 },
    { id: 42, nome: 'Espreitadora', livro: 'Heróis de Arton', pagina: 256 },
    { id: 43, nome: 'Espreitadora', livro: 'Heróis de Arton', pagina: 256 },
    { id: 44, nome: 'Excruciante', livro: 'Tormenta20', pagina: 335 },
    { id: 45, nome: 'Excruciante', livro: 'Tormenta20', pagina: 335 },
    { id: 46, nome: 'Flamejante', livro: 'Tormenta20', pagina: 335 },
    { id: 47, nome: 'Flamejante', livro: 'Tormenta20', pagina: 335 },
    { id: 48, nome: 'Flamejante', livro: 'Tormenta20', pagina: 335 },
    { id: 49, nome: 'Flamejante', livro: 'Tormenta20', pagina: 335 },
    { id: 50, nome: 'Formidável', livro: 'Tormenta20', pagina: 336 },
    { id: 51, nome: 'Formidável', livro: 'Tormenta20', pagina: 336 },
    { id: 52, nome: 'Formidável', livro: 'Tormenta20', pagina: 336 },
    { id: 53, nome: 'Formidável', livro: 'Tormenta20', pagina: 336 },
    { id: 54, nome: 'Formidável', livro: 'Tormenta20', pagina: 336 },
    { id: 55, nome: 'Formidável', livro: 'Tormenta20', pagina: 336 },
    { id: 56, nome: 'Formidável', livro: 'Tormenta20', pagina: 336 },
    { id: 57, nome: 'Formidável', livro: 'Tormenta20', pagina: 336 },
    { id: 58, nome: 'Frenética', livro: 'Heróis de Arton', pagina: 256 },
    { id: 59, nome: 'Frenética', livro: 'Heróis de Arton', pagina: 256 },
    { id: 60, nome: 'Gárgula', livro: 'Heróis de Arton', pagina: 256 },
    { id: 61, nome: 'Horrenda', livro: 'Heróis de Arton', pagina: 256 },
    { id: 62, nome: 'Indignada', livro: 'Heróis de Arton', pagina: 256 },
    { id: 63, nome: 'Infestada', livro: 'Heróis de Arton', pagina: 256 },
    { id: 64, nome: 'Lancinante*', livro: 'Tormenta20', pagina: 336 },
    { id: 65, nome: 'Magnífica*', livro: 'Tormenta20', pagina: 336 },
    { id: 66, nome: 'Magnífica*', livro: 'Tormenta20', pagina: 336 },
    { id: 67, nome: 'Magnífica*', livro: 'Tormenta20', pagina: 336 },
    { id: 68, nome: 'Magnífica*', livro: 'Tormenta20', pagina: 336 },
    { id: 69, nome: 'Magnífica*', livro: 'Tormenta20', pagina: 336 },
    { id: 70, nome: 'Magnífica*', livro: 'Tormenta20', pagina: 336 },
    { id: 71, nome: 'Magnífica*', livro: 'Tormenta20', pagina: 336 },
    { id: 72, nome: 'Magnífica*', livro: 'Tormenta20', pagina: 336 },
    { id: 73, nome: 'Manáfaga', livro: 'Heróis de Arton', pagina: 256 },
    { id: 74, nome: 'Piedosa', livro: 'Tormenta20', pagina: 336 },
    { id: 75, nome: 'Piedosa', livro: 'Tormenta20', pagina: 336 },
    { id: 76, nome: 'Profana', livro: 'Tormenta20', pagina: 336 },
    { id: 77, nome: 'Rebote', livro: 'Heróis de Arton', pagina: 256 },
    { id: 78, nome: 'Reflexiva', livro: 'Heróis de Arton', pagina: 257 },
    { id: 79, nome: 'Ressonante', livro: 'Heróis de Arton', pagina: 257 },
    { id: 80, nome: 'Sagrada', livro: 'Tormenta20', pagina: 336 },
    { id: 81, nome: 'Sanguinária', livro: 'Tormenta20', pagina: 336 },
    { id: 82, nome: 'Sanguinária', livro: 'Tormenta20', pagina: 336 },
    { id: 83, nome: 'Sepulcral', livro: 'Heróis de Arton', pagina: 257 },
    { id: 84, nome: 'Sombria', livro: 'Heróis de Arton', pagina: 257 },
    { id: 85, nome: 'Trovejante', livro: 'Tormenta20', pagina: 336 },
    { id: 86, nome: 'Tumular', livro: 'Tormenta20', pagina: 336 },
    { id: 87, nome: 'Vampírica', livro: 'Heróis de Arton', pagina: 257 },
    { id: 88, nome: 'Veloz', livro: 'Tormenta20', pagina: 336 },
    { id: 89, nome: 'Veloz', livro: 'Tormenta20', pagina: 336 },
    { id: 90, nome: 'Venenosa', livro: 'Tormenta20', pagina: 336 },
    { id: 91, nome: 'Arma específica', livro: 'Role na tabela abaixo', pagina: '-' },
    { id: 92, nome: 'Arma específica', livro: 'Role na tabela abaixo', pagina: '-' },
    { id: 93, nome: 'Arma específica', livro: 'Role na tabela abaixo', pagina: '-' },
    { id: 94, nome: 'Arma específica', livro: 'Role na tabela abaixo', pagina: '-' },
    { id: 95, nome: 'Arma específica', livro: 'Role na tabela abaixo', pagina: '-' },
    { id: 96, nome: 'Arma específica', livro: 'Role na tabela abaixo', pagina: '-' },
    { id: 97, nome: 'Arma específica', livro: 'Role na tabela abaixo', pagina: '-' },
    { id: 98, nome: 'Arma específica', livro: 'Role na tabela abaixo', pagina: '-' },
    { id: 99, nome: 'Arma específica', livro: 'Role na tabela abaixo', pagina: '-' },
    { id: 100, nome: 'Arma específica', livro: 'Role na tabela abaixo', pagina: '-' },
  ];

  armaMagica = [
    { id: 1, nome: 'Adaga da bruma', livro: 'Heróis de Arton', pagina: 257 },
    { id: 2, nome: 'Adaga da bruma', livro: 'Heróis de Arton', pagina: 257 },
    { id: 3, nome: 'Adaga ofídica', livro: 'Deuses de Arton', pagina: 58 },
    { id: 4, nome: 'Adaga sorrateira', livro: 'Deuses de Arton', pagina: 56 },
    { id: 5, nome: 'Alabarda da coragem', livro: 'Deuses de Arton', pagina: 57 },
    { id: 6, nome: 'Alfange dourado', livro: 'Deuses de Arton', pagina: 56 },
    { id: 7, nome: 'Alguma coisa de Nimb...', livro: 'Deuses de Arton', pagina: 58 },
    { id: 8, nome: 'Arco das sombras', livro: 'Heróis de Arton', pagina: 257 },
    { id: 9, nome: 'Arco das sombras', livro: 'Heróis de Arton', pagina: 257 },
    { id: 10, nome: 'Arco das sombras', livro: 'Heróis de Arton', pagina: 257 },
    { id: 11, nome: 'Arco do crepúsculo', livro: 'Heróis de Arton', pagina: 257 },
    { id: 12, nome: 'Arco do crepúsculo', livro: 'Heróis de Arton', pagina: 257 },
    { id: 13, nome: 'Arco do poder', livro: 'Tormenta20', pagina: 336 },
    { id: 14, nome: 'Arco do poder', livro: 'Tormenta20', pagina: 336 },
    { id: 15, nome: 'Arco do poder', livro: 'Tormenta20', pagina: 336 },
    { id: 16, nome: 'Avalanche', livro: 'Tormenta20', pagina: 337 },
    { id: 17, nome: 'Avalanche', livro: 'Tormenta20', pagina: 337 },
    { id: 18, nome: 'Avalanche', livro: 'Tormenta20', pagina: 337 },
    { id: 19, nome: 'Azagaia dos relâmpagos', livro: 'Tormenta20', pagina: 337 },
    { id: 20, nome: 'Azagaia dos relâmpagos', livro: 'Tormenta20', pagina: 337 },
    { id: 21, nome: 'Azagaia dos relâmpagos', livro: 'Tormenta20', pagina: 337 },
    { id: 22, nome: 'Azagaia fantasma', livro: 'Heróis de Arton', pagina: 257 },
    { id: 23, nome: 'Azagaia fantasma', livro: 'Heróis de Arton', pagina: 257 },
    { id: 24, nome: 'Besta estelar', livro: 'Heróis de Arton', pagina: 257 },
    { id: 25, nome: 'Besta estelar', livro: 'Heróis de Arton', pagina: 257 },
    { id: 26, nome: 'Besta estelar', livro: 'Heróis de Arton', pagina: 257 },
    { id: 27, nome: 'Besta explosiva', livro: 'Tormenta20', pagina: 337 },
    { id: 28, nome: 'Besta explosiva', livro: 'Tormenta20', pagina: 337 },
    { id: 29, nome: 'Besta explosiva', livro: 'Tormenta20', pagina: 337 },
    { id: 30, nome: 'Bordão sabichão', livro: 'Deuses de Arton', pagina: 58 },
    { id: 31, nome: 'Cajado das matas', livro: 'Deuses de Arton', pagina: 55 },
    { id: 32, nome: 'Cimitarra solar', livro: 'Deuses de Arton', pagina: 56 },
    { id: 33, nome: 'Clava de lava', livro: 'Heróis de Arton', pagina: 257 },
    { id: 34, nome: 'Clava de lava', livro: 'Heróis de Arton', pagina: 257 },
    { id: 35, nome: 'Espada baronial', livro: 'Tormenta20', pagina: 337 },
    { id: 36, nome: 'Espada baronial', livro: 'Tormenta20', pagina: 337 },
    { id: 37, nome: 'Espada baronial', livro: 'Tormenta20', pagina: 337 },
    { id: 38, nome: 'Espada da tempestade', livro: 'Heróis de Arton', pagina: 257 },
    { id: 39, nome: 'Espada da tempestade', livro: 'Heróis de Arton', pagina: 257 },
    { id: 40, nome: 'Espada do guardião', livro: 'Heróis de Arton', pagina: 257 },
    { id: 41, nome: 'Espada do guardião', livro: 'Heróis de Arton', pagina: 257 },
    { id: 42, nome: 'Espada do guardião', livro: 'Heróis de Arton', pagina: 257 },
    { id: 43, nome: 'Espada imaculada', livro: 'Deuses de Arton', pagina: 59 },
    { id: 44, nome: 'Espada monástica', livro: 'Deuses de Arton', pagina: 57 },
    { id: 45, nome: 'Espada solar', livro: 'Heróis de Arton', pagina: 257 },
    { id: 46, nome: 'Espada solar', livro: 'Heróis de Arton', pagina: 257 },
    { id: 47, nome: 'Espada sortuda', livro: 'Tormenta20', pagina: 337 },
    { id: 48, nome: 'Espada sortuda', livro: 'Tormenta20', pagina: 337 },
    { id: 49, nome: 'Espada sortuda', livro: 'Tormenta20', pagina: 337 },
    { id: 50, nome: 'Florete do vendaval', livro: 'Heróis de Arton', pagina: 258 },
    { id: 51, nome: 'Florete do vendaval', livro: 'Heróis de Arton', pagina: 258 },
    { id: 52, nome: 'Florete fugaz', livro: 'Tormenta20', pagina: 337 },
    { id: 53, nome: 'Florete fugaz', livro: 'Tormenta20', pagina: 337 },
    { id: 54, nome: 'Florete fugaz', livro: 'Tormenta20', pagina: 337 },
    { id: 55, nome: 'Katana da determinação', livro: 'Deuses de Arton', pagina: 57 },
    { id: 56, nome: 'Lâmina da luz', livro: 'Tormenta20', pagina: 338 },
    { id: 57, nome: 'Lâmina da luz', livro: 'Tormenta20', pagina: 338 },
    { id: 58, nome: 'Lâmina da luz', livro: 'Tormenta20', pagina: 338 },
    { id: 59, nome: 'Lança animalesca', livro: 'Tormenta20', pagina: 338 },
    { id: 60, nome: 'Lança animalesca', livro: 'Tormenta20', pagina: 338 },
    { id: 61, nome: 'Lança animalesca', livro: 'Tormenta20', pagina: 338 },
    { id: 62, nome: 'Lança da dominação', livro: 'Deuses de Arton', pagina: 56 },
    { id: 63, nome: 'Lança da fênix', livro: 'Heróis de Arton', pagina: 258 },
    { id: 64, nome: 'Lança da fênix', livro: 'Heróis de Arton', pagina: 258 },
    { id: 65, nome: 'Língua do deserto', livro: 'Tormenta20', pagina: 338 },
    { id: 66, nome: 'Língua do deserto', livro: 'Tormenta20', pagina: 338 },
    { id: 67, nome: 'Língua do deserto', livro: 'Tormenta20', pagina: 338 },
    { id: 68, nome: 'Maça do terror', livro: 'Tormenta20', pagina: 338 },
    { id: 69, nome: 'Maça do terror', livro: 'Tormenta20', pagina: 338 },
    { id: 70, nome: 'Maça do terror', livro: 'Tormenta20', pagina: 338 },
    { id: 71, nome: 'Maça monstruosa', livro: 'Deuses de Arton', pagina: 58 },
    { id: 72, nome: 'Machado da bravura', livro: 'Deuses de Arton', pagina: 55 },
    { id: 73, nome: 'Machado da natureza', livro: 'Heróis de Arton', pagina: 258 },
    { id: 74, nome: 'Machado da natureza', livro: 'Heróis de Arton', pagina: 258 },
    { id: 75, nome: 'Machado do abismo', livro: 'Heróis de Arton', pagina: 258 },
    { id: 76, nome: 'Machado do abismo', livro: 'Heróis de Arton', pagina: 258 },
    { id: 77, nome: 'Machado do vulcão', livro: 'Heróis de Arton', pagina: 258 },
    { id: 78, nome: 'Machado do vulcão', livro: 'Heróis de Arton', pagina: 258 },
    { id: 79, nome: 'Machado do vulcão', livro: 'Heróis de Arton', pagina: 258 },
    { id: 80, nome: 'Machado lamnoriano', livro: 'Deuses de Arton', pagina: 59 },
    { id: 81, nome: 'Machado silvestre', livro: 'Tormenta20', pagina: 338 },
    { id: 82, nome: 'Machado silvestre', livro: 'Tormenta20', pagina: 338 },
    { id: 83, nome: 'Machado silvestre', livro: 'Tormenta20', pagina: 338 },
    { id: 84, nome: 'Mangual aventureiro', livro: 'Deuses de Arton', pagina: 59 },
    { id: 85, nome: 'Martelo da terra', livro: 'Heróis de Arton', pagina: 258 },
    { id: 86, nome: 'Martelo da terra', livro: 'Heróis de Arton', pagina: 258 },
    { id: 87, nome: 'Martelo de Doherimm', livro: 'Tormenta20', pagina: 338 },
    { id: 88, nome: 'Martelo de Doherimm', livro: 'Tormenta20', pagina: 338 },
    { id: 89, nome: 'Martelo de Doherimm', livro: 'Tormenta20', pagina: 338 },
    { id: 90, nome: 'Martelo do titã', livro: 'Heróis de Arton', pagina: 258 },
    { id: 91, nome: 'Martelo do titã', livro: 'Heróis de Arton', pagina: 258 },
    { id: 92, nome: 'Punhal das profundezas', livro: 'Heróis de Arton', pagina: 258 },
    { id: 93, nome: 'Punhal das profundezas', livro: 'Heróis de Arton', pagina: 258 },
    { id: 94, nome: 'Punhal sszzaazita', livro: 'Tormenta20', pagina: 338 },
    { id: 95, nome: 'Punhal sszzaazita', livro: 'Tormenta20', pagina: 338 },
    { id: 96, nome: 'Punhal sszzaazita', livro: 'Tormenta20', pagina: 338 },
    { id: 97, nome: 'Tridente aquoso', livro: 'Deuses de Arton', pagina: 58 },
    { id: 98, nome: 'Vingadora sagrada', livro: 'Tormenta20', pagina: 338 },
    { id: 99, nome: 'Vingadora sagrada', livro: 'Tormenta20', pagina: 338 },
    { id: 100, nome: 'Vingadora sagrada', livro: 'Tormenta20', pagina: 338 },
  ];

  encantoArmadura = [
    { id: 1, nome: 'Abascanto', livro: 'Tormenta20', pagina: 338 },
    { id: 2, nome: 'Abascanto', livro: 'Tormenta20', pagina: 338 },
    { id: 3, nome: 'Abençoado', livro: 'Tormenta20', pagina: 338 },
    { id: 4, nome: 'Abençoado', livro: 'Tormenta20', pagina: 338 },
    { id: 5, nome: 'Abissal', livro: 'Heróis de Arton', pagina: 258 },
    { id: 6, nome: 'Acrobático', livro: 'Tormenta20', pagina: 338 },
    { id: 7, nome: 'Alado', livro: 'Tormenta20', pagina: 338 },
    { id: 8, nome: 'Alado', livro: 'Tormenta20', pagina: 338 },
    { id: 9, nome: 'Ancorada*', livro: 'Heróis de Arton', pagina: 258 },
    { id: 10, nome: 'Animado**', livro: 'Tormenta20', pagina: 338 },
    { id: 11, nome: 'Animado**', livro: 'Tormenta20', pagina: 338 },
    { id: 12, nome: 'Anulador***', livro: 'Heróis de Arton', pagina: 258 },
    { id: 13, nome: 'Arbóreo', livro: 'Heróis de Arton', pagina: 258 },
    { id: 14, nome: 'Assustador', livro: 'Tormenta20', pagina: 338 },
    { id: 15, nome: 'Assustador', livro: 'Tormenta20', pagina: 338 },
    { id: 16, nome: 'Astuto', livro: 'Heróis de Arton', pagina: 258 },
    { id: 17, nome: 'Cáustica', livro: 'Tormenta20', pagina: 338 },
    { id: 18, nome: 'Defensor', livro: 'Tormenta20', pagina: 338 },
    { id: 19, nome: 'Defensor', livro: 'Tormenta20', pagina: 338 },
    { id: 20, nome: 'Defensor', livro: 'Tormenta20', pagina: 338 },
    { id: 21, nome: 'Defensor', livro: 'Tormenta20', pagina: 338 },
    { id: 22, nome: 'Defensor', livro: 'Tormenta20', pagina: 338 },
    { id: 23, nome: 'Defensor', livro: 'Tormenta20', pagina: 338 },
    { id: 24, nome: 'Defensor', livro: 'Tormenta20', pagina: 338 },
    { id: 25, nome: 'Defensor', livro: 'Tormenta20', pagina: 338 },
    { id: 26, nome: 'Defensor', livro: 'Tormenta20', pagina: 338 },
    { id: 27, nome: 'Defensor', livro: 'Tormenta20', pagina: 338 },
    { id: 28, nome: 'Densa*', livro: 'Heróis de Arton', pagina: 258 },
    { id: 29, nome: 'Égide', livro: 'Heróis de Arton', pagina: 258 },
    { id: 30, nome: 'Enraizada*', livro: 'Heróis de Arton', pagina: 258 },
    { id: 31, nome: 'Escorregadio', livro: 'Tormenta20', pagina: 338 },
    { id: 32, nome: 'Esmagador**', livro: 'Tormenta20', pagina: 339 },
    { id: 33, nome: 'Esmagador**', livro: 'Tormenta20', pagina: 339 },
    { id: 34, nome: 'Esmérico', livro: 'Heróis de Arton', pagina: 258 },
    { id: 35, nome: 'Estígio***', livro: 'Heróis de Arton', pagina: 258 },
    { id: 36, nome: 'Estígio***', livro: 'Heróis de Arton', pagina: 258 },
    { id: 37, nome: 'Etéreo', livro: 'Heróis de Arton', pagina: 259 },
    { id: 38, nome: 'Fantasmagórico', livro: 'Tormenta20', pagina: 339 },
    { id: 39, nome: 'Fantasmagórico', livro: 'Tormenta20', pagina: 339 },
    { id: 40, nome: 'Fortificado', livro: 'Tormenta20', pagina: 339 },
    { id: 41, nome: 'Fortificado', livro: 'Tormenta20', pagina: 339 },
    { id: 42, nome: 'Fortificado', livro: 'Tormenta20', pagina: 339 },
    { id: 43, nome: 'Fortificado', livro: 'Tormenta20', pagina: 339 },
    { id: 44, nome: 'Gélido', livro: 'Tormenta20', pagina: 339 },
    { id: 45, nome: 'Geomântico', livro: 'Heróis de Arton', pagina: 259 },
    { id: 46, nome: 'Guardião***', livro: 'Tormenta20', pagina: 339 },
    { id: 47, nome: 'Guardião***', livro: 'Tormenta20', pagina: 339 },
    { id: 48, nome: 'Guardião***', livro: 'Tormenta20', pagina: 339 },
    { id: 49, nome: 'Guardião***', livro: 'Tormenta20', pagina: 339 },
    { id: 50, nome: 'Guardião***', livro: 'Tormenta20', pagina: 339 },
    { id: 51, nome: 'Guardião***', livro: 'Tormenta20', pagina: 339 },
    { id: 52, nome: 'Guardião***', livro: 'Tormenta20', pagina: 339 },
    { id: 53, nome: 'Guardião***', livro: 'Tormenta20', pagina: 339 },
    { id: 54, nome: 'Guardião***', livro: 'Tormenta20', pagina: 339 },
    { id: 55, nome: 'Guardião***', livro: 'Tormenta20', pagina: 339 },
    { id: 56, nome: 'Hipnótico', livro: 'Tormenta20', pagina: 339 },
    { id: 57, nome: 'Hipnótico', livro: 'Tormenta20', pagina: 339 },
    { id: 58, nome: 'Ilusório', livro: 'Tormenta20', pagina: 339 },
    { id: 59, nome: 'Incandescente', livro: 'Tormenta20', pagina: 339 },
    { id: 60, nome: 'Invulnerável', livro: 'Tormenta20', pagina: 339 },
    { id: 61, nome: 'Invulnerável', livro: 'Tormenta20', pagina: 339 },
    { id: 62, nome: 'Invulnerável', livro: 'Tormenta20', pagina: 339 },
    { id: 63, nome: 'Invulnerável', livro: 'Tormenta20', pagina: 339 },
    { id: 64, nome: 'Invulnerável', livro: 'Tormenta20', pagina: 339 },
    { id: 65, nome: 'Ligeira*', livro: 'Heróis de Arton', pagina: 259 },
    { id: 66, nome: 'Luminescente', livro: 'Heróis de Arton', pagina: 259 },
    { id: 67, nome: 'Luminescente', livro: 'Heróis de Arton', pagina: 259 },
    { id: 68, nome: 'Opaco', livro: 'Tormenta20', pagina: 339 },
    { id: 69, nome: 'Opaco', livro: 'Tormenta20', pagina: 339 },
    { id: 70, nome: 'Opaco', livro: 'Tormenta20', pagina: 339 },
    { id: 71, nome: 'Opaco', livro: 'Tormenta20', pagina: 339 },
    { id: 72, nome: 'Opaco', livro: 'Tormenta20', pagina: 339 },
    { id: 73, nome: 'Prístino', livro: 'Heróis de Arton', pagina: 259 },
    { id: 74, nome: 'Protetor', livro: 'Tormenta20', pagina: 339 },
    { id: 75, nome: 'Protetor', livro: 'Tormenta20', pagina: 339 },
    { id: 76, nome: 'Protetor', livro: 'Tormenta20', pagina: 339 },
    { id: 77, nome: 'Protetor', livro: 'Tormenta20', pagina: 339 },
    { id: 78, nome: 'Protetor', livro: 'Tormenta20', pagina: 339 },
    { id: 79, nome: 'Purificador', livro: 'Heróis de Arton', pagina: 259 },
    { id: 80, nome: 'Reanimador', livro: 'Heróis de Arton', pagina: 259 },
    { id: 81, nome: 'Reanimador', livro: 'Heróis de Arton', pagina: 259 },
    { id: 82, nome: 'Refletor', livro: 'Tormenta20', pagina: 339 },
    { id: 83, nome: 'Refletor', livro: 'Tormenta20', pagina: 339 },
    { id: 84, nome: 'Relampejante', livro: 'Tormenta20', pagina: 339 },
    { id: 85, nome: 'Reluzente', livro: 'Tormenta20', pagina: 339 },
    { id: 86, nome: 'Replicante', livro: 'Heróis de Arton', pagina: 259 },
    { id: 87, nome: 'Resiliente', livro: 'Heróis de Arton', pagina: 259 },
    { id: 88, nome: 'Sombrio', livro: 'Tormenta20', pagina: 339 },
    { id: 89, nome: 'Vórtice', livro: 'Heróis de Arton', pagina: 259 },
    { id: 90, nome: 'Zeloso', livro: 'Tormenta20', pagina: 339 },
    { id: 91, nome: 'Item específico', livro: 'Role na tabela abaixo', pagina: '–' },
    { id: 92, nome: 'Item específico', livro: 'Role na tabela abaixo', pagina: '–' },
    { id: 93, nome: 'Item específico', livro: 'Role na tabela abaixo', pagina: '–' },
    { id: 94, nome: 'Item específico', livro: 'Role na tabela abaixo', pagina: '–' },
    { id: 95, nome: 'Item específico', livro: 'Role na tabela abaixo', pagina: '–' },
    { id: 96, nome: 'Item específico', livro: 'Role na tabela abaixo', pagina: '–' },
    { id: 97, nome: 'Item específico', livro: 'Role na tabela abaixo', pagina: '–' },
    { id: 98, nome: 'Item específico', livro: 'Role na tabela abaixo', pagina: '–' },
    { id: 99, nome: 'Item específico', livro: 'Role na tabela abaixo', pagina: '–' },
    { id: 100, nome: 'Item específico', livro: 'Role na tabela abaixo', pagina: '–' },
  ];
  armaduraMagica = [
    { id: 1, nome: 'Armadura da luz', livro: 'Tormenta20', pagina: 340 },
    { id: 2, nome: 'Armadura da luz', livro: 'Tormenta20', pagina: 340 },
    { id: 3, nome: 'Armadura da luz', livro: 'Tormenta20', pagina: 340 },
    { id: 4, nome: 'Armadura da luz', livro: 'Tormenta20', pagina: 340 },
    { id: 5, nome: 'Armadura das sombras profundas', livro: 'Heróis de Arton', pagina: 259 },
    { id: 6, nome: 'Armadura das sombras profundas', livro: 'Heróis de Arton', pagina: 259 },
    { id: 7, nome: 'Armadura das sombras profundas', livro: 'Heróis de Arton', pagina: 259 },
    { id: 8, nome: 'Armadura das sombras profundas', livro: 'Heróis de Arton', pagina: 259 },
    { id: 9, nome: 'Armadura do dragão ancião', livro: 'Heróis de Arton', pagina: 259 },
    { id: 10, nome: 'Armadura do dragão ancião', livro: 'Heróis de Arton', pagina: 259 },
    { id: 11, nome: 'Armadura do dragão ancião', livro: 'Heróis de Arton', pagina: 259 },
    { id: 12, nome: 'Armadura do dragão ancião', livro: 'Heróis de Arton', pagina: 259 },
    { id: 13, nome: 'Armadura do inverno perene', livro: 'Heróis de Arton', pagina: 259 },
    { id: 14, nome: 'Armadura do inverno perene', livro: 'Heróis de Arton', pagina: 259 },
    { id: 15, nome: 'Armadura do inverno perene', livro: 'Heróis de Arton', pagina: 259 },
    { id: 16, nome: 'Armadura do inverno perene', livro: 'Heróis de Arton', pagina: 259 },
    { id: 17, nome: 'Armadura do julgamento', livro: 'Deuses de Arton', pagina: 57 },
    { id: 18, nome: 'Armadura do julgamento', livro: 'Deuses de Arton', pagina: 57 },
    { id: 19, nome: 'Baluarte anão', livro: 'Tormenta20', pagina: 340 },
    { id: 20, nome: 'Baluarte anão', livro: 'Tormenta20', pagina: 340 },
    { id: 21, nome: 'Baluarte anão', livro: 'Tormenta20', pagina: 340 },
    { id: 22, nome: 'Baluarte anão', livro: 'Tormenta20', pagina: 340 },
    { id: 23, nome: 'Carapaça demoníaca', livro: 'Tormenta20', pagina: 340 },
    { id: 24, nome: 'Carapaça demoníaca', livro: 'Tormenta20', pagina: 340 },
    { id: 25, nome: 'Carapaça demoníaca', livro: 'Tormenta20', pagina: 340 },
    { id: 26, nome: 'Carapaça demoníaca', livro: 'Tormenta20', pagina: 340 },
    { id: 27, nome: 'Cota da serpente marinha', livro: 'Heróis de Arton', pagina: 259 },
    { id: 28, nome: 'Cota da serpente marinha', livro: 'Heróis de Arton', pagina: 259 },
    { id: 29, nome: 'Cota da serpente marinha', livro: 'Heróis de Arton', pagina: 259 },
    { id: 30, nome: 'Cota da serpente marinha', livro: 'Heróis de Arton', pagina: 259 },
    { id: 31, nome: 'Cota élfica', livro: 'Tormenta20', pagina: 340 },
    { id: 32, nome: 'Cota élfica', livro: 'Tormenta20', pagina: 340 },
    { id: 33, nome: 'Cota élfica', livro: 'Tormenta20', pagina: 340 },
    { id: 34, nome: 'Cota élfica', livro: 'Tormenta20', pagina: 340 },
    { id: 35, nome: 'Cota élfica', livro: 'Tormenta20', pagina: 340 },
    { id: 36, nome: 'Cota élfica', livro: 'Tormenta20', pagina: 340 },
    { id: 37, nome: 'Cota élfica', livro: 'Tormenta20', pagina: 340 },
    { id: 38, nome: 'Cota élfica', livro: 'Tormenta20', pagina: 340 },
    { id: 39, nome: 'Cota élfica', livro: 'Tormenta20', pagina: 340 },
    { id: 40, nome: 'Cota élfica', livro: 'Tormenta20', pagina: 340 },
    { id: 41, nome: 'Couraça do comando', livro: 'Tormenta20', pagina: 340 },
    { id: 42, nome: 'Couraça do comando', livro: 'Tormenta20', pagina: 340 },
    { id: 43, nome: 'Couraça do comando', livro: 'Tormenta20', pagina: 340 },
    { id: 44, nome: 'Couraça do comando', livro: 'Tormenta20', pagina: 340 },
    { id: 45, nome: 'Couraça do guardião celeste', livro: 'Heróis de Arton', pagina: 259 },
    { id: 46, nome: 'Couraça do guardião celeste', livro: 'Heróis de Arton', pagina: 259 },
    { id: 47, nome: 'Couraça do guardião celeste', livro: 'Heróis de Arton', pagina: 259 },
    { id: 48, nome: 'Couraça do guardião celeste', livro: 'Heróis de Arton', pagina: 259 },
    { id: 49, nome: 'Couro de monstro', livro: 'Tormenta20', pagina: 340 },
    { id: 50, nome: 'Couro de monstro', livro: 'Tormenta20', pagina: 340 },
    { id: 51, nome: 'Couro de monstro', livro: 'Tormenta20', pagina: 340 },
    { id: 52, nome: 'Couro de monstro', livro: 'Tormenta20', pagina: 340 },
    { id: 53, nome: 'Escudo da ira vulcânica', livro: 'Heróis de Arton', pagina: 260 },
    { id: 54, nome: 'Escudo da ira vulcânica', livro: 'Heróis de Arton', pagina: 260 },
    { id: 55, nome: 'Escudo da ira vulcânica', livro: 'Heróis de Arton', pagina: 260 },
    { id: 56, nome: 'Escudo da ira vulcânica', livro: 'Heróis de Arton', pagina: 260 },
    { id: 57, nome: 'Escudo da luz estelar', livro: 'Heróis de Arton', pagina: 260 },
    { id: 58, nome: 'Escudo da luz estelar', livro: 'Heróis de Arton', pagina: 260 },
    { id: 59, nome: 'Escudo da luz estelar', livro: 'Heróis de Arton', pagina: 260 },
    { id: 60, nome: 'Escudo da luz estelar', livro: 'Heróis de Arton', pagina: 260 },
    { id: 61, nome: 'Escudo da natureza viva', livro: 'Heróis de Arton', pagina: 260 },
    { id: 62, nome: 'Escudo da natureza viva', livro: 'Heróis de Arton', pagina: 260 },
    { id: 63, nome: 'Escudo da natureza viva', livro: 'Heróis de Arton', pagina: 260 },
    { id: 64, nome: 'Escudo da natureza viva', livro: 'Heróis de Arton', pagina: 260 },
    { id: 65, nome: 'Escudo de Azgher', livro: 'Tormenta20', pagina: 340 },
    { id: 66, nome: 'Escudo de Azgher', livro: 'Tormenta20', pagina: 340 },
    { id: 67, nome: 'Escudo de Azgher', livro: 'Tormenta20', pagina: 340 },
    { id: 68, nome: 'Escudo de Azgher', livro: 'Tormenta20', pagina: 340 },
    { id: 69, nome: 'Escudo do conjurador', livro: 'Tormenta20', pagina: 340 },
    { id: 70, nome: 'Escudo do conjurador', livro: 'Tormenta20', pagina: 340 },
    { id: 71, nome: 'Escudo do conjurador', livro: 'Tormenta20', pagina: 340 },
    { id: 72, nome: 'Escudo do conjurador', livro: 'Tormenta20', pagina: 340 },
    { id: 73, nome: 'Escudo do eclipse', livro: 'Tormenta20', pagina: 340 },
    { id: 74, nome: 'Escudo do eclipse', livro: 'Tormenta20', pagina: 340 },
    { id: 75, nome: 'Escudo do eclipse', livro: 'Tormenta20', pagina: 340 },
    { id: 76, nome: 'Escudo do eclipse', livro: 'Tormenta20', pagina: 340 },
    { id: 77, nome: 'Escudo do grifo', livro: 'Heróis de Arton', pagina: 260 },
    { id: 78, nome: 'Escudo do grifo', livro: 'Heróis de Arton', pagina: 260 },
    { id: 79, nome: 'Escudo do grifo', livro: 'Heróis de Arton', pagina: 260 },
    { id: 80, nome: 'Escudo do grifo', livro: 'Heróis de Arton', pagina: 260 },
    { id: 81, nome: 'Escudo do leão', livro: 'Tormenta20', pagina: 340 },
    { id: 82, nome: 'Escudo do leão', livro: 'Tormenta20', pagina: 340 },
    { id: 83, nome: 'Escudo do leão', livro: 'Tormenta20', pagina: 340 },
    { id: 84, nome: 'Escudo do leão', livro: 'Tormenta20', pagina: 340 },
    { id: 85, nome: 'Escudo do leão', livro: 'Tormenta20', pagina: 340 },
    { id: 86, nome: 'Escudo do leão', livro: 'Tormenta20', pagina: 340 },
    { id: 87, nome: 'Escudo do trovão', livro: 'Heróis de Arton', pagina: 260 },
    { id: 88, nome: 'Escudo do trovão', livro: 'Heróis de Arton', pagina: 260 },
    { id: 89, nome: 'Escudo do trovão', livro: 'Heróis de Arton', pagina: 260 },
    { id: 90, nome: 'Escudo do trovão', livro: 'Heróis de Arton', pagina: 260 },
    { id: 91, nome: 'Escudo espinhoso', livro: 'Tormenta20', pagina: 340 },
    { id: 92, nome: 'Escudo espinhoso', livro: 'Tormenta20', pagina: 340 },
    { id: 93, nome: 'Escudo espinhoso', livro: 'Tormenta20', pagina: 340 },
    { id: 94, nome: 'Escudo espinhoso', livro: 'Tormenta20', pagina: 340 },
    { id: 95, nome: 'Loriga do centurião', livro: 'Tormenta20', pagina: 340 },
    { id: 96, nome: 'Loriga do centurião', livro: 'Tormenta20', pagina: 340 },
    { id: 97, nome: 'Loriga do centurião', livro: 'Tormenta20', pagina: 340 },
    { id: 98, nome: 'Loriga do centurião', livro: 'Tormenta20', pagina: 340 },
    { id: 99, nome: 'Manto da noite', livro: 'Tormenta20', pagina: 340 },
    { id: 100, nome: 'Manto da noite', livro: 'Tormenta20', pagina: 340 },
  ];

  encantoEsoterico = [
    { id: 1, nome: 'Abafador', livro: 'Heróis de Arton', pagina: 260 },
    { id: 2, nome: 'Abafador', livro: 'Heróis de Arton', pagina: 260 },
    { id: 3, nome: 'Bélico', livro: 'Heróis de Arton', pagina: 260 },
    { id: 4, nome: 'Bélico', livro: 'Heróis de Arton', pagina: 260 },
    { id: 5, nome: 'Bélico', livro: 'Heróis de Arton', pagina: 260 },
    { id: 6, nome: 'Bélico', livro: 'Heróis de Arton', pagina: 260 },
    { id: 7, nome: 'Bélico', livro: 'Heróis de Arton', pagina: 260 },
    { id: 8, nome: 'Bélico', livro: 'Heróis de Arton', pagina: 260 },
    { id: 9, nome: 'Bélico', livro: 'Heróis de Arton', pagina: 260 },
    { id: 10, nome: 'Bélico', livro: 'Heróis de Arton', pagina: 260 },
    { id: 11, nome: 'Bélico', livro: 'Heróis de Arton', pagina: 260 },
    { id: 12, nome: 'Bélico', livro: 'Heróis de Arton', pagina: 260 },
    { id: 13, nome: 'Caridoso', livro: 'Heróis de Arton', pagina: 260 },
    { id: 14, nome: 'Caridoso', livro: 'Heróis de Arton', pagina: 260 },
    { id: 15, nome: 'Caridoso', livro: 'Heróis de Arton', pagina: 260 },
    { id: 16, nome: 'Caridoso', livro: 'Heróis de Arton', pagina: 260 },
    { id: 17, nome: 'Chocante', livro: 'Heróis de Arton', pagina: 260 },
    { id: 18, nome: 'Chocante', livro: 'Heróis de Arton', pagina: 260 },
    { id: 19, nome: 'Chocante', livro: 'Heróis de Arton', pagina: 260 },
    { id: 20, nome: 'Chocante', livro: 'Heróis de Arton', pagina: 260 },
    { id: 21, nome: 'Clemente', livro: 'Heróis de Arton', pagina: 260 },
    { id: 22, nome: 'Clemente', livro: 'Heróis de Arton', pagina: 260 },
    { id: 23, nome: 'Clemente', livro: 'Heróis de Arton', pagina: 260 },
    { id: 24, nome: 'Clemente', livro: 'Heróis de Arton', pagina: 260 },
    { id: 25, nome: 'Clemente', livro: 'Heróis de Arton', pagina: 260 },
    { id: 26, nome: 'Clemente', livro: 'Heróis de Arton', pagina: 260 },
    { id: 27, nome: 'Clemente', livro: 'Heróis de Arton', pagina: 260 },
    { id: 28, nome: 'Clemente', livro: 'Heróis de Arton', pagina: 260 },
    { id: 29, nome: 'Clemente', livro: 'Heróis de Arton', pagina: 260 },
    { id: 30, nome: 'Clemente', livro: 'Heróis de Arton', pagina: 260 },
    { id: 31, nome: 'Contido', livro: 'Heróis de Arton', pagina: 260 },
    { id: 32, nome: 'Contido', livro: 'Heróis de Arton', pagina: 260 },
    { id: 33, nome: 'Embusteiro', livro: 'Heróis de Arton', pagina: 260 },
    { id: 34, nome: 'Embusteiro', livro: 'Heróis de Arton', pagina: 260 },
    { id: 35, nome: 'Emergencial', livro: 'Heróis de Arton', pagina: 260 },
    { id: 36, nome: 'Emergencial', livro: 'Heróis de Arton', pagina: 260 },
    { id: 37, nome: 'Encadeado', livro: 'Heróis de Arton', pagina: 260 },
    { id: 38, nome: 'Encadeado', livro: 'Heróis de Arton', pagina: 260 },
    { id: 39, nome: 'Encadeado', livro: 'Heróis de Arton', pagina: 260 },
    { id: 40, nome: 'Encadeado', livro: 'Heróis de Arton', pagina: 260 },
    { id: 41, nome: 'Escultor', livro: 'Heróis de Arton', pagina: 260 },
    { id: 42, nome: 'Escultor', livro: 'Heróis de Arton', pagina: 260 },
    { id: 43, nome: 'Frugal', livro: 'Heróis de Arton', pagina: 261 },
    { id: 44, nome: 'Frugal', livro: 'Heróis de Arton', pagina: 261 },
    { id: 45, nome: 'Glacial', livro: 'Heróis de Arton', pagina: 261 },
    { id: 46, nome: 'Glacial', livro: 'Heróis de Arton', pagina: 261 },
    { id: 47, nome: 'Glacial', livro: 'Heróis de Arton', pagina: 261 },
    { id: 48, nome: 'Glacial', livro: 'Heróis de Arton', pagina: 261 },
    { id: 49, nome: 'Imperioso', livro: 'Heróis de Arton', pagina: 261 },
    { id: 50, nome: 'Imperioso', livro: 'Heróis de Arton', pagina: 261 },
    { id: 51, nome: 'Implacável*', livro: 'Heróis de Arton', pagina: 261 },
    { id: 52, nome: 'Implacável*', livro: 'Heróis de Arton', pagina: 261 },
    { id: 53, nome: 'Incriminador', livro: 'Heróis de Arton', pagina: 261 },
    { id: 54, nome: 'Incriminador', livro: 'Heróis de Arton', pagina: 261 },
    { id: 55, nome: 'Inflamável', livro: 'Heróis de Arton', pagina: 261 },
    { id: 56, nome: 'Inflamável', livro: 'Heróis de Arton', pagina: 261 },
    { id: 57, nome: 'Inflamável', livro: 'Heróis de Arton', pagina: 261 },
    { id: 58, nome: 'Inflamável', livro: 'Heróis de Arton', pagina: 261 },
    { id: 59, nome: 'Inflamável', livro: 'Heróis de Arton', pagina: 261 },
    { id: 60, nome: 'Inflamável', livro: 'Heróis de Arton', pagina: 261 },
    { id: 61, nome: 'Inflamável', livro: 'Heróis de Arton', pagina: 261 },
    { id: 62, nome: 'Inquisidor', livro: 'Heróis de Arton', pagina: 261 },
    { id: 63, nome: 'Inquisidor', livro: 'Heróis de Arton', pagina: 261 },
    { id: 64, nome: 'Inquisidor', livro: 'Heróis de Arton', pagina: 261 },
    { id: 65, nome: 'Inquisidor', livro: 'Heróis de Arton', pagina: 261 },
    { id: 66, nome: 'Insistente', livro: 'Heróis de Arton', pagina: 261 },
    { id: 67, nome: 'Insistente', livro: 'Heróis de Arton', pagina: 261 },
    { id: 68, nome: 'Insistente', livro: 'Heróis de Arton', pagina: 261 },
    { id: 69, nome: 'Insistente', livro: 'Heróis de Arton', pagina: 261 },
    { id: 70, nome: 'Khalmyrita', livro: 'Heróis de Arton', pagina: 261 },
    { id: 71, nome: 'Khalmyrita', livro: 'Heróis de Arton', pagina: 261 },
    { id: 72, nome: 'Majestoso*', livro: 'Heróis de Arton', pagina: 261 },
    { id: 73, nome: 'Majestoso*', livro: 'Heróis de Arton', pagina: 261 },
    { id: 74, nome: 'Majestoso*', livro: 'Heróis de Arton', pagina: 261 },
    { id: 75, nome: 'Majestoso*', livro: 'Heróis de Arton', pagina: 261 },
    { id: 76, nome: 'Majestoso*', livro: 'Heróis de Arton', pagina: 261 },
    { id: 77, nome: 'Majestoso*', livro: 'Heróis de Arton', pagina: 261 },
    { id: 78, nome: 'Majestoso*', livro: 'Heróis de Arton', pagina: 261 },
    { id: 79, nome: 'Majestoso*', livro: 'Heróis de Arton', pagina: 261 },
    { id: 80, nome: 'Majestoso*', livro: 'Heróis de Arton', pagina: 261 },
    { id: 81, nome: 'Majestoso*', livro: 'Heróis de Arton', pagina: 261 },
    { id: 82, nome: 'Nímbico', livro: 'Heróis de Arton', pagina: 261 },
    { id: 83, nome: 'Nímbico', livro: 'Heróis de Arton', pagina: 261 },
    { id: 84, nome: 'Pulverizante*', livro: 'Heróis de Arton', pagina: 261 },
    { id: 85, nome: 'Retaliador', livro: 'Heróis de Arton', pagina: 261 },
    { id: 86, nome: 'Sanguessuga', livro: 'Heróis de Arton', pagina: 261 },
    { id: 87, nome: 'Sanguessuga', livro: 'Heróis de Arton', pagina: 261 },
    { id: 88, nome: 'Traiçoeiro', livro: 'Heróis de Arton', pagina: 261 },
    { id: 89, nome: 'Verdugo', livro: 'Heróis de Arton', pagina: 261 },
    { id: 90, nome: 'Verdugo', livro: 'Heróis de Arton', pagina: 261 },
    { id: 91, nome: 'Esotérico específico', livro: '—', pagina: null },
    { id: 92, nome: 'Esotérico específico', livro: '—', pagina: null },
    { id: 93, nome: 'Esotérico específico', livro: '—', pagina: null },
    { id: 94, nome: 'Esotérico específico', livro: '—', pagina: null },
    { id: 95, nome: 'Esotérico específico', livro: '—', pagina: null },
    { id: 96, nome: 'Esotérico específico', livro: '—', pagina: null },
    { id: 97, nome: 'Esotérico específico', livro: '—', pagina: null },
    { id: 98, nome: 'Esotérico específico', livro: '—', pagina: null },
    { id: 99, nome: 'Esotérico específico', livro: '—', pagina: null },
    { id: 100, nome: 'Esotérico específico', livro: '—', pagina: null },
  ];

  esotericoMagico = [
    { id: 1, nome: 'Cajado da destruição', livro: 'Tormenta20', pagina: 337 },
    { id: 2, nome: 'Cajado da destruição', livro: 'Tormenta20', pagina: 337 },
    { id: 3, nome: 'Cajado da destruição', livro: 'Tormenta20', pagina: 337 },
    { id: 4, nome: 'Cajado da destruição', livro: 'Tormenta20', pagina: 337 },
    { id: 5, nome: 'Cajado da destruição', livro: 'Tormenta20', pagina: 337 },
    { id: 6, nome: 'Cajado da destruição', livro: 'Tormenta20', pagina: 337 },
    { id: 7, nome: 'Cajado da destruição', livro: 'Tormenta20', pagina: 337 },
    { id: 8, nome: 'Cajado da destruição', livro: 'Tormenta20', pagina: 337 },
    { id: 9, nome: 'Cajado da destruição', livro: 'Tormenta20', pagina: 337 },
    { id: 10, nome: 'Cajado da destruição', livro: 'Tormenta20', pagina: 337 },
    { id: 11, nome: 'Cajado da destruição', livro: 'Tormenta20', pagina: 337 },
    { id: 12, nome: 'Cajado da destruição', livro: 'Tormenta20', pagina: 337 },
    { id: 13, nome: 'Cajado da destruição', livro: 'Tormenta20', pagina: 337 },
    { id: 14, nome: 'Cajado da destruição', livro: 'Tormenta20', pagina: 337 },
    { id: 15, nome: 'Cajado da destruição', livro: 'Tormenta20', pagina: 337 },
    { id: 16, nome: 'Cajado da destruição', livro: 'Tormenta20', pagina: 337 },
    { id: 17, nome: 'Cajado da destruição', livro: 'Tormenta20', pagina: 337 },
    { id: 18, nome: 'Cajado da destruição', livro: 'Tormenta20', pagina: 337 },
    { id: 19, nome: 'Cajado da destruição', livro: 'Tormenta20', pagina: 337 },
    { id: 20, nome: 'Cajado da destruição', livro: 'Tormenta20', pagina: 337 },
    { id: 21, nome: 'Cajado da vida', livro: 'Tormenta20', pagina: 337 },
    { id: 22, nome: 'Cajado da vida', livro: 'Tormenta20', pagina: 337 },
    { id: 23, nome: 'Cajado da vida', livro: 'Tormenta20', pagina: 337 },
    { id: 24, nome: 'Cajado da vida', livro: 'Tormenta20', pagina: 337 },
    { id: 25, nome: 'Cajado da vida', livro: 'Tormenta20', pagina: 337 },
    { id: 26, nome: 'Cajado da vida', livro: 'Tormenta20', pagina: 337 },
    { id: 27, nome: 'Cajado da vida', livro: 'Tormenta20', pagina: 337 },
    { id: 28, nome: 'Cajado da vida', livro: 'Tormenta20', pagina: 337 },
    { id: 29, nome: 'Cajado da vida', livro: 'Tormenta20', pagina: 337 },
    { id: 30, nome: 'Cajado da vida', livro: 'Tormenta20', pagina: 337 },
    { id: 31, nome: 'Cajado da vida', livro: 'Tormenta20', pagina: 337 },
    { id: 32, nome: 'Cajado da vida', livro: 'Tormenta20', pagina: 337 },
    { id: 33, nome: 'Cajado da vida', livro: 'Tormenta20', pagina: 337 },
    { id: 34, nome: 'Cajado da vida', livro: 'Tormenta20', pagina: 337 },
    { id: 35, nome: 'Cajado da vida', livro: 'Tormenta20', pagina: 337 },
    { id: 36, nome: 'Cajado da vida', livro: 'Tormenta20', pagina: 337 },
    { id: 37, nome: 'Cajado da vida', livro: 'Tormenta20', pagina: 337 },
    { id: 38, nome: 'Cajado da vida', livro: 'Tormenta20', pagina: 337 },
    { id: 39, nome: 'Cajado da vida', livro: 'Tormenta20', pagina: 337 },
    { id: 40, nome: 'Cajado da vida', livro: 'Tormenta20', pagina: 337 },
    { id: 41, nome: 'Cajado das marés', livro: 'Heróis de Arton', pagina: 262 },
    { id: 42, nome: 'Cajado das marés', livro: 'Heróis de Arton', pagina: 262 },
    { id: 43, nome: 'Cajado das marés', livro: 'Heróis de Arton', pagina: 262 },
    { id: 44, nome: 'Cajado das marés', livro: 'Heróis de Arton', pagina: 262 },
    { id: 45, nome: 'Cajado das marés', livro: 'Heróis de Arton', pagina: 262 },
    { id: 46, nome: 'Cajado do poder', livro: 'Tormenta20', pagina: 337 },
    { id: 47, nome: 'Cajado do poder', livro: 'Tormenta20', pagina: 337 },
    { id: 48, nome: 'Cajado do poder', livro: 'Tormenta20', pagina: 337 },
    { id: 49, nome: 'Cajado do poder', livro: 'Tormenta20', pagina: 337 },
    { id: 50, nome: 'Cajado do poder', livro: 'Tormenta20', pagina: 337 },
    { id: 51, nome: 'Cajado do poder', livro: 'Tormenta20', pagina: 337 },
    { id: 52, nome: 'Cajado do poder', livro: 'Tormenta20', pagina: 337 },
    { id: 53, nome: 'Cajado do poder', livro: 'Tormenta20', pagina: 337 },
    { id: 54, nome: 'Cajado do poder', livro: 'Tormenta20', pagina: 337 },
    { id: 55, nome: 'Cajado do poder', livro: 'Tormenta20', pagina: 337 },
    { id: 56, nome: 'Cajado do poder', livro: 'Tormenta20', pagina: 337 },
    { id: 57, nome: 'Cajado do poder', livro: 'Tormenta20', pagina: 337 },
    { id: 58, nome: 'Cajado do poder', livro: 'Tormenta20', pagina: 337 },
    { id: 59, nome: 'Cajado do poder', livro: 'Tormenta20', pagina: 337 },
    { id: 60, nome: 'Cajado do poder', livro: 'Tormenta20', pagina: 337 },
    { id: 61, nome: 'Cálice sagrado', livro: 'Heróis de Arton', pagina: 262 },
    { id: 62, nome: 'Cálice sagrado', livro: 'Heróis de Arton', pagina: 262 },
    { id: 63, nome: 'Cálice sagrado', livro: 'Heróis de Arton', pagina: 262 },
    { id: 64, nome: 'Cálice sagrado', livro: 'Heróis de Arton', pagina: 262 },
    { id: 65, nome: 'Cálice sagrado', livro: 'Heróis de Arton', pagina: 262 },
    { id: 66, nome: 'Cálice sagrado', livro: 'Heróis de Arton', pagina: 262 },
    { id: 67, nome: 'Cálice sagrado', livro: 'Heróis de Arton', pagina: 262 },
    { id: 68, nome: 'Cálice sagrado', livro: 'Heróis de Arton', pagina: 262 },
    { id: 69, nome: 'Cálice sagrado', livro: 'Heróis de Arton', pagina: 262 },
    { id: 70, nome: 'Cálice sagrado', livro: 'Heróis de Arton', pagina: 262 },
    { id: 71, nome: 'Cálice sagrado', livro: 'Heróis de Arton', pagina: 262 },
    { id: 72, nome: 'Cálice sagrado', livro: 'Heróis de Arton', pagina: 262 },
    { id: 73, nome: 'Cálice sagrado', livro: 'Heróis de Arton', pagina: 262 },
    { id: 74, nome: 'Cálice sagrado', livro: 'Heróis de Arton', pagina: 262 },
    { id: 75, nome: 'Cálice sagrado', livro: 'Heróis de Arton', pagina: 262 },
    { id: 76, nome: 'Relógio do arcanista', livro: 'Heróis de Arton', pagina: 262 },
    { id: 77, nome: 'Relógio do arcanista', livro: 'Heróis de Arton', pagina: 262 },
    { id: 78, nome: 'Relógio do arcanista', livro: 'Heróis de Arton', pagina: 262 },
    { id: 79, nome: 'Relógio do arcanista', livro: 'Heróis de Arton', pagina: 262 },
    { id: 80, nome: 'Relógio do arcanista', livro: 'Heróis de Arton', pagina: 262 },
    { id: 81, nome: 'Relógio do arcanista', livro: 'Heróis de Arton', pagina: 262 },
    { id: 82, nome: 'Relógio do arcanista', livro: 'Heróis de Arton', pagina: 262 },
    { id: 83, nome: 'Relógio do arcanista', livro: 'Heróis de Arton', pagina: 262 },
    { id: 84, nome: 'Relógio do arcanista', livro: 'Heróis de Arton', pagina: 262 },
    { id: 85, nome: 'Relógio do arcanista', livro: 'Heróis de Arton', pagina: 262 },
    { id: 86, nome: 'Varinha da generosidade', livro: 'Deuses de Arton', pagina: 59 },
    { id: 87, nome: 'Varinha da generosidade', livro: 'Deuses de Arton', pagina: 59 },
    { id: 88, nome: 'Varinha da generosidade', livro: 'Deuses de Arton', pagina: 59 },
    { id: 89, nome: 'Varinha da generosidade', livro: 'Deuses de Arton', pagina: 59 },
    { id: 90, nome: 'Varinha da generosidade', livro: 'Deuses de Arton', pagina: 59 },
    { id: 91, nome: 'Varinha milenar', livro: 'Heróis de Arton', pagina: 262 },
    { id: 92, nome: 'Varinha milenar', livro: 'Heróis de Arton', pagina: 262 },
    { id: 93, nome: 'Varinha milenar', livro: 'Heróis de Arton', pagina: 262 },
    { id: 94, nome: 'Varinha milenar', livro: 'Heróis de Arton', pagina: 262 },
    { id: 95, nome: 'Varinha milenar', livro: 'Heróis de Arton', pagina: 262 },
    { id: 96, nome: 'Varinha milenar', livro: 'Heróis de Arton', pagina: 262 },
    { id: 97, nome: 'Varinha milenar', livro: 'Heróis de Arton', pagina: 262 },
    { id: 98, nome: 'Varinha milenar', livro: 'Heróis de Arton', pagina: 262 },
    { id: 99, nome: 'Varinha milenar', livro: 'Heróis de Arton', pagina: 262 },
    { id: 100, nome: 'Varinha milenar', livro: 'Heróis de Arton', pagina: 262 },
  ];

  acessorioMenor = [
    { id: 1, nome: 'Algibeira mordedora', preco: 1000, livro: 'Heróis de Arton', pagina: 263 },
    { id: 2, nome: 'Elixir da mente dividida', preco: 1500, livro: 'Heróis de Arton', pagina: 265 },
    { id: 3, nome: 'Papiro das estrelas', preco: 1500, livro: 'Heróis de Arton', pagina: 267 },
    { id: 4, nome: 'Anel do sustento', preco: 3000, livro: 'Tormenta20', pagina: 342 },
    { id: 5, nome: 'Bainha mágica', preco: 3000, livro: 'Tormenta20', pagina: 342 },
    { id: 6, nome: 'Bainha mágica', preco: 3000, livro: 'Tormenta20', pagina: 342 },
    { id: 7, nome: 'Bainha mágica', preco: 3000, livro: 'Tormenta20', pagina: 342 },
    { id: 8, nome: 'Corda da escalada', preco: 3000, livro: 'Tormenta20', pagina: 343 },
    { id: 9, nome: 'Corda da escalada', preco: 3000, livro: 'Tormenta20', pagina: 343 },
    { id: 10, nome: 'Ferraduras da velocidade', preco: 3000, livro: 'Tormenta20', pagina: 344 },
    { id: 11, nome: 'Garrafa da fumaça eterna', preco: 3000, livro: 'Tormenta20', pagina: 344 },
    { id: 12, nome: 'Garrafa da fumaça eterna', preco: 3000, livro: 'Tormenta20', pagina: 344 },
    { id: 13, nome: 'Gema da luminosidade', preco: 3000, livro: 'Tormenta20', pagina: 344 },
    { id: 14, nome: 'Gema da luminosidade', preco: 3000, livro: 'Tormenta20', pagina: 344 },
    { id: 15, nome: 'Gema da luminosidade', preco: 3000, livro: 'Tormenta20', pagina: 344 },
    { id: 16, nome: 'Manto élfico', preco: 3000, livro: 'Tormenta20', pagina: 345 },
    { id: 17, nome: 'Manto élfico', preco: 3000, livro: 'Tormenta20', pagina: 345 },
    { id: 18, nome: 'Manto élfico', preco: 3000, livro: 'Tormenta20', pagina: 345 },
    { id: 19, nome: 'Mochila de carga', preco: 3000, livro: 'Tormenta20', pagina: 345 },
    { id: 20, nome: 'Mochila de carga', preco: 3000, livro: 'Tormenta20', pagina: 345 },
    { id: 21, nome: 'Mochila de carga', preco: 3000, livro: 'Tormenta20', pagina: 345 },
    { id: 22, nome: 'Amuleto da visão etérea', preco: 3000, livro: 'Heróis de Arton', pagina: 263 },
    { id: 23, nome: 'Amuleto da visão etérea', preco: 3000, livro: 'Heróis de Arton', pagina: 263 },
    { id: 24, nome: 'Cinturão do trobo', preco: 3000, livro: 'Heróis de Arton', pagina: 264 },
    { id: 25, nome: 'Cinturão do trobo', preco: 3000, livro: 'Heróis de Arton', pagina: 264 },
    { id: 26, nome: 'Elixir da eternidade', preco: 3000, livro: 'Heróis de Arton', pagina: 265 },
    { id: 27, nome: 'Elixir da eternidade', preco: 3000, livro: 'Heróis de Arton', pagina: 265 },
    { id: 28, nome: 'Pérola da nulificação', preco: 3000, livro: 'Heróis de Arton', pagina: 267 },
    { id: 29, nome: 'Pérola da nulificação', preco: 3000, livro: 'Heróis de Arton', pagina: 267 },
    { id: 30, nome: 'Saco dos ventos silenciosos', preco: 3000, livro: 'Heróis de Arton', pagina: 267 },
    { id: 31, nome: 'Saco dos ventos silenciosos', preco: 3000, livro: 'Heróis de Arton', pagina: 267 },
    { id: 32, nome: 'Brincos da sagacidade', preco: 4500, livro: 'Tormenta20', pagina: 342 },
    { id: 33, nome: 'Brincos da sagacidade', preco: 4500, livro: 'Tormenta20', pagina: 342 },
    { id: 34, nome: 'Brincos da sagacidade', preco: 4500, livro: 'Tormenta20', pagina: 342 },
    { id: 35, nome: 'Brincos da sagacidade', preco: 4500, livro: 'Tormenta20', pagina: 342 },
    { id: 36, nome: 'Brincos da sagacidade', preco: 4500, livro: 'Tormenta20', pagina: 342 },
    { id: 37, nome: 'Luvas da delicadeza', preco: 4500, livro: 'Tormenta20', pagina: 344 },
    { id: 38, nome: 'Luvas da delicadeza', preco: 4500, livro: 'Tormenta20', pagina: 344 },
    { id: 39, nome: 'Luvas da delicadeza', preco: 4500, livro: 'Tormenta20', pagina: 344 },
    { id: 40, nome: 'Luvas da delicadeza', preco: 4500, livro: 'Tormenta20', pagina: 344 },
    { id: 41, nome: 'Luvas da delicadeza', preco: 4500, livro: 'Tormenta20', pagina: 344 },
    { id: 42, nome: 'Manoplas da força do ogro', preco: 4500, livro: 'Tormenta20', pagina: 344 },
    { id: 43, nome: 'Manoplas da força do ogro', preco: 4500, livro: 'Tormenta20', pagina: 344 },
    { id: 44, nome: 'Manoplas da força do ogro', preco: 4500, livro: 'Tormenta20', pagina: 344 },
    { id: 45, nome: 'Manoplas da força do ogro', preco: 4500, livro: 'Tormenta20', pagina: 344 },
    { id: 46, nome: 'Manoplas da força do ogro', preco: 4500, livro: 'Tormenta20', pagina: 344 },
    { id: 47, nome: 'Manto da resistência', preco: 4500, livro: 'Tormenta20', pagina: 344 },
    { id: 48, nome: 'Manto da resistência', preco: 4500, livro: 'Tormenta20', pagina: 344 },
    { id: 49, nome: 'Manto da resistência', preco: 4500, livro: 'Tormenta20', pagina: 344 },
    { id: 50, nome: 'Manto da resistência', preco: 4500, livro: 'Tormenta20', pagina: 344 },
    { id: 51, nome: 'Manto do fascínio', preco: 4500, livro: 'Tormenta20', pagina: 344 },
    { id: 52, nome: 'Manto do fascínio', preco: 4500, livro: 'Tormenta20', pagina: 344 },
    { id: 53, nome: 'Manto do fascínio', preco: 4500, livro: 'Tormenta20', pagina: 344 },
    { id: 54, nome: 'Manto do fascínio', preco: 4500, livro: 'Tormenta20', pagina: 344 },
    { id: 55, nome: 'Manto do fascínio', preco: 4500, livro: 'Tormenta20', pagina: 344 },
    { id: 56, nome: 'Pingente da sensatez', preco: 4500, livro: 'Tormenta20', pagina: 345 },
    { id: 57, nome: 'Pingente da sensatez', preco: 4500, livro: 'Tormenta20', pagina: 345 },
    { id: 58, nome: 'Pingente da sensatez', preco: 4500, livro: 'Tormenta20', pagina: 345 },
    { id: 59, nome: 'Pingente da sensatez', preco: 4500, livro: 'Tormenta20', pagina: 345 },
    { id: 60, nome: 'Pingente da sensatez', preco: 4500, livro: 'Tormenta20', pagina: 345 },
    { id: 61, nome: 'Torque do vigor', preco: 4500, livro: 'Tormenta20', pagina: 345 },
    { id: 62, nome: 'Torque do vigor', preco: 4500, livro: 'Tormenta20', pagina: 345 },
    { id: 63, nome: 'Torque do vigor', preco: 4500, livro: 'Tormenta20', pagina: 345 },
    { id: 64, nome: 'Torque do vigor', preco: 4500, livro: 'Tormenta20', pagina: 345 },
    { id: 65, nome: 'Torque do vigor', preco: 4500, livro: 'Tormenta20', pagina: 345 },
    { id: 66, nome: 'Monóculo da franqueza', preco: 4500, livro: 'Heróis de Arton', pagina: 266 },
    { id: 67, nome: 'Chapéu do disfarce', preco: 6000, livro: 'Tormenta20', pagina: 343 },
    { id: 68, nome: 'Chapéu do disfarce', preco: 6000, livro: 'Tormenta20', pagina: 343 },
    { id: 69, nome: 'Flauta fantasma', preco: 6000, livro: 'Tormenta20', pagina: 344 },
    { id: 70, nome: 'Lanterna da revelação', preco: 6000, livro: 'Tormenta20', pagina: 344 },
    { id: 71, nome: 'Lanterna da revelação', preco: 6000, livro: 'Tormenta20', pagina: 344 },
    { id: 72, nome: 'Algibeira provedora', preco: 6000, livro: 'Heróis de Arton', pagina: 263 },
    { id: 73, nome: 'Algibeira provedora', preco: 6000, livro: 'Heróis de Arton', pagina: 263 },
    { id: 74, nome: 'Gaiola dos arcanos', preco: 6000, livro: 'Heróis de Arton', pagina: 266 },
    { id: 75, nome: 'Gaiola dos arcanos', preco: 6000, livro: 'Heróis de Arton', pagina: 266 },
    { id: 76, nome: 'Lâmpada da ilusão impecável', preco: 6000, livro: 'Heróis de Arton', pagina: 266 },
    { id: 77, nome: 'Lâmpada da ilusão impecável', preco: 6000, livro: 'Heróis de Arton', pagina: 266 },
    { id: 78, nome: 'Pena da criação', preco: 6000, livro: 'Heróis de Arton', pagina: 267 },
    { id: 79, nome: 'Pena da criação', preco: 6000, livro: 'Heróis de Arton', pagina: 267 },
    { id: 80, nome: 'Corda da resignação', preco: 7500, livro: 'Heróis de Arton', pagina: 265 },
    { id: 81, nome: 'Corda da resignação', preco: 7500, livro: 'Heróis de Arton', pagina: 265 },
    { id: 82, nome: 'Anel da proteção', preco: 9000, livro: 'Tormenta20', pagina: 342 },
    { id: 83, nome: 'Anel da proteção', preco: 9000, livro: 'Tormenta20', pagina: 342 },
    { id: 84, nome: 'Anel da proteção', preco: 9000, livro: 'Tormenta20', pagina: 342 },
    { id: 85, nome: 'Anel da proteção', preco: 9000, livro: 'Tormenta20', pagina: 342 },
    { id: 86, nome: 'Anel da proteção', preco: 9000, livro: 'Tormenta20', pagina: 342 },
    { id: 87, nome: 'Anel do escudo mental', preco: 9000, livro: 'Tormenta20', pagina: 342 },
    { id: 88, nome: 'Pingente da saúde', preco: 9000, livro: 'Tormenta20', pagina: 345 },
    { id: 89, nome: 'Coroa de flores', preco: 9000, livro: 'Deuses de Arton', pagina: 55 },
    { id: 90, nome: 'Jarro das profundezas', preco: 9000, livro: 'Deuses de Arton', pagina: 58 },
    { id: 91, nome: 'Escrivaninha consagrada', preco: 9000, livro: 'Deuses de Arton', pagina: 58 },
    { id: 92, nome: 'Anel da proteção mental', preco: 9000, livro: 'Heróis de Arton', pagina: 263 },
    { id: 93, nome: 'Berço das fadas', preco: 9000, livro: 'Heróis de Arton', pagina: 263 },
    { id: 94, nome: 'Chapéu dos truques infinitos', preco: 9000, livro: 'Heróis de Arton', pagina: 264 },
    { id: 95, nome: 'Cinto da leveza graciosa', preco: 9000, livro: 'Heróis de Arton', pagina: 264 },
    { id: 96, nome: 'Cristal da voz silenciosa', preco: 9000, livro: 'Heróis de Arton', pagina: 265 },
    { id: 97, nome: 'Cristal do tempo célere', preco: 9000, livro: 'Heróis de Arton', pagina: 265 },
    { id: 98, nome: 'Ocarina da melodia distante', preco: 9000, livro: 'Heróis de Arton', pagina: 266 },
    { id: 99, nome: 'Olhos do corvo', preco: 9000, livro: 'Heróis de Arton', pagina: 266 },
    { id: 100, nome: 'Pergaminho da verdade cósmica', preco: 9000, livro: 'Heróis de Arton', pagina: 267 },
  ];

  acessorioMedio = [
    { id: 1, nome: 'Anel de telecinesia', preco: 10500, livro: 'Tormenta20', pagina: 342 },
    { id: 2, nome: 'Bola de cristal', preco: 10500, livro: 'Tormenta20', pagina: 342 },
    { id: 3, nome: 'Caveira maldita', preco: 10500, livro: 'Tormenta20', pagina: 343 },
    { id: 4, nome: 'Instrumento da alegria', preco: 10500, livro: 'Deuses de Arton', pagina: 57 },
    { id: 5, nome: 'Ampulheta da harmonia temporal', preco: 10500, livro: 'Heróis de Arton', pagina: 263 },
    { id: 6, nome: 'Amuleto do amparo', preco: 10500, livro: 'Heróis de Arton', pagina: 263 },
    { id: 7, nome: 'Caixa dos ecos perdidos', preco: 10500, livro: 'Heróis de Arton', pagina: 264 },
    { id: 8, nome: 'Colar da perseverança', preco: 10500, livro: 'Heróis de Arton', pagina: 264 },
    { id: 9, nome: 'Colar do tirano', preco: 10500, livro: 'Heróis de Arton', pagina: 265 },
    { id: 10, nome: 'Óculos da revelação', preco: 10500, livro: 'Heróis de Arton', pagina: 266 },
    { id: 11, nome: 'Colar das bolas de fogo', preco: 12000, livro: 'Heróis de Arton', pagina: 265 },
    { id: 12, nome: 'Sandálias de Valkaria', preco: 12000, livro: 'Heróis de Arton', pagina: 267 },
    { id: 13, nome: 'Véu diáfano', preco: 13500, livro: 'Deuses de Arton', pagina: 57 },
    { id: 14, nome: 'Botas aladas', preco: 15000, livro: 'Tormenta20', pagina: 342 },
    { id: 15, nome: 'Botas inquietas', preco: 15000, livro: 'Deuses de Arton', pagina: 59 },
    { id: 16, nome: 'Pira póstera', preco: 15000, livro: 'Deuses de Arton', pagina: 59 },
    { id: 17, nome: 'Anel do pacto oneroso', preco: 15000, livro: 'Heróis de Arton', pagina: 263 },
    { id: 18, nome: 'Botas do andarilho das sombras', preco: 15000, livro: 'Heróis de Arton', pagina: 263 },
    { id: 19, nome: 'Cálice das marés', preco: 15000, livro: 'Heróis de Arton', pagina: 264 },
    { id: 20, nome: 'Cinto dos caminhos cruzados', preco: 15000, livro: 'Heróis de Arton', pagina: 264 },
    { id: 21, nome: 'Pedra da passagem', preco: 15000, livro: 'Heróis de Arton', pagina: 267 },
    { id: 22, nome: 'Pingente da dor partilhada', preco: 15000, livro: 'Heróis de Arton', pagina: 267 },
    { id: 23, nome: 'Braceletes de bronze', preco: 16500, livro: 'Tormenta20', pagina: 342 },
    { id: 24, nome: 'Braceletes de bronze', preco: 16500, livro: 'Tormenta20', pagina: 342 },
    { id: 25, nome: 'Braceletes de bronze', preco: 16500, livro: 'Tormenta20', pagina: 342 },
    { id: 26, nome: 'Braceletes de bronze', preco: 16500, livro: 'Tormenta20', pagina: 342 },
    { id: 27, nome: 'Capa nebulosa', preco: 16500, livro: 'Heróis de Arton', pagina: 264 },
    { id: 28, nome: 'Espelho do outro lado', preco: 18000, livro: 'Heróis de Arton', pagina: 265 },
    { id: 29, nome: 'Gema da purificação', preco: 18000, livro: 'Heróis de Arton', pagina: 266 },
    { id: 30, nome: 'Gema da purificação', preco: 18000, livro: 'Heróis de Arton', pagina: 266 },
    { id: 31, nome: 'Máscara da raposa', preco: 18000, livro: 'Heróis de Arton', pagina: 266 },
    { id: 32, nome: 'Máscara da raposa', preco: 18000, livro: 'Heróis de Arton', pagina: 266 },
    { id: 33, nome: 'Anel da energia', preco: 21000, livro: 'Tormenta20', pagina: 342 },
    { id: 34, nome: 'Anel da energia', preco: 21000, livro: 'Tormenta20', pagina: 342 },
    { id: 35, nome: 'Anel da energia', preco: 21000, livro: 'Tormenta20', pagina: 342 },
    { id: 36, nome: 'Anel da energia', preco: 21000, livro: 'Tormenta20', pagina: 342 },
    { id: 37, nome: 'Anel da vitalidade', preco: 21000, livro: 'Tormenta20', pagina: 342 },
    { id: 38, nome: 'Anel da vitalidade', preco: 21000, livro: 'Tormenta20', pagina: 342 },
    { id: 39, nome: 'Anel da vitalidade', preco: 21000, livro: 'Tormenta20', pagina: 342 },
    { id: 40, nome: 'Anel da vitalidade', preco: 21000, livro: 'Tormenta20', pagina: 342 },
    { id: 41, nome: 'Anel de invisibilidade', preco: 21000, livro: 'Tormenta20', pagina: 342 },
    { id: 42, nome: 'Anel de invisibilidade', preco: 21000, livro: 'Tormenta20', pagina: 342 },
    { id: 43, nome: 'Braçadeiras do arqueiro', preco: 21000, livro: 'Tormenta20', pagina: 342 },
    { id: 44, nome: 'Braçadeiras do arqueiro', preco: 21000, livro: 'Tormenta20', pagina: 342 },
    { id: 45, nome: 'Brincos de Marah', preco: 21000, livro: 'Tormenta20', pagina: 343 },
    { id: 46, nome: 'Brincos de Marah', preco: 21000, livro: 'Tormenta20', pagina: 343 },
    { id: 47, nome: 'Faixas do pugilista', preco: 21000, livro: 'Tormenta20', pagina: 344 },
    { id: 48, nome: 'Faixas do pugilista', preco: 21000, livro: 'Tormenta20', pagina: 344 },
    { id: 49, nome: 'Manto da aranha', preco: 21000, livro: 'Tormenta20', pagina: 344 },
    { id: 50, nome: 'Manto da aranha', preco: 21000, livro: 'Tormenta20', pagina: 344 },
    { id: 51, nome: 'Vassoura voadora', preco: 21000, livro: 'Tormenta20', pagina: 345 },
    { id: 52, nome: 'Vassoura voadora', preco: 21000, livro: 'Tormenta20', pagina: 345 },
    { id: 53, nome: 'Símbolo abençoado', preco: 21000, livro: 'Tormenta20', pagina: 345 },
    { id: 54, nome: 'Símbolo abençoado', preco: 21000, livro: 'Tormenta20', pagina: 345 },
    { id: 55, nome: 'Colar de presas', preco: 21000, livro: 'Deuses de Arton', pagina: 57 },
    { id: 56, nome: 'Vestido noturno', preco: 21000, livro: 'Deuses de Arton', pagina: 58 },
    { id: 57, nome: 'Anel da beleza ilusória', preco: 21000, livro: 'Heróis de Arton', pagina: 263 },
    { id: 58, nome: 'Bastão do sonhador', preco: 21000, livro: 'Heróis de Arton', pagina: 263 },
    { id: 59, nome: 'Colar da fúria monstruosa', preco: 21000, livro: 'Heróis de Arton', pagina: 264 },
    { id: 60, nome: 'Coroa da floresta sussurrante', preco: 21000, livro: 'Heróis de Arton', pagina: 265 },
    { id: 61, nome: 'Espelho da verdade', preco: 21000, livro: 'Heróis de Arton', pagina: 265 },
    { id: 62, nome: 'Instrumentos da celeridade', preco: 22500, livro: 'Heróis de Arton', pagina: 266 },
    { id: 63, nome: 'Máscara do predador', preco: 22500, livro: 'Heróis de Arton', pagina: 266 },
    { id: 64, nome: 'Frigideira do chef anão', preco: 24000, livro: 'Heróis de Arton', pagina: 266 },
    { id: 65, nome: 'Frigideira do chef anão', preco: 24000, livro: 'Heróis de Arton', pagina: 266 },
    { id: 66, nome: 'Gema da santificação', preco: 24000, livro: 'Heróis de Arton', pagina: 266 },
    { id: 67, nome: 'Cubo armadilha', preco: 25000, livro: 'Deuses de Arton', pagina: 56 },
    { id: 68, nome: 'Caldeirão da vida', preco: 25000, livro: 'Deuses de Arton', pagina: 57 },
    { id: 69, nome: 'Amuleto da robustez', preco: 25500, livro: 'Tormenta20', pagina: 342 },
    { id: 70, nome: 'Amuleto da robustez', preco: 25500, livro: 'Tormenta20', pagina: 342 },
    { id: 71, nome: 'Amuleto da robustez', preco: 25500, livro: 'Tormenta20', pagina: 342 },
    { id: 72, nome: 'Amuleto da robustez', preco: 25500, livro: 'Tormenta20', pagina: 342 },
    { id: 73, nome: 'Botas velozes', preco: 25500, livro: 'Tormenta20', pagina: 342 },
    { id: 74, nome: 'Botas velozes', preco: 25500, livro: 'Tormenta20', pagina: 342 },
    { id: 75, nome: 'Cinto da força do gigante', preco: 25500, livro: 'Tormenta20', pagina: 343 },
    { id: 76, nome: 'Cinto da força do gigante', preco: 25500, livro: 'Tormenta20', pagina: 343 },
    { id: 77, nome: 'Cinto da força do gigante', preco: 25500, livro: 'Tormenta20', pagina: 343 },
    { id: 78, nome: 'Cinto da força do gigante', preco: 25500, livro: 'Tormenta20', pagina: 343 },
    { id: 79, nome: 'Coroa majestosa', preco: 25500, livro: 'Tormenta20', pagina: 344 },
    { id: 80, nome: 'Coroa majestosa', preco: 25500, livro: 'Tormenta20', pagina: 344 },
    { id: 81, nome: 'Coroa majestosa', preco: 25500, livro: 'Tormenta20', pagina: 344 },
    { id: 82, nome: 'Coroa majestosa', preco: 25500, livro: 'Tormenta20', pagina: 344 },
    { id: 83, nome: 'Estola da serenidade', preco: 25500, livro: 'Tormenta20', pagina: 344 },
    { id: 84, nome: 'Estola da serenidade', preco: 25500, livro: 'Tormenta20', pagina: 344 },
    { id: 85, nome: 'Estola da serenidade', preco: 25500, livro: 'Tormenta20', pagina: 344 },
    { id: 86, nome: 'Estola da serenidade', preco: 25500, livro: 'Tormenta20', pagina: 344 },
    { id: 87, nome: 'Manto do morcego', preco: 25500, livro: 'Tormenta20', pagina: 344 },
    { id: 88, nome: 'Pulseiras da celeridade', preco: 25500, livro: 'Tormenta20', pagina: 345 },
    { id: 89, nome: 'Pulseiras da celeridade', preco: 25500, livro: 'Tormenta20', pagina: 345 },
    { id: 90, nome: 'Pulseiras da celeridade', preco: 25500, livro: 'Tormenta20', pagina: 345 },
    { id: 91, nome: 'Pulseiras da celeridade', preco: 25500, livro: 'Tormenta20', pagina: 345 },
    { id: 92, nome: 'Tiara da sapiência', preco: 25500, livro: 'Tormenta20', pagina: 345 },
    { id: 93, nome: 'Tiara da sapiência', preco: 25500, livro: 'Tormenta20', pagina: 345 },
    { id: 94, nome: 'Tiara da sapiência', preco: 25500, livro: 'Tormenta20', pagina: 345 },
    { id: 95, nome: 'Tiara da sapiência', preco: 25500, livro: 'Tormenta20', pagina: 345 },
    { id: 96, nome: 'Argolas místicas', preco: 25500, livro: 'Deuses de Arton', pagina: 59 },
    { id: 97, nome: 'Argolas místicas', preco: 25500, livro: 'Deuses de Arton', pagina: 59 },
    { id: 98, nome: 'Bastão da grande harmonia', preco: 25500, livro: 'Heróis de Arton', pagina: 263 },
    { id: 99, nome: 'Coroa da majestade distorcida', preco: 25500, livro: 'Heróis de Arton', pagina: 265 },
    { id: 100, nome: 'Bracelete do coração vivaz', preco: 27000, livro: 'Heróis de Arton', pagina: 264 },
  ];

  acessorioMaior = [
    { id: 1, nome: 'Elmo do teletransporte', preco: 30000, livro: 'Tormenta20', pagina: 344 },
    { id: 2, nome: 'Elmo do teletransporte', preco: 30000, livro: 'Tormenta20', pagina: 344 },
    { id: 3, nome: 'Gema da telepatia', preco: 30000, livro: 'Tormenta20', pagina: 344 },
    { id: 4, nome: 'Gema da telepatia', preco: 30000, livro: 'Tormenta20', pagina: 344 },
    { id: 5, nome: 'Gema elemental', preco: 30000, livro: 'Tormenta20', pagina: 344 },
    { id: 6, nome: 'Gema elemental', preco: 30000, livro: 'Tormenta20', pagina: 344 },
    { id: 7, nome: 'Manual da saúde corporal', preco: 30000, livro: 'Tormenta20', pagina: 345 },
    { id: 8, nome: 'Manual da saúde corporal', preco: 30000, livro: 'Tormenta20', pagina: 345 },
    { id: 9, nome: 'Manual da saúde corporal', preco: 30000, livro: 'Tormenta20', pagina: 345 },
    { id: 10, nome: 'Manual da saúde corporal', preco: 30000, livro: 'Tormenta20', pagina: 345 },
    { id: 11, nome: 'Manual da saúde corporal', preco: 30000, livro: 'Tormenta20', pagina: 345 },
    { id: 12, nome: 'Manual do bom exercício', preco: 30000, livro: 'Tormenta20', pagina: 345 },
    { id: 13, nome: 'Manual do bom exercício', preco: 30000, livro: 'Tormenta20', pagina: 345 },
    { id: 14, nome: 'Manual do bom exercício', preco: 30000, livro: 'Tormenta20', pagina: 345 },
    { id: 15, nome: 'Manual do bom exercício', preco: 30000, livro: 'Tormenta20', pagina: 345 },
    { id: 16, nome: 'Manual do bom exercício', preco: 30000, livro: 'Tormenta20', pagina: 345 },
    { id: 17, nome: 'Manual dos movimentos precisos', preco: 30000, livro: 'Tormenta20', pagina: 345 },
    { id: 18, nome: 'Manual dos movimentos precisos', preco: 30000, livro: 'Tormenta20', pagina: 345 },
    { id: 19, nome: 'Manual dos movimentos precisos', preco: 30000, livro: 'Tormenta20', pagina: 345 },
    { id: 20, nome: 'Manual dos movimentos precisos', preco: 30000, livro: 'Tormenta20', pagina: 345 },
    { id: 21, nome: 'Manual dos movimentos precisos', preco: 30000, livro: 'Tormenta20', pagina: 345 },
    { id: 22, nome: 'Medalhão de Lena', preco: 30000, livro: 'Tormenta20', pagina: 345 },
    { id: 23, nome: 'Medalhão de Lena', preco: 30000, livro: 'Tormenta20', pagina: 345 },
    { id: 24, nome: 'Medalhão de Lena', preco: 30000, livro: 'Tormenta20', pagina: 345 },
    { id: 25, nome: 'Medalhão de Lena', preco: 30000, livro: 'Tormenta20', pagina: 345 },
    { id: 26, nome: 'Medalhão de Lena', preco: 30000, livro: 'Tormenta20', pagina: 345 },
    { id: 27, nome: 'Tomo da compreensão', preco: 30000, livro: 'Tormenta20', pagina: 345 },
    { id: 28, nome: 'Tomo da compreensão', preco: 30000, livro: 'Tormenta20', pagina: 345 },
    { id: 29, nome: 'Tomo da compreensão', preco: 30000, livro: 'Tormenta20', pagina: 345 },
    { id: 30, nome: 'Tomo da compreensão', preco: 30000, livro: 'Tormenta20', pagina: 345 },
    { id: 31, nome: 'Tomo da compreensão', preco: 30000, livro: 'Tormenta20', pagina: 345 },
    { id: 32, nome: 'Tomo da liderança e influência', preco: 30000, livro: 'Tormenta20', pagina: 345 },
    { id: 33, nome: 'Tomo da liderança e influência', preco: 30000, livro: 'Tormenta20', pagina: 345 },
    { id: 34, nome: 'Tomo da liderança e influência', preco: 30000, livro: 'Tormenta20', pagina: 345 },
    { id: 35, nome: 'Tomo da liderança e influência', preco: 30000, livro: 'Tormenta20', pagina: 345 },
    { id: 36, nome: 'Tomo da liderança e influência', preco: 30000, livro: 'Tormenta20', pagina: 345 },
    { id: 37, nome: 'Tomo dos grandes pensamentos', preco: 30000, livro: 'Tormenta20', pagina: 345 },
    { id: 38, nome: 'Tomo dos grandes pensamentos', preco: 30000, livro: 'Tormenta20', pagina: 345 },
    { id: 39, nome: 'Tomo dos grandes pensamentos', preco: 30000, livro: 'Tormenta20', pagina: 345 },
    { id: 40, nome: 'Tomo dos grandes pensamentos', preco: 30000, livro: 'Tormenta20', pagina: 345 },
    { id: 41, nome: 'Tomo dos grandes pensamentos', preco: 30000, livro: 'Tormenta20', pagina: 345 },
    { id: 42, nome: 'Anel da chama dançante', preco: 30000, livro: 'Heróis de Arton', pagina: 263 },
    { id: 43, nome: 'Anel da chama dançante', preco: 30000, livro: 'Heróis de Arton', pagina: 263 },
    { id: 44, nome: 'Anel da chama dançante', preco: 30000, livro: 'Heróis de Arton', pagina: 263 },
    { id: 45, nome: 'Chapéu pensador', preco: 30000, livro: 'Heróis de Arton', pagina: 264 },
    { id: 46, nome: 'Chapéu pensador', preco: 30000, livro: 'Heróis de Arton', pagina: 264 },
    { id: 47, nome: 'Cinto da flecha veloz', preco: 30000, livro: 'Heróis de Arton', pagina: 264 },
    { id: 48, nome: 'Cinto da flecha veloz', preco: 30000, livro: 'Heróis de Arton', pagina: 264 },
    { id: 49, nome: 'Gema da profanação', preco: 30000, livro: 'Heróis de Arton', pagina: 266 },
    { id: 50, nome: 'Gema da profanação', preco: 30000, livro: 'Heróis de Arton', pagina: 266 },
    { id: 51, nome: 'Tomo da técnica definitiva', preco: 30000, livro: 'Heróis de Arton', pagina: 267 },
    { id: 52, nome: 'Tomo da técnica definitiva', preco: 30000, livro: 'Heróis de Arton', pagina: 267 },
    { id: 53, nome: 'Tomo da técnica definitiva', preco: 30000, livro: 'Heróis de Arton', pagina: 267 },
    { id: 54, nome: 'Tapeçaria da guerra', preco: 35000, livro: 'Deuses de Arton', pagina: 55 },
    { id: 55, nome: 'Tapeçaria da guerra', preco: 35000, livro: 'Deuses de Arton', pagina: 55 },
    { id: 56, nome: 'Braceletes da amizade intensa', preco: 36000, livro: 'Heróis de Arton', pagina: 264 },
    { id: 57, nome: 'Braceletes da amizade intensa', preco: 36000, livro: 'Heróis de Arton', pagina: 264 },
    { id: 58, nome: 'Cilício vivo', preco: 37000, livro: 'Deuses de Arton', pagina: 55 },
    { id: 59, nome: 'Coração corrompido', preco: 45000, livro: 'Deuses de Arton', pagina: 55 },
    { id: 60, nome: 'Coração do inverno', preco: 45000, livro: 'Heróis de Arton', pagina: 265 },
    { id: 61, nome: 'Coração do inverno', preco: 45000, livro: 'Heróis de Arton', pagina: 265 },
    { id: 62, nome: 'Tomo dos companheiros', preco: 45000, livro: 'Heróis de Arton', pagina: 267 },
    { id: 63, nome: 'Tomo dos companheiros', preco: 45000, livro: 'Heróis de Arton', pagina: 267 },
    { id: 64, nome: 'Anel refletor', preco: 51000, livro: 'Tormenta20', pagina: 342 },
    { id: 65, nome: 'Anel refletor', preco: 51000, livro: 'Tormenta20', pagina: 342 },
    { id: 66, nome: 'Cinto do campeão', preco: 51000, livro: 'Tormenta20', pagina: 343 },
    { id: 67, nome: 'Cinto do campeão', preco: 51000, livro: 'Tormenta20', pagina: 343 },
    { id: 68, nome: 'Colar guardião', preco: 51000, livro: 'Tormenta20', pagina: 343 },
    { id: 69, nome: 'Colar guardião', preco: 51000, livro: 'Tormenta20', pagina: 343 },
    { id: 70, nome: 'Colar guardião', preco: 51000, livro: 'Tormenta20', pagina: 343 },
    { id: 71, nome: 'Colar guardião', preco: 51000, livro: 'Tormenta20', pagina: 343 },
    { id: 72, nome: 'Estatueta animista', preco: 51000, livro: 'Tormenta20', pagina: 344 },
    { id: 73, nome: 'Estatueta animista', preco: 51000, livro: 'Tormenta20', pagina: 344 },
    { id: 74, nome: 'Anel da liberdade', preco: 60000, livro: 'Tormenta20', pagina: 342 },
    { id: 75, nome: 'Anel da liberdade', preco: 60000, livro: 'Tormenta20', pagina: 342 },
    { id: 76, nome: 'Tapete voador', preco: 60000, livro: 'Tormenta20', pagina: 345 },
    { id: 77, nome: 'Tapete voador', preco: 60000, livro: 'Tormenta20', pagina: 345 },
    { id: 78, nome: 'Chave dos planos', preco: 60000, livro: 'Heróis de Arton', pagina: 264 },
    { id: 79, nome: 'Chave dos planos', preco: 60000, livro: 'Heróis de Arton', pagina: 264 },
    { id: 80, nome: 'Cinto da desmaterialização', preco: 60000, livro: 'Heróis de Arton', pagina: 264 },
    { id: 81, nome: 'Cinto da desmaterialização', preco: 60000, livro: 'Heróis de Arton', pagina: 264 },
    { id: 82, nome: 'Braceletes de ouro', preco: 64500, livro: 'Tormenta20', pagina: 342 },
    { id: 83, nome: 'Braceletes de ouro', preco: 64500, livro: 'Tormenta20', pagina: 342 },
    { id: 84, nome: 'Braceletes de ouro', preco: 64500, livro: 'Tormenta20', pagina: 342 },
    { id: 85, nome: 'Braceletes de ouro', preco: 64500, livro: 'Tormenta20', pagina: 342 },
    { id: 86, nome: 'Espelho da oposição', preco: 75000, livro: 'Tormenta20', pagina: 344 },
    { id: 87, nome: 'Espelho da oposição', preco: 75000, livro: 'Tormenta20', pagina: 344 },
    { id: 88, nome: 'Robe do arquimago', preco: 90000, livro: 'Tormenta20', pagina: 345 },
    { id: 89, nome: 'Robe do arquimago', preco: 90000, livro: 'Tormenta20', pagina: 345 },
    { id: 90, nome: 'Robe do arquimago', preco: 90000, livro: 'Tormenta20', pagina: 345 },
    { id: 91, nome: 'Robe do arquimago', preco: 90000, livro: 'Tormenta20', pagina: 345 },
    { id: 92, nome: 'Ossos dracônicos', preco: 90000, livro: 'Deuses de Arton', pagina: 56 },
    { id: 93, nome: 'Ossos dracônicos', preco: 90000, livro: 'Deuses de Arton', pagina: 56 },
    { id: 94, nome: 'Orbe das tempestades', preco: 97500, livro: 'Tormenta20', pagina: 345 },
    { id: 95, nome: 'Orbe das tempestades', preco: 97500, livro: 'Tormenta20', pagina: 345 },
    { id: 96, nome: 'Braçadeiras da força do colosso', preco: 120000, livro: 'Heróis de Arton', pagina: 264 },
    { id: 97, nome: 'Braçadeiras da força do colosso', preco: 120000, livro: 'Heróis de Arton', pagina: 264 },
    { id: 98, nome: 'Anel da regeneração', preco: 150000, livro: 'Tormenta20', pagina: 342 },
    { id: 99, nome: 'Anel da regeneração', preco: 150000, livro: 'Tormenta20', pagina: 342 },
    { id: 100, nome: 'Espelho do aprisionamento', preco: 150000, livro: 'Tormenta20', pagina: 344 },
  ];
}
