// models.ts
export type TreasureContext = {
  type: string;
  level: number;
  notes?: string;
  random?: number;
};

export type GeneratedTreasure = {
  items: any[];
  return: string;
  notes?: string;
  report?: string;
};

export const tabelaTesouroItens = [
  { nd: 0.25, min: 1, max: 50, faixa: '01-50', valor: '—', modificador: '', tipo: '' },
  { nd: 0.25, min: 51, max: 75, faixa: '51-75', valor: 'Item diverso', modificador: '', tipo: 'miscellaneous-item' },
  { nd: 0.25, min: 76, max: 100, faixa: '76-100', valor: 'Equipamento', modificador: '', tipo: 'equipment' },
  { nd: 0.5, min: 1, max: 45, faixa: '01-45', valor: '—', modificador: '', tipo: '' },
  { nd: 0.5, min: 46, max: 70, faixa: '46-70', valor: 'Item diverso', modificador: '', tipo: 'miscellaneous-item' },
  { nd: 0.5, min: 71, max: 100, faixa: '71-100', valor: 'Equipamento', modificador: '', tipo: 'equipment' },
  { nd: 1, min: 1, max: 40, faixa: '01-40', valor: '—', modificador: '', tipo: '' },
  { nd: 1, min: 41, max: 65, faixa: '41-65', valor: 'Item diverso', modificador: '', tipo: 'miscellaneous-item' },
  { nd: 1, min: 66, max: 90, faixa: '66-90', valor: 'Equipamento', modificador: '', tipo: 'equipment' },
  { nd: 1, min: 91, max: 100, faixa: '91-100', valor: '1 poção', modificador: '', tipo: 'potion' },
  { nd: 2, min: 1, max: 30, faixa: '01-30', valor: '—', modificador: '', tipo: '' },
  { nd: 2, min: 31, max: 40, faixa: '31-40', valor: 'Item diverso', modificador: '', tipo: 'miscellaneous-item' },
  { nd: 2, min: 41, max: 70, faixa: '41-70', valor: 'Equipamento', modificador: '', tipo: 'equipment' },
  { nd: 2, min: 71, max: 90, faixa: '71-90', valor: '1 poção', modificador: '', tipo: 'potion' },
  {
    nd: 2,
    min: 91,
    max: 100,
    faixa: '91-100',
    valor: 'Superior (1 melhoria)',
    modificador: '(1 melhoria)',
    tipo: 'equipment',
  },
  { nd: 3, min: 1, max: 25, faixa: '01-25', valor: '—', modificador: '', tipo: '' },
  { nd: 3, min: 26, max: 35, faixa: '26-35', valor: 'Item diverso', modificador: '', tipo: 'miscellaneous-item' },
  { nd: 3, min: 36, max: 60, faixa: '36-60', valor: 'Equipamento', modificador: '', tipo: 'equipment' },
  { nd: 3, min: 61, max: 85, faixa: '61-85', valor: '1 poção', modificador: '', tipo: 'potion' },
  {
    nd: 3,
    min: 86,
    max: 100,
    faixa: '91-100',
    valor: 'Superior (1 melhoria)',
    modificador: '(1 melhoria)',
    tipo: 'equipment',
  },
  { nd: 4, min: 1, max: 20, faixa: '01-20', valor: '—', modificador: '', tipo: '' },
  { nd: 4, min: 21, max: 30, faixa: '21-30', valor: 'Item diverso', modificador: '', tipo: 'miscellaneous-item' },
  { nd: 4, min: 31, max: 55, faixa: '31-55', valor: 'Equipamento 2D', modificador: '2D', tipo: 'equipment' },
  { nd: 4, min: 56, max: 80, faixa: '56-80', valor: '1 poção +%', modificador: '+%', tipo: 'potion' },
  {
    nd: 4,
    min: 81,
    max: 100,
    faixa: '81-100',
    valor: 'Superior (1 melhoria) 2D',
    modificador: '(1 melhoria) 2D',
    tipo: 'equipment',
  },
  { nd: 5, min: 1, max: 20, faixa: '01-20', valor: '—', modificador: '', tipo: '' },
  { nd: 5, min: 21, max: 70, faixa: '21-70', valor: '1 poção', modificador: '', tipo: 'potion' },
  {
    nd: 5,
    min: 71,
    max: 90,
    faixa: '71-90',
    valor: 'Superior (1 melhoria)',
    modificador: '(1 melhoria)',
    tipo: 'equipment',
  },
  {
    nd: 5,
    min: 91,
    max: 100,
    faixa: '91-100',
    valor: 'Superior (2 melhorias)',
    modificador: '(2 melhorias)',
    tipo: 'equipment',
  },
  { nd: 6, min: 1, max: 20, faixa: '01-20', valor: '—', modificador: '', tipo: '' },
  { nd: 6, min: 21, max: 65, faixa: '21-65', valor: '1 poção +%', modificador: '+%', tipo: 'potion' },
  {
    nd: 6,
    min: 66,
    max: 95,
    faixa: '66-95',
    valor: 'Superior (1 melhoria)',
    modificador: '(1 melhoria)',
    tipo: 'equipment',
  },
  {
    nd: 6,
    min: 96,
    max: 100,
    faixa: '96-100',
    valor: 'Superior (2 melhorias) 2D',
    modificador: '(2 melhorias) 2D',
    tipo: 'equipment',
  },
  { nd: 7, min: 1, max: 20, faixa: '01-20', valor: '—', modificador: '', tipo: '' },
  { nd: 7, min: 21, max: 60, faixa: '21-60', valor: '1d3 poções', modificador: '1d3', tipo: 'potion' },
  {
    nd: 7,
    min: 61,
    max: 90,
    faixa: '61-90',
    valor: 'Superior (2 melhorias)',
    modificador: '(2 melhorias)',
    tipo: 'equipment',
  },
  {
    nd: 7,
    min: 91,
    max: 100,
    faixa: '91-100',
    valor: 'Superior (3 melhorias)',
    modificador: '(3 melhorias)',
    tipo: 'equipment',
  },
  { nd: 8, min: 1, max: 20, faixa: '01-20', valor: '—', modificador: '', tipo: '' },
  { nd: 8, min: 21, max: 75, faixa: '21-75', valor: '1d3 poções', modificador: '1d3', tipo: 'potion' },
  {
    nd: 8,
    min: 76,
    max: 95,
    faixa: '76-95',
    valor: 'Superior (2 melhorias)',
    modificador: '(2 melhorias)',
    tipo: 'equipment',
  },
  {
    nd: 8,
    min: 96,
    max: 100,
    faixa: '96-100',
    valor: 'Superior (3 melhorias) 2D',
    modificador: '(3 melhorias) 2D',
    tipo: 'equipment',
  },
  { nd: 9, min: 1, max: 20, faixa: '01-20', valor: '—', modificador: '', tipo: '' },
  { nd: 9, min: 21, max: 70, faixa: '21-70', valor: '1 poção +%', modificador: '+%', tipo: 'potion' },
  {
    nd: 9,
    min: 71,
    max: 95,
    faixa: '71-95',
    valor: 'Superior (3 melhorias)',
    modificador: '(3 melhorias)',
    tipo: 'equipment',
  },
  {
    nd: 9,
    min: 96,
    max: 100,
    faixa: '96-100',
    valor: 'Mágico (menor)',
    modificador: '(menor)',
    tipo: 'magic-equipment',
  },
  { nd: 10, min: 1, max: 50, faixa: '01-50', valor: '—', modificador: '', tipo: '' },
  { nd: 10, min: 51, max: 75, faixa: '51-75', valor: '1d3+1 poções', modificador: '1d3', tipo: 'potion' },
  {
    nd: 10,
    min: 76,
    max: 90,
    faixa: '76-90',
    valor: 'Superior (3 melhorias)',
    modificador: '(3 melhorias)',
    tipo: 'equipment',
  },
  {
    nd: 10,
    min: 91,
    max: 100,
    faixa: '96-100',
    valor: 'Mágico (menor)',
    modificador: '(menor)',
    tipo: 'magic-equipment',
  },
  { nd: 11, min: 1, max: 45, faixa: '01-45', valor: '—', modificador: '', tipo: '' },
  { nd: 11, min: 46, max: 70, faixa: '46-70', valor: '1d4+1 poções', modificador: '1d4+1', tipo: 'potion' },
  {
    nd: 11,
    min: 71,
    max: 90,
    faixa: '71-90',
    valor: 'Superior (3 melhorias)',
    modificador: '(3 melhorias)',
    tipo: 'equipment',
  },
  {
    nd: 11,
    min: 91,
    max: 100,
    faixa: '91-100',
    valor: 'Mágico (menor) 2D',
    modificador: '(menor) 2D',
    tipo: 'magic-equipment',
  },
  { nd: 12, min: 1, max: 45, faixa: '01-45', valor: '—', modificador: '', tipo: '' },
  { nd: 12, min: 46, max: 70, faixa: '46-70', valor: '1d3+1 poções +%', modificador: '1d3+1 +%', tipo: 'potion' },
  {
    nd: 12,
    min: 71,
    max: 85,
    faixa: '71-85',
    valor: 'Superior (4 melhorias)',
    modificador: '(4 melhorias)',
    tipo: 'equipment',
  },
  {
    nd: 12,
    min: 86,
    max: 100,
    faixa: '86-100',
    valor: 'Mágico (menor)',
    modificador: '(menor)',
    tipo: 'magic-equipment',
  },
  { nd: 13, min: 1, max: 40, faixa: '01-40', valor: '—', modificador: '', tipo: '' },
  { nd: 13, min: 41, max: 65, faixa: '41-65', valor: '1d4+1 poções +%', modificador: '1d4+1 +%', tipo: 'potion' },
  {
    nd: 13,
    min: 66,
    max: 95,
    faixa: '66-95',
    valor: 'Superior (4 melhorias)',
    modificador: '(4 melhorias)',
    tipo: 'equipment',
  },
  {
    nd: 13,
    min: 96,
    max: 100,
    faixa: '96-100',
    valor: 'Mágico (médio)',
    modificador: '(médio)',
    tipo: 'magic-equipment',
  },
  { nd: 14, min: 1, max: 40, faixa: '01-40', valor: '—', modificador: '', tipo: '' },
  { nd: 14, min: 41, max: 65, faixa: '41-65', valor: '1d4+1 poções +%', modificador: '1d4+1 +%', tipo: 'potion' },
  {
    nd: 14,
    min: 66,
    max: 90,
    faixa: '66-90',
    valor: 'Superior (4 melhorias)',
    modificador: '(4 melhorias)',
    tipo: 'equipment',
  },
  {
    nd: 14,
    min: 91,
    max: 100,
    faixa: '91-100',
    valor: 'Mágico (médio)',
    modificador: '(médio)',
    tipo: 'magic-equipment',
  },
  { nd: 15, min: 1, max: 35, faixa: '01-35', valor: '—', modificador: '', tipo: '' },
  { nd: 15, min: 36, max: 45, faixa: '36-45', valor: '1d6+1 poções', modificador: '1d6+1', tipo: 'potion' },
  {
    nd: 15,
    min: 46,
    max: 85,
    faixa: '46-85',
    valor: 'Superior (4 melhorias) 2D',
    modificador: '(4 melhorias) 2D',
    tipo: 'equipment',
  },
  {
    nd: 15,
    min: 86,
    max: 100,
    faixa: '86-100',
    valor: 'Mágico (médio)',
    modificador: '(médio)',
    tipo: 'magic-equipment',
  },
  { nd: 16, min: 1, max: 35, faixa: '01-35', valor: '—', modificador: '', tipo: '' },
  { nd: 16, min: 36, max: 45, faixa: '36-45', valor: '1d6+1 poções +%', modificador: '1d6+1 +%', tipo: 'potion' },
  {
    nd: 16,
    min: 46,
    max: 85,
    faixa: '46-85',
    valor: 'Superior (4 melhorias) 2D',
    modificador: '(4 melhorias) 2D',
    tipo: 'equipment',
  },
  {
    nd: 16,
    min: 86,
    max: 100,
    faixa: '86-100',
    valor: 'Mágico (médio)',
    modificador: '(médio)',
    tipo: 'magic-equipment',
  },
  { nd: 17, min: 1, max: 20, faixa: '01-20', valor: '—', modificador: '', tipo: '' },
  {
    nd: 17,
    min: 21,
    max: 40,
    faixa: '21-40',
    valor: 'Mágico (menor)',
    modificador: '(menor)',
    tipo: 'magic-equipment',
  },
  {
    nd: 17,
    min: 41,
    max: 80,
    faixa: '46-80',
    valor: 'Mágico (médio)',
    modificador: '(médio)',
    tipo: 'magic-equipment',
  },
  {
    nd: 17,
    min: 81,
    max: 100,
    faixa: '81-100',
    valor: 'Mágico (maior)',
    modificador: '(maior)',
    tipo: 'magic-equipment',
  },
  { nd: 18, min: 1, max: 15, faixa: '01-15', valor: '—', modificador: '', tipo: '' },
  {
    nd: 18,
    min: 16,
    max: 40,
    faixa: '16-40',
    valor: 'Mágico (menor) 2D',
    modificador: '(menor) 2D',
    tipo: 'magic-equipment',
  },
  {
    nd: 18,
    min: 41,
    max: 70,
    faixa: '41-70',
    valor: 'Mágico (médio)',
    modificador: '(médio)',
    tipo: 'magic-equipment',
  },
  {
    nd: 18,
    min: 71,
    max: 100,
    faixa: '71-100',
    valor: 'Mágico (maior)',
    modificador: '(maior)',
    tipo: 'magic-equipment',
  },
  { nd: 19, min: 1, max: 10, faixa: '01-10', valor: '—', modificador: '', tipo: '' },
  {
    nd: 19,
    min: 11,
    max: 40,
    faixa: '11-40',
    valor: 'Mágico (menor) 2D',
    modificador: '(menor) 2D',
    tipo: 'magic-equipment',
  },
  {
    nd: 19,
    min: 41,
    max: 60,
    faixa: '41-60',
    valor: 'Mágico (médio) 2D',
    modificador: '(médio) 2D',
    tipo: 'magic-equipment',
  },
  {
    nd: 19,
    min: 61,
    max: 100,
    faixa: '61-100',
    valor: 'Mágico (maior)',
    modificador: '(maior)',
    tipo: 'magic-equipment',
  },
  { nd: 20, min: 1, max: 10, faixa: '01-05', valor: '—', modificador: '', tipo: '' },
  {
    nd: 20,
    min: 6,
    max: 40,
    faixa: '06-40',
    valor: 'Mágico (menor) 2D',
    modificador: '(menor) 2D',
    tipo: 'magic-equipment',
  },
  {
    nd: 20,
    min: 41,
    max: 60,
    faixa: '41-60',
    valor: 'Mágico (médio) 2D',
    modificador: '(médio) 2D',
    tipo: 'magic-equipment',
  },
  {
    nd: 20,
    min: 61,
    max: 100,
    faixa: '61-100',
    valor: 'Mágico (maior) 2D',
    modificador: '(maior) 2D',
    tipo: 'magic-equipment',
  },
];

export const tabelaDinheiro = [
  {
    nd: 0.25,
    min: 1,
    max: 30,
    faixa: '01-30',
    dinheiro: '—',
    multiplicador: 0,
    randomizador: 0,
    parcela: 0,
    potencializador: 0,
    unidade: '',
    modificador: '',
  },
  {
    nd: 0.25,
    min: 31,
    max: 70,
    faixa: '31-70',
    dinheiro: '1d6x10 TC',
    multiplicador: 1,
    randomizador: 6,
    parcela: 0,
    potencializador: 10,
    unidade: 'TC',
    modificador: '',
  },
  {
    nd: 0.25,
    min: 71,
    max: 95,
    faixa: '71-95',
    dinheiro: '1d4x100 TC',
    multiplicador: 1,
    randomizador: 4,
    parcela: 0,
    potencializador: 100,
    unidade: 'TC',
    modificador: '',
  },
  {
    nd: 0.25,
    min: 96,
    max: 100,
    faixa: '96-100',
    dinheiro: '1d6x10 T$',
    multiplicador: 1,
    randomizador: 6,
    parcela: 0,
    potencializador: 10,
    unidade: 'T$',
    modificador: '',
  },
  {
    nd: 0.5,
    min: 1,
    max: 25,
    faixa: '01-25',
    dinheiro: '—',
    multiplicador: 0,
    randomizador: 0,
    parcela: 0,
    potencializador: 0,
    unidade: '',
    modificador: '',
  },
  {
    nd: 0.5,
    min: 26,
    max: 70,
    faixa: '26-70',
    dinheiro: '2d6x10 TC',
    multiplicador: 2,
    randomizador: 6,
    parcela: 0,
    potencializador: 10,
    unidade: 'TC',
    modificador: '',
  },
  {
    nd: 0.5,
    min: 71,
    max: 95,
    faixa: '71-95',
    dinheiro: '2d8x10 T$',
    multiplicador: 2,
    randomizador: 8,
    parcela: 0,
    potencializador: 10,
    unidade: 'T$',
    modificador: '',
  },
  {
    nd: 0.5,
    min: 96,
    max: 100,
    faixa: '96-100',
    dinheiro: '1d4x100 T$',
    multiplicador: 1,
    randomizador: 4,
    parcela: 0,
    potencializador: 100,
    unidade: 'T$',
    modificador: '',
  },
  {
    nd: 1,
    min: 1,
    max: 20,
    faixa: '01-20',
    dinheiro: '—',
    multiplicador: 0,
    randomizador: 0,
    parcela: 0,
    potencializador: 0,
    unidade: '',
    modificador: '',
  },
  {
    nd: 1,
    min: 21,
    max: 70,
    faixa: '21-70',
    dinheiro: '3d8x10 T$',
    multiplicador: 3,
    randomizador: 8,
    parcela: 0,
    potencializador: 10,
    unidade: 'T$',
    modificador: '',
  },
  {
    nd: 1,
    min: 71,
    max: 95,
    faixa: '71-95',
    dinheiro: '4d12x10 T$',
    multiplicador: 4,
    randomizador: 12,
    parcela: 0,
    potencializador: 10,
    unidade: 'T$',
    modificador: '',
  },
  {
    nd: 1,
    min: 96,
    max: 100,
    faixa: '96-100',
    dinheiro: '1 riqueza menor',
    multiplicador: 1,
    randomizador: 1,
    parcela: 0,
    potencializador: 1,
    unidade: 'riqueza menor',
    modificador: '',
  },
  {
    nd: 2,
    min: 1,
    max: 15,
    faixa: '01-15',
    dinheiro: '—',
    multiplicador: 0,
    randomizador: 0,
    parcela: 0,
    potencializador: 0,
    unidade: '',
    modificador: '',
  },
  {
    nd: 2,
    min: 16,
    max: 55,
    faixa: '16-55',
    dinheiro: '3d10x10 T$',
    multiplicador: 3,
    randomizador: 10,
    parcela: 0,
    potencializador: 10,
    unidade: 'T$',
    modificador: '',
  },
  {
    nd: 2,
    min: 56,
    max: 85,
    faixa: '56-85',
    dinheiro: '2d4x100 T$',
    multiplicador: 2,
    randomizador: 4,
    parcela: 0,
    potencializador: 100,
    unidade: 'T$',
    modificador: '',
  },
  {
    nd: 2,
    min: 86,
    max: 95,
    faixa: '86-95',
    dinheiro: '2d6+1x100 T$',
    multiplicador: 2,
    randomizador: 6,
    parcela: 1,
    potencializador: 100,
    unidade: 'T$',
    modificador: '',
  },
  {
    nd: 2,
    min: 96,
    max: 100,
    faixa: '96-100',
    dinheiro: '1 riqueza menor',
    multiplicador: 1,
    randomizador: 1,
    parcela: 0,
    potencializador: 1,
    unidade: 'riqueza menor',
    modificador: '',
  },
  {
    nd: 3,
    min: 1,
    max: 10,
    faixa: '01-10',
    dinheiro: '—',
    multiplicador: 0,
    randomizador: 0,
    parcela: 0,
    potencializador: 0,
    unidade: '',
    modificador: '',
  },
  {
    nd: 3,
    min: 11,
    max: 20,
    faixa: '11-20',
    dinheiro: '4d12x10 T$',
    multiplicador: 4,
    randomizador: 12,
    parcela: 0,
    potencializador: 10,
    unidade: 'T$',
    modificador: '',
  },
  {
    nd: 3,
    min: 21,
    max: 60,
    faixa: '21-60',
    dinheiro: '1d4x100 T$',
    multiplicador: 1,
    randomizador: 4,
    parcela: 0,
    potencializador: 100,
    unidade: 'T$',
    modificador: '',
  },
  {
    nd: 3,
    min: 61,
    max: 90,
    faixa: '61-90',
    dinheiro: '1d8x10 TO',
    multiplicador: 1,
    randomizador: 8,
    parcela: 0,
    potencializador: 10,
    unidade: 'TO',
    modificador: '',
  },
  {
    nd: 3,
    min: 91,
    max: 100,
    faixa: '91-100',
    dinheiro: '1d3 riquezas menores',
    multiplicador: 1,
    randomizador: 3,
    parcela: 0,
    potencializador: 1,
    unidade: 'riqueza menor',
    modificador: '',
  },
  {
    nd: 4,
    min: 1,
    max: 10,
    faixa: '01-10',
    dinheiro: '—',
    multiplicador: 0,
    randomizador: 0,
    parcela: 0,
    potencializador: 0,
    unidade: '',
    modificador: '',
  },
  {
    nd: 4,
    min: 11,
    max: 50,
    faixa: '11-50',
    dinheiro: '1d6x100 T$',
    multiplicador: 1,
    randomizador: 6,
    parcela: 0,
    potencializador: 100,
    unidade: 'T$',
    modificador: '',
  },
  {
    nd: 4,
    min: 51,
    max: 80,
    faixa: '51-80',
    dinheiro: '1d12x100 T$',
    multiplicador: 1,
    randomizador: 12,
    parcela: 0,
    potencializador: 100,
    unidade: 'T$',
    modificador: '',
  },
  {
    nd: 4,
    min: 81,
    max: 90,
    faixa: '81-90',
    dinheiro: '1 riqueza menor +%',
    multiplicador: 1,
    randomizador: 1,
    parcela: 0,
    potencializador: 1,
    unidade: 'riqueza menor',
    modificador: '+%',
  },
  {
    nd: 4,
    min: 91,
    max: 100,
    faixa: '91-100',
    dinheiro: '1d3 riquezas menores +%',
    multiplicador: 1,
    randomizador: 3,
    parcela: 0,
    potencializador: 1,
    unidade: 'riqueza menor',
    modificador: '+%',
  },
  {
    nd: 5,
    min: 1,
    max: 15,
    faixa: '01-15',
    dinheiro: '—',
    multiplicador: 0,
    randomizador: 0,
    parcela: 0,
    potencializador: 0,
    unidade: '',
    modificador: '',
  },
  {
    nd: 5,
    min: 16,
    max: 65,
    faixa: '16-65',
    dinheiro: '1d8x100 T$',
    multiplicador: 1,
    randomizador: 8,
    parcela: 0,
    potencializador: 100,
    unidade: 'T$',
    modificador: '',
  },
  {
    nd: 5,
    min: 66,
    max: 95,
    faixa: '66-95',
    dinheiro: '3d4x10 TO',
    multiplicador: 3,
    randomizador: 4,
    parcela: 0,
    potencializador: 10,
    unidade: 'TO',
    modificador: '',
  },
  {
    nd: 5,
    min: 96,
    max: 100,
    faixa: '96-100',
    dinheiro: '1 riqueza média',
    multiplicador: 1,
    randomizador: 1,
    parcela: 0,
    potencializador: 1,
    unidade: 'riqueza média',
    modificador: '',
  },
  {
    nd: 6,
    min: 1,
    max: 15,
    faixa: '01-15',
    dinheiro: '—',
    multiplicador: 0,
    randomizador: 0,
    parcela: 0,
    potencializador: 0,
    unidade: '',
    modificador: '',
  },
  {
    nd: 6,
    min: 16,
    max: 60,
    faixa: '16-60',
    dinheiro: '2d6x100 T$',
    multiplicador: 2,
    randomizador: 6,
    parcela: 0,
    potencializador: 100,
    unidade: 'T$',
    modificador: '',
  },
  {
    nd: 6,
    min: 61,
    max: 90,
    faixa: '61-90',
    dinheiro: '2d10x100 T$',
    multiplicador: 2,
    randomizador: 10,
    parcela: 0,
    potencializador: 100,
    unidade: 'T$',
    modificador: '',
  },
  {
    nd: 6,
    min: 91,
    max: 100,
    faixa: '91-100',
    dinheiro: '1d3+1 riqueza menores',
    multiplicador: 1,
    randomizador: 3,
    parcela: 1,
    potencializador: 0,
    unidade: 'riqueza menor',
    modificador: '',
  },
  {
    nd: 7,
    min: 1,
    max: 10,
    faixa: '01-10',
    dinheiro: '—',
    multiplicador: 0,
    randomizador: 0,
    parcela: 0,
    potencializador: 0,
    unidade: '',
    modificador: '',
  },
  {
    nd: 7,
    min: 11,
    max: 60,
    faixa: '11-60',
    dinheiro: '2d8x100 T$',
    multiplicador: 2,
    randomizador: 8,
    parcela: 0,
    potencializador: 100,
    unidade: 'T$',
    modificador: '',
  },
  {
    nd: 7,
    min: 61,
    max: 90,
    faixa: '61-90',
    dinheiro: '2d12x10 TO',
    multiplicador: 2,
    randomizador: 12,
    parcela: 0,
    potencializador: 10,
    unidade: 'TO',
    modificador: '',
  },
  {
    nd: 7,
    min: 91,
    max: 100,
    faixa: '91-100',
    dinheiro: '1d4+1 riquezas menores',
    multiplicador: 1,
    randomizador: 4,
    parcela: 1,
    potencializador: 1,
    unidade: 'riqueza menor',
    modificador: '',
  },
  {
    nd: 8,
    min: 1,
    max: 10,
    faixa: '01-10',
    dinheiro: '—',
    multiplicador: 0,
    randomizador: 0,
    parcela: 0,
    potencializador: 0,
    unidade: '',
    modificador: '',
  },
  {
    nd: 8,
    min: 11,
    max: 55,
    faixa: '11-55',
    dinheiro: '2d10x100 T$',
    multiplicador: 2,
    randomizador: 10,
    parcela: 0,
    potencializador: 100,
    unidade: 'T$',
    modificador: '',
  },
  {
    nd: 8,
    min: 56,
    max: 95,
    faixa: '56-95',
    dinheiro: '1d4+1 riquezas menores',
    multiplicador: 1,
    randomizador: 4,
    parcela: 1,
    potencializador: 1,
    unidade: 'riqueza menor',
    modificador: '',
  },
  {
    nd: 8,
    min: 96,
    max: 100,
    faixa: '96-100',
    dinheiro: '1 riqueza média +%',
    multiplicador: 1,
    randomizador: 1,
    parcela: 0,
    potencializador: 1,
    unidade: 'riqueza média',
    modificador: '',
  },
  {
    nd: 9,
    min: 1,
    max: 10,
    faixa: '01-10',
    dinheiro: '—',
    multiplicador: 0,
    randomizador: 0,
    parcela: 0,
    potencializador: 0,
    unidade: '',
    modificador: '',
  },
  {
    nd: 9,
    min: 11,
    max: 35,
    faixa: '11-35',
    dinheiro: '1 riqueza média',
    multiplicador: 1,
    randomizador: 1,
    parcela: 0,
    potencializador: 1,
    unidade: 'riqueza média',
    modificador: '',
  },
  {
    nd: 9,
    min: 36,
    max: 85,
    faixa: '36-85',
    dinheiro: '4d6x100 T$',
    multiplicador: 4,
    randomizador: 6,
    parcela: 0,
    potencializador: 100,
    unidade: 'T$',
    modificador: '',
  },
  {
    nd: 9,
    min: 86,
    max: 100,
    faixa: '86-100',
    dinheiro: '1d3 riquezas médias',
    multiplicador: 1,
    randomizador: 3,
    parcela: 0,
    potencializador: 1,
    unidade: 'riqueza média',
    modificador: '',
  },
  {
    nd: 10,
    min: 1,
    max: 10,
    faixa: '01-10',
    dinheiro: '—',
    multiplicador: 0,
    randomizador: 0,
    parcela: 0,
    potencializador: 0,
    unidade: '',
    modificador: '',
  },
  {
    nd: 10,
    min: 11,
    max: 30,
    faixa: '11-30',
    dinheiro: '4d6x100 T$',
    multiplicador: 4,
    randomizador: 6,
    parcela: 0,
    potencializador: 100,
    unidade: 'T$',
    modificador: '',
  },
  {
    nd: 10,
    min: 31,
    max: 85,
    faixa: '31-85',
    dinheiro: '4d10x10 TO',
    multiplicador: 4,
    randomizador: 10,
    parcela: 0,
    potencializador: 10,
    unidade: 'TO',
    modificador: '',
  },
  {
    nd: 10,
    min: 86,
    max: 100,
    faixa: '86-100',
    dinheiro: '1d3+1 riquezas médias',
    multiplicador: 1,
    randomizador: 3,
    parcela: 1,
    potencializador: 1,
    unidade: 'riqueza média',
    modificador: '',
  },
  {
    nd: 11,
    min: 1,
    max: 10,
    faixa: '01-10',
    dinheiro: '—',
    multiplicador: 0,
    randomizador: 0,
    parcela: 0,
    potencializador: 0,
    unidade: '',
    modificador: '',
  },
  {
    nd: 11,
    min: 11,
    max: 45,
    faixa: '11-45',
    dinheiro: '2d4x1000 T$',
    multiplicador: 2,
    randomizador: 4,
    parcela: 0,
    potencializador: 1000,
    unidade: 'T$',
    modificador: '',
  },
  {
    nd: 11,
    min: 46,
    max: 85,
    faixa: '46-85',
    dinheiro: '1d3 riquezas médias',
    multiplicador: 1,
    randomizador: 3,
    parcela: 0,
    potencializador: 1,
    unidade: 'riqueza média',
    modificador: '',
  },
  {
    nd: 11,
    min: 86,
    max: 100,
    faixa: '86-100',
    dinheiro: '2d6x100 TO',
    multiplicador: 2,
    randomizador: 6,
    parcela: 0,
    potencializador: 100,
    unidade: 'TO',
    modificador: '',
  },
  {
    nd: 12,
    min: 1,
    max: 10,
    faixa: '01-10',
    dinheiro: '—',
    multiplicador: 0,
    randomizador: 0,
    parcela: 0,
    potencializador: 0,
    unidade: '',
    modificador: '',
  },
  {
    nd: 12,
    min: 11,
    max: 45,
    faixa: '11-45',
    dinheiro: '1 riqueza média +%',
    multiplicador: 1,
    randomizador: 1,
    parcela: 0,
    potencializador: 1,
    unidade: 'riqueza média',
    modificador: '+%',
  },
  {
    nd: 12,
    min: 46,
    max: 80,
    faixa: '46-80',
    dinheiro: '2d6x1000 T$',
    multiplicador: 2,
    randomizador: 6,
    parcela: 0,
    potencializador: 1000,
    unidade: 'T$',
    modificador: '',
  },
  {
    nd: 12,
    min: 81,
    max: 100,
    faixa: '81-100',
    dinheiro: '1d4+1 riquezas médias',
    multiplicador: 1,
    randomizador: 4,
    parcela: 1,
    potencializador: 1,
    unidade: 'riqueza média',
    modificador: '',
  },
  {
    nd: 13,
    min: 1,
    max: 10,
    faixa: '01-10',
    dinheiro: '—',
    multiplicador: 0,
    randomizador: 0,
    parcela: 0,
    potencializador: 0,
    unidade: '',
    modificador: '',
  },
  {
    nd: 13,
    min: 11,
    max: 45,
    faixa: '11-45',
    dinheiro: '4d4x1000 +%',
    multiplicador: 4,
    randomizador: 4,
    parcela: 0,
    potencializador: 1000,
    unidade: 'T$',
    modificador: '+%',
  },
  {
    nd: 13,
    min: 46,
    max: 80,
    faixa: '46-80',
    dinheiro: '1d3+1 riquezas médias',
    multiplicador: 1,
    randomizador: 3,
    parcela: 1,
    potencializador: 1,
    unidade: 'riqueza média',
    modificador: '',
  },
  {
    nd: 13,
    min: 81,
    max: 100,
    faixa: '81-100',
    dinheiro: '4d6x100 TO',
    multiplicador: 4,
    randomizador: 6,
    parcela: 0,
    potencializador: 100,
    unidade: 'TO',
    modificador: '',
  },
  {
    nd: 14,
    min: 1,
    max: 10,
    faixa: '01-10',
    dinheiro: '—',
    multiplicador: 0,
    randomizador: 0,
    parcela: 0,
    potencializador: 0,
    unidade: '',
    modificador: '',
  },
  {
    nd: 14,
    min: 11,
    max: 45,
    faixa: '11-45',
    dinheiro: '1d3+1 riquezas médias',
    multiplicador: 1,
    randomizador: 3,
    parcela: 1,
    potencializador: 1,
    unidade: 'riqueza média',
    modificador: '',
  },
  {
    nd: 14,
    min: 46,
    max: 80,
    faixa: '46-80',
    dinheiro: '3d6x1000 T$',
    multiplicador: 3,
    randomizador: 6,
    parcela: 0,
    potencializador: 1000,
    unidade: 'T$',
    modificador: '',
  },
  {
    nd: 14,
    min: 81,
    max: 100,
    faixa: '81-100',
    dinheiro: '1 riqueza maior',
    multiplicador: 1,
    randomizador: 1,
    parcela: 0,
    potencializador: 1,
    unidade: 'riqueza maior',
    modificador: '',
  },
  {
    nd: 15,
    min: 1,
    max: 10,
    faixa: '01-10',
    dinheiro: '—',
    multiplicador: 0,
    randomizador: 0,
    parcela: 0,
    potencializador: 0,
    unidade: '',
    modificador: '',
  },
  {
    nd: 15,
    min: 11,
    max: 45,
    faixa: '11-45',
    dinheiro: '1 riqueza média +%',
    multiplicador: 1,
    randomizador: 1,
    parcela: 0,
    potencializador: 1,
    unidade: 'riqueza média',
    modificador: '+%',
  },
  {
    nd: 15,
    min: 46,
    max: 80,
    faixa: '46-80',
    dinheiro: '2d10x1000 T$',
    multiplicador: 2,
    randomizador: 10,
    parcela: 0,
    potencializador: 1000,
    unidade: 'T$',
    modificador: '',
  },
  {
    nd: 15,
    min: 81,
    max: 100,
    faixa: '81-100',
    dinheiro: '1d4x1000 TO',
    multiplicador: 1,
    randomizador: 4,
    parcela: 0,
    potencializador: 1000,
    unidade: 'TO',
    modificador: '',
  },
  {
    nd: 16,
    min: 1,
    max: 10,
    faixa: '01-10',
    dinheiro: '—',
    multiplicador: 0,
    randomizador: 0,
    parcela: 0,
    potencializador: 0,
    unidade: '',
    modificador: '',
  },
  {
    nd: 16,
    min: 11,
    max: 40,
    faixa: '11-40',
    dinheiro: '3d6x1000 T$',
    multiplicador: 3,
    randomizador: 6,
    parcela: 0,
    potencializador: 1000,
    unidade: 'T$',
    modificador: '',
  },
  {
    nd: 16,
    min: 41,
    max: 75,
    faixa: '41-75',
    dinheiro: '3d10x100 TO',
    multiplicador: 3,
    randomizador: 10,
    parcela: 0,
    potencializador: 100,
    unidade: 'TO',
    modificador: '',
  },
  {
    nd: 16,
    min: 76,
    max: 100,
    faixa: '76-100',
    dinheiro: '1d3 riquezas maiores',
    multiplicador: 1,
    randomizador: 3,
    parcela: 0,
    potencializador: 1,
    unidade: 'riqueza maior',
    modificador: '',
  },
  {
    nd: 17,
    min: 1,
    max: 5,
    faixa: '01-05',
    dinheiro: '—',
    multiplicador: 0,
    randomizador: 0,
    parcela: 0,
    potencializador: 0,
    unidade: '',
    modificador: '',
  },
  {
    nd: 17,
    min: 6,
    max: 40,
    faixa: '06-40',
    dinheiro: '4d6x1000 T$',
    multiplicador: 4,
    randomizador: 6,
    parcela: 0,
    potencializador: 1000,
    unidade: 'T$',
    modificador: '',
  },
  {
    nd: 17,
    min: 41,
    max: 75,
    faixa: '41-75',
    dinheiro: '1d3 riquezas maiores +%',
    multiplicador: 1,
    randomizador: 3,
    parcela: 0,
    potencializador: 1,
    unidade: 'riqueza maior',
    modificador: '+%',
  },
  {
    nd: 17,
    min: 76,
    max: 100,
    faixa: '76-100',
    dinheiro: '2d4x1000 TO',
    multiplicador: 2,
    randomizador: 4,
    parcela: 0,
    potencializador: 1000,
    unidade: 'TO',
    modificador: '',
  },
  {
    nd: 18,
    min: 1,
    max: 5,
    faixa: '01-05',
    dinheiro: '—',
    multiplicador: 0,
    randomizador: 0,
    parcela: 0,
    potencializador: 0,
    unidade: '',
    modificador: '',
  },
  {
    nd: 18,
    min: 6,
    max: 40,
    faixa: '06-40',
    dinheiro: '4d10x1000 T$',
    multiplicador: 4,
    randomizador: 10,
    parcela: 0,
    potencializador: 1000,
    unidade: 'T$',
    modificador: '',
  },
  {
    nd: 18,
    min: 41,
    max: 75,
    faixa: '41-75',
    dinheiro: '1 riqueza maiores',
    multiplicador: 1,
    randomizador: 1,
    parcela: 0,
    potencializador: 1,
    unidade: 'riqueza maior',
    modificador: '',
  },
  {
    nd: 18,
    min: 76,
    max: 100,
    faixa: '76-100',
    dinheiro: '1d3+1 riquezas maiores',
    multiplicador: 1,
    randomizador: 3,
    parcela: 1,
    potencializador: 1,
    unidade: 'riqueza maior',
    modificador: '',
  },
  {
    nd: 19,
    min: 1,
    max: 5,
    faixa: '01-05',
    dinheiro: '—',
    multiplicador: 0,
    randomizador: 0,
    parcela: 0,
    potencializador: 0,
    unidade: '',
    modificador: '',
  },
  {
    nd: 19,
    min: 6,
    max: 40,
    faixa: '06-40',
    dinheiro: '4d12x1000 T$',
    multiplicador: 4,
    randomizador: 12,
    parcela: 0,
    potencializador: 1000,
    unidade: 'T$',
    modificador: '',
  },
  {
    nd: 19,
    min: 41,
    max: 75,
    faixa: '41-75',
    dinheiro: '1 riqueza maior +%',
    multiplicador: 1,
    randomizador: 1,
    parcela: 0,
    potencializador: 1,
    unidade: 'riqueza maior',
    modificador: '+%',
  },
  {
    nd: 19,
    min: 76,
    max: 100,
    faixa: '76-100',
    dinheiro: '1d12x1000 TO',
    multiplicador: 1,
    randomizador: 12,
    parcela: 0,
    potencializador: 1000,
    unidade: 'TO',
    modificador: '',
  },
  {
    nd: 20,
    min: 1,
    max: 5,
    faixa: '01-05',
    dinheiro: '—',
    multiplicador: 0,
    randomizador: 0,
    parcela: 0,
    potencializador: 0,
    unidade: '',
    modificador: '',
  },
  {
    nd: 20,
    min: 6,
    max: 40,
    faixa: '06-40',
    dinheiro: '2d4x1000 TO',
    multiplicador: 2,
    randomizador: 4,
    parcela: 0,
    potencializador: 1000,
    unidade: 'TO',
    modificador: '',
  },
  {
    nd: 20,
    min: 41,
    max: 75,
    faixa: '41-75',
    dinheiro: '1d3 riqueza maiores',
    multiplicador: 1,
    randomizador: 3,
    parcela: 0,
    potencializador: 1,
    unidade: 'riqueza maior',
    modificador: '',
  },
  {
    nd: 20,
    min: 76,
    max: 100,
    faixa: '76-100',
    dinheiro: '1d3+1 riquezas maiores +%',
    multiplicador: 1,
    randomizador: 3,
    parcela: 1,
    potencializador: 1,
    unidade: 'riqueza maior',
    modificador: '+%',
  },
];
export const tabelaRiquezaMenor = [
  { min: 1, max: 25, valor: '4d4 T$', multiplicador: 4, randomizador: 4, potencializador: 1, unidade: 'T$' },
  { min: 26, max: 40, valor: '1d4x10 T$', multiplicador: 1, randomizador: 4, potencializador: 10, unidade: 'T$' },
  { min: 41, max: 55, valor: '2d4x10 T$', multiplicador: 2, randomizador: 4, potencializador: 10, unidade: 'T$' },
  { min: 56, max: 70, valor: '4d6x10 T$', multiplicador: 4, randomizador: 6, potencializador: 10, unidade: 'T$' },
  { min: 71, max: 85, valor: '1d6x100 T$', multiplicador: 1, randomizador: 6, potencializador: 100, unidade: 'T$' },
  { min: 86, max: 95, valor: '2d6x100 T$', multiplicador: 2, randomizador: 6, potencializador: 100, unidade: 'T$' },
  { min: 96, max: 99, valor: '2d8x100 T$', multiplicador: 2, randomizador: 8, potencializador: 100, unidade: 'T$' },
  {
    min: 100,
    max: 100,
    valor: '4d10x100 T$',
    multiplicador: 4,
    randomizador: 10,
    potencializador: 100,
    unidade: 'T$',
  },
];

export const tabelaRiquezaMedia = [
  { min: 1, max: 10, valor: '2d4x10 T$', multiplicador: 2, randomizador: 4, potencializador: 10, unidade: 'T$' },
  { min: 11, max: 30, valor: '4d4x10 T$', multiplicador: 4, randomizador: 4, potencializador: 10, unidade: 'T$' },
  { min: 31, max: 50, valor: '1d6x100 T$', multiplicador: 1, randomizador: 6, potencializador: 100, unidade: 'T$' },
  { min: 51, max: 65, valor: '2d6x100 T$', multiplicador: 2, randomizador: 6, potencializador: 100, unidade: 'T$' },
  { min: 66, max: 80, valor: '2d8x100 T$', multiplicador: 2, randomizador: 8, potencializador: 100, unidade: 'T$' },
  { min: 81, max: 90, valor: '4d10x100 T$', multiplicador: 4, randomizador: 10, potencializador: 100, unidade: 'T$' },
  { min: 91, max: 95, valor: '6d12x100 T$', multiplicador: 6, randomizador: 12, potencializador: 100, unidade: 'T$' },
  {
    min: 96,
    max: 99,
    valor: '2d10x1000 T$',
    multiplicador: 2,
    randomizador: 10,
    potencializador: 1000,
    unidade: 'T$',
  },
  {
    min: 99,
    max: 100,
    valor: '6d8x1000 T$',
    multiplicador: 6,
    randomizador: 8,
    potencializador: 1000,
    unidade: 'T$',
  },
];

export const tabelaRiquezaMaior = [
  { min: 1, max: 5, valor: '1d6x100 T$', multiplicador: 1, randomizador: 6, potencializador: 100, unidade: 'T$' },
  { min: 6, max: 15, valor: '2d6x100 T$', multiplicador: 2, randomizador: 6, potencializador: 100, unidade: 'T$' },
  { min: 16, max: 25, valor: '2d8x100 T$', multiplicador: 2, randomizador: 8, potencializador: 100, unidade: 'T$' },
  { min: 26, max: 40, valor: '4d10x100 T$', multiplicador: 4, randomizador: 10, potencializador: 100, unidade: 'T$' },
  { min: 41, max: 60, valor: '6d12x100 T$', multiplicador: 6, randomizador: 12, potencializador: 100, unidade: 'T$' },
  {
    min: 61,
    max: 75,
    valor: '2d10x1000 T$',
    multiplicador: 2,
    randomizador: 10,
    potencializador: 1000,
    unidade: 'T$',
  },
  { min: 76, max: 85, valor: '6d8x1000 T$', multiplicador: 6, randomizador: 8, potencializador: 1000, unidade: 'T$' },
  {
    min: 86,
    max: 95,
    valor: '1d10x10000 T$',
    multiplicador: 1,
    randomizador: 10,
    potencializador: 10000,
    unidade: 'T$',
  },
  {
    min: 96,
    max: 100,
    valor: '4d12x10000 T$',
    multiplicador: 4,
    randomizador: 12,
    potencializador: 10000,
    unidade: 'T$',
  },
];

export const tabelaItensDiversos = [
  { id: 1, nome: 'Ácido', livro: 'Tormenta20', pagina: 160 },
  { id: 2, nome: 'Água benta', livro: 'Tormenta20', pagina: 155 },
  { id: 3, nome: 'Alaúde élfico', livro: 'Tormenta20', pagina: 158 },
  { id: 4, nome: 'Algemas', livro: 'Tormenta20', pagina: 155 },
  { id: 5, nome: 'Baga-de-fogo', livro: 'Tormenta20', pagina: 160 },
  { id: 6, nome: 'Bálsamo restaurador', livro: 'Tormenta20', pagina: 160 },
  { id: 7, nome: 'Bálsamo restaurador', livro: 'Tormenta20', pagina: 160 },
  { id: 8, nome: 'Bálsamo restaurador', livro: 'Tormenta20', pagina: 160 },
  { id: 9, nome: 'Bandana', livro: 'Tormenta20', pagina: 159 },
  { id: 10, nome: 'Bandoleira de poções', livro: 'Tormenta20', pagina: 155 },
  { id: 11, nome: 'Bomba', livro: 'Tormenta20', pagina: 160 },
  { id: 12, nome: 'Botas reforçadas', livro: 'Tormenta20', pagina: 159 },
  { id: 13, nome: 'Camisa bufante', livro: 'Tormenta20', pagina: 159 },
  { id: 14, nome: 'Capa esvoaçante', livro: 'Tormenta20', pagina: 159 },
  { id: 15, nome: 'Capa pesada', livro: 'Tormenta20', pagina: 159 },
  { id: 16, nome: 'Casaco longo', livro: 'Tormenta20', pagina: 159 },
  { id: 17, nome: 'Chapéu arcano', livro: 'Tormenta20', pagina: 159 },
  { id: 18, nome: 'Coleção de livros', livro: 'Tormenta20', pagina: 158 },
  { id: 19, nome: 'Cosmético', livro: 'Tormenta20', pagina: 160 },
  { id: 20, nome: 'Dente-de-dragão', livro: 'Tormenta20', pagina: 161 },
  { id: 21, nome: 'Enfeite de elmo', livro: 'Tormenta20', pagina: 159 },
  { id: 22, nome: 'Elixir do amor', livro: 'Tormenta20', pagina: 160 },
  { id: 23, nome: 'Equipamento de viagem', livro: 'Tormenta20', pagina: 155 },
  { id: 24, nome: 'Essência de mana', livro: 'Tormenta20', pagina: 160 },
  { id: 25, nome: 'Essência de mana', livro: 'Tormenta20', pagina: 160 },
  { id: 26, nome: 'Essência de mana', livro: 'Tormenta20', pagina: 160 },
  { id: 27, nome: 'Estojo de disfarces', livro: 'Tormenta20', pagina: 158 },
  { id: 28, nome: 'Farrapos de ermitão', livro: 'Tormenta20', pagina: 159 },
  { id: 29, nome: 'Flauta mística', livro: 'Tormenta20', pagina: 158 },
  { id: 30, nome: 'Fogo alquímico', livro: 'Tormenta20', pagina: 160 },
  { id: 31, nome: 'Gorro de ervas', livro: 'Tormenta20', pagina: 159 },
  { id: 32, nome: 'Líquen lilás', livro: 'Tormenta20', pagina: 161 },
  { id: 33, nome: 'Luneta', livro: 'Tormenta20', pagina: 158 },
  { id: 34, nome: 'Luva de pelica', livro: 'Tormenta20', pagina: 159 },
  { id: 35, nome: 'Maleta de medicamentos', livro: 'Tormenta20', pagina: 158 },
  { id: 36, nome: 'Manopla', livro: 'Tormenta20', pagina: 159 },
  { id: 37, nome: 'Manto eclesiástico', livro: 'Tormenta20', pagina: 159 },
  { id: 38, nome: 'Mochila de aventureiro', livro: 'Tormenta20', pagina: 155 },
  { id: 39, nome: 'Musgo púrpura', livro: 'Tormenta20', pagina: 161 },
  { id: 40, nome: 'Organizador de pergaminhos', livro: 'Tormenta20', pagina: 155 },
  { id: 41, nome: 'Ossos de monstro', livro: 'Tormenta20', pagina: 161 },
  { id: 42, nome: 'Pó de cristal', livro: 'Tormenta20', pagina: 161 },
  { id: 43, nome: 'Pó de giz', livro: 'Tormenta20', pagina: 161 },
  { id: 44, nome: 'Pó do desaparecimento', livro: 'Tormenta20', pagina: 160 },
  { id: 45, nome: 'Robe místico', livro: 'Tormenta20', pagina: 159 },
  { id: 46, nome: 'Saco de sal', livro: 'Tormenta20', pagina: 161 },
  { id: 47, nome: 'Sapatos de camurça', livro: 'Tormenta20', pagina: 159 },
  { id: 48, nome: 'Seixo de âmbar', livro: 'Tormenta20', pagina: 161 },
  { id: 49, nome: 'Sela', livro: 'Tormenta20', pagina: 158 },
  { id: 50, nome: 'Tabardo', livro: 'Tormenta20', pagina: 159 },
  { id: 51, nome: 'Traje da corte', livro: 'Tormenta20', pagina: 159 },
  { id: 52, nome: 'Terra de cemitério', livro: 'Tormenta20', pagina: 161 },
  { id: 53, nome: 'Veste de seda', livro: 'Tormenta20', pagina: 159 },
  { id: 54, nome: 'Corda de teia', livro: 'Ameaças de Arton', pagina: 396 },
  { id: 55, nome: 'Dente de wisphago', livro: 'Ameaças de Arton', pagina: 396 },
  { id: 56, nome: 'Bomba de fumaça', livro: 'Ameaças de Arton', pagina: 396 },
  { id: 57, nome: 'Elixir quimérico', livro: 'Ameaças de Arton', pagina: 396 },
  { id: 58, nome: 'Éter elemental', livro: 'Ameaças de Arton', pagina: 396 },
  { id: 59, nome: 'Óleo de besouro', livro: 'Ameaças de Arton', pagina: 397 },
  { id: 60, nome: 'Água benta concentrada', livro: 'Deuses de Arton', pagina: 48 },
  { id: 61, nome: 'Aspersório', livro: 'Deuses de Arton', pagina: 48 },
  { id: 62, nome: 'Patuá', livro: 'Deuses de Arton', pagina: 49 },
  { id: 63, nome: 'Panfleto de aforismos', livro: 'Deuses de Arton', pagina: 49 },
  { id: 64, nome: 'Texto sagrado', livro: 'Deuses de Arton', pagina: 49 },
  { id: 65, nome: 'Hábito sacerdotal', livro: 'Deuses de Arton', pagina: 49 },
  { id: 66, nome: 'Manto de alto sacerdote', livro: 'Deuses de Arton', pagina: 49 },
  { id: 67, nome: 'Sandálias', livro: 'Deuses de Arton', pagina: 51 },
  { id: 68, nome: 'Piercing de umbigo', livro: 'Deuses de Arton', pagina: 51 },
  { id: 69, nome: 'Incenso', livro: 'Deuses de Arton', pagina: 52 },
  { id: 70, nome: 'Santa granada de mão', livro: 'Deuses de Arton', pagina: 52 },
  { id: 71, nome: 'Fitilho consagrado', livro: 'Deuses de Arton', pagina: 52 },
  { id: 72, nome: 'Pena de anjo', livro: 'Deuses de Arton', pagina: 52 },
  { id: 73, nome: 'Ábaco', livro: 'Heróis de Arton', pagina: 227 },
  { id: 74, nome: 'Ampulheta', livro: 'Heróis de Arton', pagina: 227 },
  { id: 75, nome: 'Astrolábio', livro: 'Heróis de Arton', pagina: 227 },
  { id: 76, nome: 'Bainha adornada', livro: 'Heróis de Arton', pagina: 227 },
  { id: 77, nome: 'Bússola', livro: 'Heróis de Arton', pagina: 227 },
  { id: 78, nome: 'Diagrama anatômico', livro: 'Heróis de Arton', pagina: 230 },
  { id: 79, nome: 'Estrepes', livro: 'Heróis de Arton', pagina: 230 },
  { id: 80, nome: 'Lampião de foco', livro: 'Heróis de Arton', pagina: 230 },
  { id: 81, nome: 'Leque', livro: 'Heróis de Arton', pagina: 230 },
  { id: 82, nome: 'Lupa', livro: 'Heróis de Arton', pagina: 230 },
  { id: 83, nome: 'Mapa (mestre define de qual região)', livro: 'Heróis de Arton', pagina: 230 },
  { id: 84, nome: 'Mecanismo de mola', livro: 'Heróis de Arton', pagina: 230 },
  { id: 85, nome: 'Mochila discreta', livro: 'Heróis de Arton', pagina: 230 },
  { id: 86, nome: 'Sinete', livro: 'Heróis de Arton', pagina: 231 },
  { id: 87, nome: 'Apito de caça', livro: 'Heróis de Arton', pagina: 231 },
  { id: 88, nome: 'Baralho marcado', livro: 'Heróis de Arton', pagina: 231 },
  { id: 89, nome: 'Clarim deheoni', livro: 'Heróis de Arton', pagina: 231 },
  { id: 90, nome: 'Pandeiro das estradas', livro: 'Heróis de Arton', pagina: 231 },
  { id: 91, nome: 'Camisolão', livro: 'Heróis de Arton', pagina: 232 },
  { id: 92, nome: 'Casaca de apetrechos', livro: 'Heróis de Arton', pagina: 232 },
  { id: 93, nome: 'Chapéu emplumado', livro: 'Heróis de Arton', pagina: 232 },
  { id: 94, nome: 'Elmo leve', livro: 'Heróis de Arton', pagina: 232 },
  { id: 95, nome: 'Elmo pesado', livro: 'Heróis de Arton', pagina: 232 },
  { id: 96, nome: 'Rondel', livro: 'Heróis de Arton', pagina: 233 },
  { id: 97, nome: 'Sapatos confortáveis', livro: 'Heróis de Arton', pagina: 233 },
  { id: 98, nome: 'Sapatos de salto alto', livro: 'Heróis de Arton', pagina: 233 },
  { id: 99, nome: 'Ácido concentrado', livro: 'Heróis de Arton', pagina: 234 },
  { id: 100, nome: 'Frasco abissal', livro: 'Heróis de Arton', pagina: 234 },
];
