// models.ts
export type TreasureContext = {
  type: string;
  level: number;
  notes?: string;
  random?: number;
};

export type GeneratedTreasure = {
  items: any[];
  return: string;
  notes?: string;
  report?: string;
};

export const tabelaTesouroItens = [
        { nd: 0.25, min: 1,   max: 50,   faixa: '01-50',   valor: '—', modificador: '', tipo: '' },
        { nd: 0.25, min: 51,  max: 75,   faixa: '51-75',   valor: 'Item diverso', modificador: '', tipo: 'miscellaneous-item' },
        { nd: 0.25, min: 76,  max: 100,  faixa: '76-100',  valor: 'Equipamento', modificador: '', tipo: 'equipment' },
        { nd: 0.5, min: 1,   max: 45,   faixa: '01-45',   valor: '—', modificador: '', tipo: '' },
        { nd: 0.5, min: 46,  max: 70,   faixa: '46-70',   valor: 'Item diverso', modificador: '', tipo: 'miscellaneous-item' },
        { nd: 0.5, min: 71,  max: 100,  faixa: '71-100',  valor: 'Equipamento', modificador: '', tipo: 'equipment' },
        { nd: 1, min: 1,   max: 40,   faixa: '01-40',   valor: '—', modificador: '', tipo: '' },
        { nd: 1, min: 41,  max: 65,   faixa: '41-65',   valor: 'Item diverso', modificador: '', tipo: 'miscellaneous-item' },
        { nd: 1, min: 66,  max: 90,   faixa: '66-90',   valor: 'Equipamento', modificador: '', tipo: 'equipment' },
        { nd: 1, min: 91,  max: 100,  faixa: '91-100',  valor: '1 poção', modificador: '', tipo: 'potion' },
        { nd: 2, min: 1,   max: 30,    faixa: '01-30',   valor: '—', modificador: '', tipo: '' },
        { nd: 2, min: 31,  max: 40,    faixa: '31-40',   valor: 'Item diverso', modificador: '', tipo: 'miscellaneous-item' },
        { nd: 2, min: 41,  max: 70,    faixa: '41-70',   valor: 'Equipamento', modificador: '', tipo: 'equipment' },
        { nd: 2, min: 71,  max: 90,    faixa: '71-90',   valor: '1 poção', modificador: '', tipo: 'potion' },
        { nd: 2, min: 91,  max: 100,   faixa: '91-100',  valor: 'Superior (1 melhoria)', modificador: '(1 melhoria)', tipo: 'equipment' },
        { nd: 3, min: 1,   max: 25,    faixa: '01-25',   valor: '—', modificador: '', tipo: '' },
        { nd: 3, min: 26,  max: 35,    faixa: '26-35',   valor: 'Item diverso', modificador: '', tipo: 'miscellaneous-item' },
        { nd: 3, min: 36,  max: 60,    faixa: '36-60',   valor: 'Equipamento', modificador: '', tipo: 'equipment' },
        { nd: 3, min: 61,  max: 85,    faixa: '61-85',   valor: '1 poção', modificador: '', tipo: 'potion' },
        { nd: 3, min: 86,  max: 100,   faixa: '91-100',  valor: 'Superior (1 melhoria)', modificador: '(1 melhoria)', tipo: 'equipment' },
        { nd: 4, min: 1,   max: 20,    faixa: '01-20',   valor: '—', modificador: '', tipo: '' },
        { nd: 4, min: 21,  max: 30,    faixa: '21-30',   valor: 'Item diverso', modificador: '', tipo: 'miscellaneous-item' },
        { nd: 4, min: 31,  max: 55,    faixa: '31-55',   valor: 'Equipamento 2D', modificador: '2D', tipo: 'equipment' },
        { nd: 4, min: 56,  max: 80,    faixa: '56-80',   valor: '1 poção +%', modificador: '+%', tipo: 'potion' },
        { nd: 4, min: 81,  max: 100,   faixa: '81-100',  valor: 'Superior (1 melhoria) 2D', modificador: '(1 melhoria) 2D', tipo: 'equipment' },
        { nd: 5, min: 1,   max: 20,     faixa: '01-20',     valor: '—', modificador: '', tipo: '' },
        { nd: 5, min: 21,  max: 70,     faixa: '21-70',     valor: '1 poção', modificador: '', tipo: 'potion' },
        { nd: 5, min: 71,  max: 90,     faixa: '71-90',     valor: 'Superior (1 melhoria)', modificador: '(1 melhoria)', tipo: 'equipment' },
        { nd: 5, min: 91,  max: 100,    faixa: '91-1000',   valor: 'Superior (2 melhorias)', modificador: '(2 melhorias)', tipo: 'equipment' },
        { nd: 6, min: 1,   max: 20,     faixa: '01-20',    valor: '—', modificador: '', tipo: '' },
        { nd: 6, min: 21,  max: 65,     faixa: '21-65',    valor: '1 poção +%', modificador: '+%', tipo: 'potion' },
        { nd: 6, min: 66,  max: 95,     faixa: '66-95',    valor: 'Superior (1 melhoria)', modificador: '(1 melhoria)', tipo: 'equipment' },
        { nd: 6, min: 96,  max: 100,    faixa: '96-100',   valor: 'Superior (2 melhorias) 2D', modificador: '(2 melhorias) 2D', tipo: 'equipment' },
        { nd: 7, min: 1,   max: 20,     faixa: '01-20',    valor: '—', modificador: '', tipo: '' },
        { nd: 7, min: 21,  max: 60,     faixa: '21-60',    valor: '1d3 poções', modificador: '1d3', tipo: 'potion' },
        { nd: 7, min: 61,  max: 90,     faixa: '61-90',    valor: 'Superior (2 melhorias)', modificador: '(2 melhorias)', tipo: 'equipment' },
        { nd: 7, min: 91,  max: 100,    faixa: '91-100',   valor: 'Superior (3 melhorias)', modificador: '(3 melhorias)', tipo: 'equipment' },
        { nd: 8, min: 1,   max: 20,     faixa: '01-20',    valor: '—', modificador: '', tipo: '' },
        { nd: 8, min: 21,  max: 75,     faixa: '21-75',    valor: '1d3 poções', modificador: '1d3', tipo: 'potion' },
        { nd: 8, min: 76,  max: 95,     faixa: '76-95',    valor: 'Superior (2 melhorias)', modificador: '(2 melhorias)', tipo: 'equipment' },
        { nd: 8, min: 96,  max: 100,    faixa: '96-100',   valor: 'Superior (3 melhorias) 2D', modificador: '(3 melhorias) 2D', tipo: 'equipment' },
        { nd: 9, min: 1,   max: 20,     faixa: '01-20',    valor: '—', modificador: '', tipo: '' },
        { nd: 9, min: 21,  max: 70,     faixa: '21-70',    valor: '1 poção +%', modificador: '+%', tipo: 'potion' },
        { nd: 9, min: 71,  max: 95,     faixa: '71-95',    valor: 'Superior (3 melhorias)', modificador: '(3 melhorias)', tipo: 'equipment' },
        { nd: 9, min: 96,  max: 100,    faixa: '96-100',   valor: 'Mágico (menor)', modificador: '(menor)', tipo: 'magic-equipment' },
        { nd: 10, min: 1,   max: 50,     faixa: '01-50',    valor: '—', modificador: '', tipo: '' },
        { nd: 10, min: 51,  max: 75,     faixa: '51-75',    valor: '1d3+1 poções', modificador: '1d3', tipo: 'potion' },
        { nd: 10, min: 76,  max: 90,     faixa: '76-90',    valor: 'Superior (3 melhorias)', modificador: '(3 melhorias)', tipo: 'equipment' },
        { nd: 10, min: 91,  max: 100,    faixa: '96-100',   valor: 'Mágico (menor)', modificador: '(menor)', tipo: 'magic-equipment' },
        { nd: 11, min: 1,   max: 45,     faixa: '01-45',    valor: '—', modificador: '', tipo: '' },
        { nd: 11, min: 46,  max: 70,     faixa: '46-70',    valor: '1d4+1 poções', modificador: '1d4+1', tipo: 'potion' },
        { nd: 11, min: 71,  max: 90,     faixa: '71-90',    valor: 'Superior (3 melhorias)', modificador: '(3 melhorias)', tipo: 'equipment' },
        { nd: 11, min: 91,  max: 100,    faixa: '91-100',   valor: 'Mágico (menor) 2D', modificador: '(menor) 2D', tipo: 'magic-equipment' },
        { nd: 12, min: 1,   max: 45,     faixa: '01-45',    valor: '—', modificador: '', tipo: '' },
        { nd: 12, min: 46,  max: 70,     faixa: '46-70',    valor: '1d3+1 poções +%', modificador: '1d3+1 +%', tipo: 'potion' },
        { nd: 12, min: 71,  max: 85,     faixa: '71-85',    valor: 'Superior (4 melhorias)', modificador: '(4 melhorias)', tipo: 'equipment' },
        { nd: 12, min: 86,  max: 100,    faixa: '86-100',   valor: 'Mágico (menor)', modificador: '(menor)', tipo: 'magic-equipment' },
        { nd: 13, min: 1,   max: 40,     faixa: '01-40',    valor: '—', modificador: '', tipo: '' },
        { nd: 13, min: 41,  max: 65,     faixa: '41-65',    valor: '1d4+1 poções +%', modificador: '1d4+1 +%', tipo: 'potion' },
        { nd: 13, min: 66,  max: 95,     faixa: '66-95',    valor: 'Superior (4 melhorias)', modificador: '(4 melhorias)', tipo: 'equipment' },
        { nd: 13, min: 96,  max: 100,    faixa: '96-100',   valor: 'Mágico (médio)', modificador: '(médio)', tipo: 'magic-equipment' },
        { nd: 14, min: 1,   max: 40,     faixa: '01-40',    valor: '—', modificador: '', tipo: ''},
        { nd: 14, min: 41,  max: 65,     faixa: '41-65',    valor: '1d4+1 poções +%', modificador: '1d4+1 +%', tipo: 'potion' },
        { nd: 14, min: 66,  max: 90,     faixa: '66-90',    valor: 'Superior (4 melhorias)', modificador: '(4 melhorias)', tipo: 'equipment' },
        { nd: 14, min: 91,  max: 100,    faixa: '91-100',   valor: 'Mágico (médio)', modificador: '(médio)', tipo: 'magic-equipment' },
        { nd: 15, min: 1,   max: 35,     faixa: '01-35',    valor: '—', modificador: '', tipo: '' },
        { nd: 15, min: 36,  max: 45,     faixa: '36-45',    valor: '1d6+1 poções', modificador: '1d6+1', tipo: 'potion' },
        { nd: 15, min: 46,  max: 85,     faixa: '46-85',    valor: 'Superior (4 melhorias) 2D', modificador: '(4 melhorias) 2D', tipo: 'equipment' },
        { nd: 15, min: 86,  max: 100,    faixa: '86-100',   valor: 'Mágico (médio)', modificador: '(médio)', tipo: 'magic-equipment' },
        { nd: 16, min: 1,   max: 35,     faixa: '01-35',    valor: '—', modificador: '', tipo: '' },
        { nd: 16, min: 36,  max: 45,     faixa: '36-45',    valor: '1d6+1 poções +%', modificador: '1d6+1 +%', tipo: 'potion' },
        { nd: 16, min: 46,  max: 85,     faixa: '46-85',    valor: 'Superior (4 melhorias) 2D', modificador: '(4 melhorias) 2D', tipo: 'equipment' },
        { nd: 16, min: 86,  max: 100,    faixa: '86-100',   valor: 'Mágico (médio)', modificador: '(médio)', tipo: 'magic-equipment' },
        { nd: 17, min: 1,   max: 20,     faixa: '01-20',    valor: '—', modificador: '', tipo: ''},
        { nd: 17, min: 21,  max: 40,     faixa: '21-40',    valor: 'Mágico (menor)', modificador: '(menor)', tipo: 'magic-equipment' },
        { nd: 17, min: 41,  max: 80,     faixa: '46-80',    valor: 'Mágico (médio)', modificador: '(médio)', tipo: 'magic-equipment' },
        { nd: 17, min: 81,  max: 100,    faixa: '81-100',   valor: 'Mágico (maior)', modificador: '(maior)', tipo: 'magic-equipment' },
        { nd: 18, min: 1,   max: 15,     faixa: '01-15',    valor: '—', modificador: '', tipo: '' },
        { nd: 18, min: 16,  max: 40,     faixa: '16-40',    valor: 'Mágico (menor) 2D', modificador: '(menor) 2D', tipo: 'magic-equipment' },
        { nd: 18, min: 41,  max: 70,     faixa: '41-70',    valor: 'Mágico (médio)', modificador: '(médio)', tipo: 'magic-equipment' },
        { nd: 18, min: 71,  max: 100,    faixa: '71-100',   valor: 'Mágico (maior)', modificador: '(maior)', tipo: 'magic-equipment' },
        { nd: 19, min: 1,   max: 10,     faixa: '01-10',    valor: '—', modificador: '', tipo: '' },
        { nd: 19, min: 11,  max: 40,     faixa: '11-40',    valor: 'Mágico (menor) 2D', modificador: '(menor) 2D', tipo: 'magic-equipment' },
        { nd: 19, min: 41,  max: 60,     faixa: '41-60',    valor: 'Mágico (médio) 2D', modificador: '(médio) 2D', tipo: 'magic-equipment' },
        { nd: 19, min: 61,  max: 100,    faixa: '61-100',   valor: 'Mágico (maior)', modificador: '(maior)', tipo: 'magic-equipment' },
        { nd: 20, min: 1,   max: 10,     faixa: '01-05',    valor: '—', modificador: '', tipo: '' },
        { nd: 20, min: 6,   max: 40,     faixa: '06-40',    valor: 'Mágico (menor) 2D', modificador: '(menor) 2D', tipo: 'magic-equipment' },
        { nd: 20, min: 41,  max: 60,     faixa: '41-60',    valor: 'Mágico (médio) 2D', modificador: '(médio) 2D', tipo: 'magic-equipment' },
        { nd: 20, min: 61,  max: 100,    faixa: '61-100',   valor: 'Mágico (maior) 2D', modificador: '(maior) 2D', tipo: 'magic-equipment' },
    ]