export enum AlvoMagia {
    VOCE = 'Você',
    CRIATURA = 'Criatura',
    CRIATURAS_ESCOLHIDAS = 'Criaturas Escolhidas',
    CRIATURAS_VOLUNTARIAS = 'Criaturas Voluntárias',
    CRIATURA_OBJETO = 'Criatura ou Objeto',
    CADAVER = 'Cadáver',
    AREA_OBJETO = 'Área ou Objeto',
    CRIATURA_OBJETO_AREA = 'Criatura, Área ou Objeto',
    CRIATURA_AREA = 'Criatura ou Área',
    HUMANOIDE = 'Humanóide',
    ANIMAL = 'Animal',
    PLANTA = 'Planta',
    CONSTRUTO = 'Construto',
    MONSTRO = 'Monstro',
    ESPIRITO = 'Espírito',
    OBJETO = 'Objeto',
    AREA = 'Área',
    ESFERA = 'Esfera',
    
}