export enum DuracaoMagia {
    INSTANTANEA = 'Instantânea',
    SUSTENTADA = 'Sustentada',
    TURNO = 'Turno',
    RODADA = 'Rodada(s)',
    RODADA_VARIAVEL = 'Rodada(s) Variaveis',
    CENA = 'Cena',
    CENA_DESCARREGADA = 'Cena ou Descarregar',
    CONDICIONAL = 'Condicional',
    DIA = 'Dia',
    SEMANA = 'Semana',
    PERMANENTE = 'Permanente',
    UM_MINUTO = 'Um Minuto',
    UMA_HORA = 'Uma Hora',
    VARIAVEL = 'Variável',
}