export enum DuracaoMagia {
    INSTANTANEA = 'Instantânea',
    TURNO = 'Um turno',
    RODADA = 'Uma rodada',
    D4_RODADAS = '1d4 rodadas',
    SUSTENTADA = 'Sustentada',
    CENA = 'Cena',
    DIA = 'Um dia',
    D4_DIAS = '1d4 dias',
    SEMANA = 'Uma semana',
    UM_MINUTO = 'Um minuto',
    UMA_HORA = 'Uma hora',
    UM_ANO = 'Um ano',
    PERMANENTE = 'Permanente',
    DESCARREGADA = 'Ou até ser descarregada',
    ATE_CHEGAR_SOLO = 'Ou até chegar ao solo, o que vier primeiro.',
    ESPECIAL = 'Especial',
    VEJA_TEXTO = 'Veja texto',


    RODADA_VARIAVEL = '',
    CONDICIONAL = '',
    ANO = '',
    VARIAVEL = '',
}