export enum OpcoesAtributosRaca {
    UM_ATRIBUTO = '1 ATRIBUTO',
    DOIS_ATRIBUTOS_DIFERENTES = '2 ATRIBUTOS DIFERENTES',
    TRES_ATRIBUTOS_DIFERENTES = '3 ATRIBUTOS DIFERENTES',
    DOIS_ATRIBUTOS = '2 ATRIBUTOS',
    EXCETO = 'EXCETO',
  }