export enum TipoItem {
    ARMA = "1.Arma",
    MUNICAO = "2.Munição",
    ARMADURA = "3.Armadura",
    EQUIPAMENTO_AVENTURA = "4.Equipamento de Aventura",
    FERRAMENTA = "5.Ferramenta",
    VESTUARIO = "6.Vestuário",
    ESOTERICO = "7.Esotérico",
    ALQUIMICO = "8.Alquímico",
    ALIMENTACAO = "9.Alimentação",
    ANIMAIS = "10.Animais",
    VEICULOS = "11.Veículos",
    SERVICOS = "12.Serviços",
    MELHORIAS = "13.Melhorias",
    RIQUEZAS = "14.Riquezas",
    ENCANTOS = "15.Encantos",
    POCOES_MAGICAS = "16.Encantos",
    ACESSORIOS_MAGICOS = "17.Acessórios Mágicos",
    ARTEFATOS = "18.Artefatos",
}