export enum TipoItem {
    ARMA = "1.Arma",
    MUNICAO = "2.Munição",
    ARMADURA = "3.Armadura",
    EQUIPAMENTO_AVENTURA = "4.Equipamento de Aventura",
    FERRAMENTA = "5.Ferramenta",
    VESTUARIO = "6.Vestuário",
    ESOTERICO = "7.Esotérico",
    ALQUIMICO = "8.Alquímico",
    ALIMENTACAO = "9.Alimentação",
    ANIMAIS = "10.Animais",
    VEICULOS = "11.Veículos",
    SERVICOS = "13.Serviços",
    MELHORIAS = "14.Melhorias",
    RIQUEZAS = "15.Riquezas",
    ENCANTOS = "16.Encantos",
    POCOES_MAGICAS = "17.Encantos",
    ACESSORIOS_MAGICOS = "18.Acessórios Mágicos",
    ARTEFATOS = "19.Artefatos",
}